import { Framework } from '@/lib/types'

export const MOCK_FRAMEWORKS: Framework[] = [
  {
    id: 'fw-circles',
    name: 'CIRCLES',
    purpose: 'A structured method for answering product design questions by walking through seven sequential steps from comprehension to summary.',
    steps: [
      'Comprehend the situation — clarify the question and context',
      'Identify the customer — define who the user is',
      'Report the customer\'s needs — list pain points and goals',
      'Cut through prioritization — rank the needs by impact',
      'List solutions — brainstorm ideas for the top needs',
      'Evaluate trade-offs — weigh pros and cons of each solution',
      'Summarize your recommendation — present the winning solution with rationale',
    ],
    when_to_use: 'Use for product design interview questions, especially "Design a product for X" or "How would you improve Y?" prompts.',
    domain: 'product-strategy',
  },
  {
    id: 'fw-heart',
    name: 'HEART',
    purpose: 'A Google-developed framework for measuring user experience quality across five dimensions, paired with Goals-Signals-Metrics mapping.',
    steps: [
      'Happiness — measure user satisfaction (e.g., NPS, CSAT surveys)',
      'Engagement — track depth of interaction (e.g., session duration, actions per session)',
      'Adoption — measure new user uptake of a feature or product',
      'Retention — track how many users return over time',
      'Task success — measure efficiency and completion rate of key workflows',
    ],
    when_to_use: 'Use when defining UX metrics for a feature or product, especially when stakeholders ask "how do we know if this is working for users?"',
    domain: 'metrics-analytics',
  },
  {
    id: 'fw-rice',
    name: 'RICE',
    purpose: 'A quantitative prioritization framework that scores initiatives by Reach, Impact, Confidence, and Effort to produce a comparable priority score.',
    steps: [
      'Estimate Reach — how many users will this affect per time period?',
      'Rate Impact — on a scale (3=massive, 2=high, 1=medium, 0.5=low, 0.25=minimal)',
      'Assess Confidence — how sure are you of your estimates? (100%=high, 80%=medium, 50%=low)',
      'Estimate Effort — how many person-months will this take?',
      'Calculate score — (Reach x Impact x Confidence) / Effort',
    ],
    when_to_use: 'Use when you need to objectively compare and rank a backlog of features or initiatives, especially when stakeholders disagree on priorities.',
    domain: 'prioritization',
  },
  {
    id: 'fw-ice',
    name: 'ICE',
    purpose: 'A lightweight prioritization scoring model where each initiative is rated on Impact, Confidence, and Ease, then multiplied for a quick rank.',
    steps: [
      'Rate Impact — how much will this move the target metric? (1-10)',
      'Rate Confidence — how confident are you in the impact estimate? (1-10)',
      'Rate Ease — how easy is this to implement? (1-10)',
      'Multiply the three scores for a composite ICE score',
      'Rank initiatives by score and discuss the top candidates',
    ],
    when_to_use: 'Use for fast prioritization in growth teams or when you need a quick gut-check ranking without deep estimation effort.',
    domain: 'prioritization',
  },
  {
    id: 'fw-aarrr',
    name: 'AARRR (Pirate Metrics)',
    purpose: 'A funnel framework that maps the full user lifecycle across five stages: Acquisition, Activation, Retention, Referral, and Revenue.',
    steps: [
      'Acquisition — how do users find you? (channels, CAC)',
      'Activation — do users experience the core value? (aha moment, onboarding completion)',
      'Retention — do users come back? (D1/D7/D30 retention, churn rate)',
      'Referral — do users tell others? (viral coefficient, NPS)',
      'Revenue — do users pay? (conversion rate, ARPU, LTV)',
    ],
    when_to_use: 'Use when diagnosing where the biggest drop-off is in your growth funnel, or when structuring a growth strategy from scratch.',
    domain: 'metrics-analytics',
  },
  {
    id: 'fw-jtbd',
    name: 'Jobs To Be Done',
    purpose: 'A demand-side innovation framework that reframes products as "hired" by users to accomplish a functional, emotional, or social job.',
    steps: [
      'Identify the job — what is the user trying to accomplish in their life?',
      'Map the context — when and where does this job arise?',
      'Uncover the struggle — what makes the current solution inadequate?',
      'Define success criteria — what does "done well" look like from the user\'s perspective?',
      'Evaluate alternatives — what are users currently "hiring" to do this job?',
      'Design for the job — build a solution that nails the core job better than alternatives',
    ],
    when_to_use: 'Use when exploring new product opportunities, validating feature ideas, or reframing a problem away from feature requests toward user motivations.',
    domain: 'user-research',
  },
  {
    id: 'fw-5whys',
    name: '5 Whys',
    purpose: 'A root cause analysis technique that drills past symptoms by asking "why?" iteratively until the fundamental cause is revealed.',
    steps: [
      'State the problem clearly and specifically',
      'Ask "Why does this happen?" and document the answer',
      'Ask "Why?" again on that answer',
      'Repeat until you reach a root cause (typically 3-5 iterations)',
      'Verify the root cause by checking if fixing it would prevent the original problem',
    ],
    when_to_use: 'Use when investigating metric drops, bug patterns, user complaints, or any situation where the obvious explanation feels like a symptom rather than a cause.',
    domain: 'metrics-analytics',
  },
  {
    id: 'fw-north-star',
    name: 'North Star Metric',
    purpose: 'A strategic alignment framework for selecting the single metric that best captures the core value your product delivers, guiding the entire organization.',
    steps: [
      'Identify your product\'s core value — what "job" does it do for users?',
      'Map value to a measurable behavior — what action proves a user received value?',
      'Validate alignment — does improving this metric also drive business growth?',
      'Define input metrics — what 3-5 levers influence the North Star?',
      'Communicate and embed — make the NSM visible across all teams and dashboards',
    ],
    when_to_use: 'Use when aligning a product team around a single success measure, or when leadership asks "what is the one number we should obsess over?"',
    domain: 'metrics-analytics',
  },
  {
    id: 'fw-kano',
    name: 'Kano Model',
    purpose: 'A feature classification framework that categorizes capabilities by their relationship to user satisfaction: basic, performance, and delight.',
    steps: [
      'List candidate features or capabilities',
      'Survey users with functional/dysfunctional question pairs for each feature',
      'Classify each feature: Must-Be (basic), One-Dimensional (performance), Attractive (delight), Indifferent, or Reverse',
      'Prioritize Must-Be features first, then Performance, then Attractive',
      'Revisit over time — Attractive features decay into Must-Be as user expectations rise',
    ],
    when_to_use: 'Use when deciding which features to build in a new product or major release, especially to balance table-stakes requirements with differentiating delighters.',
    domain: 'prioritization',
  },
  {
    id: 'fw-moscow',
    name: 'MoSCoW',
    purpose: 'A requirement prioritization method that sorts items into Must have, Should have, Could have, and Won\'t have categories for a given timebox.',
    steps: [
      'List all requirements or features for the release',
      'Must have — non-negotiable; the release fails without these',
      'Should have — important but not critical; workarounds exist',
      'Could have — nice-to-have; include if time and resources allow',
      'Won\'t have (this time) — explicitly out of scope for this cycle',
    ],
    when_to_use: 'Use during sprint planning or release scoping when the team needs to draw a clear line between what ships and what waits.',
    domain: 'prioritization',
  },
  {
    id: 'fw-impact-effort',
    name: 'Impact-Effort Matrix',
    purpose: 'A 2x2 visualization tool that plots initiatives by expected impact versus implementation effort to identify quick wins and big bets.',
    steps: [
      'List all candidate initiatives',
      'Score each on Impact (low to high) — how much will it move the target metric?',
      'Score each on Effort (low to high) — how much time and resources does it need?',
      'Plot on a 2x2 matrix: Quick Wins (high impact, low effort), Big Bets (high impact, high effort), Fill-Ins (low impact, low effort), Money Pits (low impact, high effort)',
      'Prioritize Quick Wins first, then evaluate Big Bets against strategic goals',
    ],
    when_to_use: 'Use in roadmap planning or backlog grooming when you need a visual, team-friendly way to compare options and build consensus.',
    domain: 'prioritization',
  },
  {
    id: 'fw-double-diamond',
    name: 'Double Diamond',
    purpose: 'A design process framework with four phases that alternate between divergent and convergent thinking to move from problem to solution.',
    steps: [
      'Discover — diverge: research broadly to understand the problem space (user interviews, data analysis, observation)',
      'Define — converge: synthesize findings into a clear problem statement or "How might we" question',
      'Develop — diverge: ideate and prototype multiple potential solutions',
      'Deliver — converge: test, refine, and ship the strongest solution',
    ],
    when_to_use: 'Use when tackling ambiguous problems where you need to ensure the team explores the problem deeply before jumping to solutions.',
    domain: 'user-research',
  },
]
