/* ─── Product 75 vocabulary ──────────────────────────────────── */

export type P75Domain =
  | "Metrics"
  | "Growth"
  | "Payments"
  | "Engagement"
  | "Retention"
  | "Monetization"
  | "Research"
  | "Strategy"
  | "Execution";

export interface P75Card {
  id: string;
  term: string;
  definition: string;          // 1 line
  lumaNote: string;            // 2–3 sentences practical context
  domain: P75Domain;
  example: string;             // example usage in a sentence
}

export const PRODUCT_75: P75Card[] = [
  /* ── Metrics ── */
  {
    id: "p75-01",
    term: "North Star Metric",
    definition: "The single metric that best captures the core value your product delivers to customers.",
    lumaNote: "Every PM battle eventually comes back to this. If your team can't agree on the north star, your roadmap will drift. It needs to be leading (predictive of revenue), not lagging (revenue itself). Airbnb's is nights booked, not revenue.",
    domain: "Metrics",
    example: "When our north star metric stalled for three weeks, it surfaced a retention problem we'd been papering over with new user growth.",
  },
  {
    id: "p75-02",
    term: "DAU / MAU Ratio",
    definition: "Daily active users divided by monthly active users — a measure of engagement stickiness.",
    lumaNote: "A DAU/MAU of 50%+ signals habitual usage (WhatsApp, Slack). Below 20% means users value the product but don't need it daily. The ratio tells you if you're building a utility or a daily ritual. Don't optimize for the wrong one.",
    domain: "Metrics",
    example: "Our DAU/MAU ratio dropped from 42% to 31% after we removed the daily digest email — users were only opening the app when pushed.",
  },
  {
    id: "p75-03",
    term: "LTV (Lifetime Value)",
    definition: "The total revenue a business expects to earn from a single customer over the entire relationship.",
    lumaNote: "LTV without CAC is meaningless. The ratio that matters is LTV:CAC — SaaS targets 3:1 minimum. LTV is also a prediction, not a measurement, so the assumptions inside the model matter as much as the number.",
    domain: "Metrics",
    example: "Once we segmented LTV by acquisition channel, we found that organic search customers had 2.4× the LTV of paid social customers.",
  },
  {
    id: "p75-04",
    term: "CAC (Customer Acquisition Cost)",
    definition: "The total cost to acquire one new customer, including sales, marketing, and overhead.",
    lumaNote: "CAC payback period — how many months of revenue to recover CAC — is often more useful than CAC alone. A 12-month payback is fine for enterprise; it's fatal for consumer. Always clarify which cost buckets are included.",
    domain: "Growth",
    example: "After attributing customer success time to CAC, our enterprise CAC jumped from $1,200 to $3,400 — changing the viability of our SMB strategy entirely.",
  },
  {
    id: "p75-05",
    term: "Activation Rate",
    definition: "The percentage of new users who complete the action that predicts long-term retention.",
    lumaNote: "Activation is the most commonly misidentified metric in product. The activation event isn't 'signed up' — it's the first moment users get real value. For Slack it's 2,000 messages sent. You find it by running a cohort analysis against retention.",
    domain: "Engagement",
    example: "We discovered our activation event was 'created first saved search,' not 'invited a teammate' — which restructured our entire onboarding sequence.",
  },
  {
    id: "p75-06",
    term: "Churn Rate",
    definition: "The percentage of customers who cancel or don't renew within a given time period.",
    lumaNote: "Monthly churn of 2% sounds fine until you compound it: that's 22% annual churn. B2B SaaS targets under 5% annually. Voluntary vs. involuntary churn (payment failures) require completely different interventions — always decompose before diagnosing.",
    domain: "Retention",
    example: "When we segmented churn by plan tier, enterprise churn was 1.2% annually while SMB churn was 28% — entirely different product-market fit problems.",
  },
  {
    id: "p75-07",
    term: "NPS (Net Promoter Score)",
    definition: "A metric measuring customer loyalty: % Promoters (9–10) minus % Detractors (0–6).",
    lumaNote: "NPS is a lagging indicator and a cultural metric, not an operational one. The follow-up question — 'why?' — is where the product signal lives. An NPS of 45 that's trending down is more alarming than a static 30.",
    domain: "Metrics",
    example: "Our NPS stayed flat at 38 for two quarters, but the verbatims shifted from 'missing features' to 'reliability issues' — a signal we'd have missed without reading the text.",
  },
  {
    id: "p75-08",
    term: "ARPU (Average Revenue Per User)",
    definition: "Total revenue divided by the number of active users in a given period.",
    lumaNote: "ARPU tells you monetization efficiency. Falling ARPU with growing user count usually means your new users are lower quality or on lower-tier plans — a mix-shift problem. Segment by cohort to see if monetization is actually degrading.",
    domain: "Monetization",
    example: "Our ARPU declined 18% despite raising prices, because free-plan usage grew 3× faster than paid — a mix-shift problem hiding in the aggregate.",
  },
  {
    id: "p75-09",
    term: "Conversion Rate",
    definition: "The percentage of users who complete a desired action (sign-up, purchase, upgrade).",
    lumaNote: "Conversion rate without funnel decomposition is almost useless. A 3% conversion rate is the output of a hundred micro-decisions: landing page, onboarding flow, pricing page, checkout. Each step has its own conversion rate that tells you where to focus.",
    domain: "Growth",
    example: "Our trial-to-paid conversion rate was 8%, but free-to-trial was 1.2% — the real problem was top-of-funnel, not the checkout experience.",
  },
  {
    id: "p75-10",
    term: "Retention Curve",
    definition: "A graph showing what percentage of users from a cohort remain active at each time period after acquisition.",
    lumaNote: "The shape of the retention curve matters more than any single retention rate. A curve that flattens (becomes horizontal) means you have a retained core. One that keeps declining means even your best users leave eventually — a fundamental product-market fit problem.",
    domain: "Retention",
    example: "After our redesign, the D30 retention curve flattened at 34% instead of continuing its previous descent to 12% — evidence we'd found a real retained core.",
  },
  /* ── Growth ── */
  {
    id: "p75-11",
    term: "Viral Coefficient (K-factor)",
    definition: "The average number of new users each existing user generates, directly through referrals.",
    lumaNote: "K > 1 means the product grows without any paid acquisition. K = 0.5 means paid acquisition grows the base but word-of-mouth accelerates it. Most products have K < 1; the metric matters most when combined with cycle time (how fast the loop runs).",
    domain: "Growth",
    example: "Our K-factor was 0.7 with a 4-day cycle time — meaning each cohort amplified marketing spend by 40% before organic growth plateaued.",
  },
  {
    id: "p75-12",
    term: "Payback Period",
    definition: "The time required to recover the cost of acquiring a customer through their generated revenue.",
    lumaNote: "The shorter the payback period, the less capital the business needs to grow. Consumer startups often target 3–6 months; enterprise can tolerate 18–24 months because of lower churn. During downturns, investors scrutinize payback period much more than LTV.",
    domain: "Growth",
    example: "By shifting our acquisition mix from paid social to SEO, we reduced payback period from 16 months to 9 months with the same CAC.",
  },
  {
    id: "p75-13",
    term: "Product-Led Growth (PLG)",
    definition: "A go-to-market strategy where the product itself drives acquisition, conversion, and expansion.",
    lumaNote: "PLG requires a fundamentally different product design: the free experience must be valuable enough to create habit, and the upgrade trigger must occur organically at the moment of maximum value recognition. It fails when free is too generous or too limited.",
    domain: "Growth",
    example: "We shifted to a PLG motion by letting teams collaborate for free on up to 3 projects, creating natural upgrade triggers when teams exceeded the limit.",
  },
  {
    id: "p75-14",
    term: "Top-of-Funnel (ToFu)",
    definition: "The awareness and acquisition stage of the marketing/product funnel — highest volume, lowest intent.",
    lumaNote: "ToFu optimization is often where engineering time is wasted. Before optimizing landing pages, verify that the traffic is the right traffic. High-volume, low-quality ToFu produces a leaky funnel that no conversion rate optimization can fix.",
    domain: "Growth",
    example: "We tripled our ToFu traffic through SEO but conversion rate fell from 4% to 1.2% — the new visitors weren't our target persona.",
  },
  {
    id: "p75-15",
    term: "Cohort Analysis",
    definition: "Grouping users by a shared characteristic (usually acquisition date) and tracking their behavior over time.",
    lumaNote: "Cohort analysis is the anti-averaging tool. Aggregate metrics hide cohort degradation — a product can show flat retention while every new cohort is actually worse than the last. Always run retention curves by acquisition cohort before drawing conclusions.",
    domain: "Metrics",
    example: "Cohort analysis revealed that users acquired via paid social had 40% lower D90 retention than organic users — invisible in our aggregate dashboard.",
  },
  /* ── Engagement ── */
  {
    id: "p75-16",
    term: "Session Depth",
    definition: "The number of actions or pages a user engages with during a single session.",
    lumaNote: "Session depth is a proxy for intent signal, not engagement quality. A user who reads 8 articles may be less engaged than one who reads 2 and saves them. Always combine session depth with action quality to assess real engagement.",
    domain: "Engagement",
    example: "Our session depth increased 35% after we added infinite scroll, but saves and shares dropped — users were browsing more but caring less.",
  },
  {
    id: "p75-17",
    term: "Time to Value (TTV)",
    definition: "How long it takes a new user to experience the core value proposition of a product.",
    lumaNote: "TTV is the hidden driver of activation rate. The shorter your TTV, the higher your activation — but shortening it requires ruthless onboarding design, not feature addition. Adding setup steps always increases TTV even if they add 'value.'",
    domain: "Engagement",
    example: "We cut TTV from 6 days to 18 hours by letting users import existing data instead of entering it manually, which doubled our week-1 retention.",
  },
  {
    id: "p75-18",
    term: "Feature Adoption Rate",
    definition: "The percentage of active users who use a specific feature within a defined time window.",
    lumaNote: "Low feature adoption means one of three things: users don't know it exists, they don't understand what it does, or they don't need it. Don't build discoverability solutions until you've diagnosed which failure mode you're solving.",
    domain: "Engagement",
    example: "Our collaboration feature had 8% adoption despite prominent placement — user interviews revealed most users didn't have teammates to collaborate with.",
  },
  {
    id: "p75-19",
    term: "Habit Loop",
    definition: "The cue → routine → reward cycle that drives repeated behavior toward a product.",
    lumaNote: "B.J. Fogg and Nir Eyal popularized different models but the core is the same: a product becomes a habit when the trigger is immediate, the action is easy, and the reward is variable. Social products exploit all three. Utility products usually rely on external triggers.",
    domain: "Engagement",
    example: "We introduced a daily digest notification as the external trigger, reducing our reliance on users generating their own cue to return.",
  },
  {
    id: "p75-20",
    term: "Engagement Score",
    definition: "A composite metric that weights multiple user actions to produce a single engagement signal.",
    lumaNote: "Engagement scores are useful for segmentation and prediction but dangerous as targets. When a team optimizes for engagement score, they optimize for whatever actions were weighted — often leading to dark patterns. Validate the score against retention outcomes before relying on it.",
    domain: "Engagement",
    example: "We found that users with engagement score > 70 in the first week had 4× the 90-day retention — making it a reliable leading indicator for customer success to prioritize.",
  },
  /* ── Retention ── */
  {
    id: "p75-21",
    term: "Day-N Retention",
    definition: "The percentage of users who return to a product exactly N days after their first session.",
    lumaNote: "D1, D7, D30 are the canonical checkpoints. D1 measures whether the first experience was compelling enough to prompt a second visit. D30 measures whether the product is building habit. A low D1 with a high D7 usually means the activation experience is bad but word-of-mouth is salvaging it.",
    domain: "Retention",
    example: "Our D1 retention was 42% but D7 dropped to 11% — the onboarding created initial interest but didn't establish a return habit.",
  },
  {
    id: "p75-22",
    term: "Rolling Retention",
    definition: "The percentage of users from a cohort who are active on or after a specific day (not just on that exact day).",
    lumaNote: "Rolling retention is more forgiving than exact-day retention and better for products with irregular usage (e.g., weekly tools). A user who logs in on day 8 instead of day 7 counts as retained under rolling but not under classic retention.",
    domain: "Retention",
    example: "Switching from D7 to rolling-7 retention increased our visible retention rate from 18% to 31% — a meaningful distinction for our weekly-cadence product.",
  },
  {
    id: "p75-23",
    term: "Churned User",
    definition: "A previously active user who has stopped using the product, as defined by an inactivity threshold.",
    lumaNote: "The churn definition threshold is a product decision that has huge implications for your reported metrics. A 30-day inactivity threshold and a 90-day threshold will produce very different churn rates from identical user behavior. Set the threshold based on your natural usage cadence.",
    domain: "Retention",
    example: "When we moved our churn definition from 30-day to 60-day inactivity, our MAU jumped 22% — without a single change to the product.",
  },
  {
    id: "p75-24",
    term: "Resurrection Rate",
    definition: "The percentage of previously churned users who return and become active again.",
    lumaNote: "Resurrection campaigns are often underinvested relative to acquisition. Resurrected users have already gone through onboarding — their re-activation cost is much lower than new user acquisition. Win-back email sequences, triggered by product updates relevant to their past behavior, are the most effective lever.",
    domain: "Retention",
    example: "A targeted win-back campaign to churned users who had used our collaboration feature generated a 12% resurrection rate — at one-fifth the CAC of new acquisition.",
  },
  {
    id: "p75-25",
    term: "Leading vs. Lagging Indicator",
    definition: "Leading indicators predict future outcomes; lagging indicators measure outcomes that have already occurred.",
    lumaNote: "This distinction is critical for product decision-making. Revenue is a lagging indicator — by the time it changes, the cause happened weeks or months earlier. Activation rate and feature adoption are leading indicators of revenue. PMs who only watch revenue are always reacting.",
    domain: "Metrics",
    example: "We identified invite-sent-in-first-week as our leading indicator for 90-day retention, giving us a 3-week window to intervene before churn materialized.",
  },
  /* ── Monetization ── */
  {
    id: "p75-26",
    term: "Freemium Model",
    definition: "A pricing model where basic features are free and users pay for premium features or capacity.",
    lumaNote: "Freemium only works when the free tier creates genuine value AND a natural limit the user will eventually hit. If the free tier is too good, no one upgrades. If it's too limited, users leave instead of paying. Finding this balance is primarily a product problem, not a pricing problem.",
    domain: "Monetization",
    example: "We expanded the free tier to include 3 projects instead of 1, which increased free activation by 60% and ultimately improved paid conversion because more users reached the collaboration limit.",
  },
  {
    id: "p75-27",
    term: "Expansion Revenue",
    definition: "Additional revenue generated from existing customers through upsells, seat additions, or usage growth.",
    lumaNote: "Expansion revenue is the secret to efficient SaaS growth — when expansion revenue exceeds churn, Net Revenue Retention exceeds 100% and the business grows even with no new customers. This is called 'negative churn' and it's the holy grail of B2B SaaS.",
    domain: "Monetization",
    example: "Our NRR crossed 112% when enterprise customers started adding seats faster than SMB accounts churned — effectively funding growth without new sales.",
  },
  {
    id: "p75-28",
    term: "Net Revenue Retention (NRR)",
    definition: "Revenue retained from existing customers after accounting for churn, contraction, and expansion.",
    lumaNote: "NRR > 100% means existing customers are worth more each year than they were the year before. Top-tier SaaS companies (Snowflake, Datadog) have NRR of 120–140%. It's the single most important indicator of product-market fit in B2B SaaS.",
    domain: "Monetization",
    example: "Our NRR fell from 108% to 94% not because customers left, but because budget freezes stopped expansion — a signal that our upgrade triggers were too passive.",
  },
  {
    id: "p75-29",
    term: "Price Elasticity",
    definition: "The sensitivity of demand to changes in price — how much purchase volume changes when price changes.",
    lumaNote: "High price elasticity means users abandon the product when prices rise. Low elasticity means you have pricing power. B2B products with deep workflow integration tend to have low elasticity; consumer products with substitutes tend to have high elasticity.",
    domain: "Monetization",
    example: "When we raised enterprise prices 25%, churn didn't move — low price elasticity confirmed we'd been significantly underpriced for our segment.",
  },
  {
    id: "p75-30",
    term: "Willingness to Pay (WTP)",
    definition: "The maximum price a user or customer is willing to pay for a product or feature.",
    lumaNote: "WTP is measured, not assumed. The Van Westendorp pricing model (4-question survey) and conjoint analysis are the most common methods. Self-reported WTP is inflated; observed behavior in A/B price tests is the gold standard.",
    domain: "Monetization",
    example: "Our stated WTP in surveys was $49/month, but A/B testing at $39 vs. $49 showed no difference in conversion — we'd been leaving money on the table.",
  },
  /* ── Payments ── */
  {
    id: "p75-31",
    term: "Failed Payment Rate",
    definition: "The percentage of attempted renewal charges that are declined by the payment processor.",
    lumaNote: "Industry average for subscription businesses is 3–4%. Above 6% signals a systemic issue — either customer quality (too many debit cards, prepaid cards) or a recovery flow problem. Decompose by decline reason code before designing interventions.",
    domain: "Payments",
    example: "Our 8.3% failed payment rate dropped to 4.1% after we added intelligent retry logic aligned with customer payday cycles.",
  },
  {
    id: "p75-32",
    term: "Involuntary Churn",
    definition: "Customer loss caused by payment failures rather than deliberate cancellation decisions.",
    lumaNote: "Involuntary churn is recoverable — these customers intended to stay. A grace period, smart retry logic, and proactive card-expiry outreach can recover 30–50% of involuntary churners at a fraction of acquisition cost. Most teams under-invest here.",
    domain: "Payments",
    example: "We recovered 41% of involuntary churners with a 7-day grace period and payday-aligned retries — adding $180K ARR without acquiring a single new customer.",
  },
  {
    id: "p75-33",
    term: "Dunning",
    definition: "The process of communicating with customers to collect overdue payments, typically via automated email sequences.",
    lumaNote: "Dunning sequence design is a product problem, not just an ops problem. Tone, timing, subject lines, and the call-to-action all affect recovery rate. The highest-converting dunning emails are empathetic (not threatening) and provide a direct, low-friction link to update payment details.",
    domain: "Payments",
    example: "Rewriting our dunning sequence with empathetic copy and a one-click payment update link increased recovery rate from 31% to 49%.",
  },
  {
    id: "p75-34",
    term: "Payment Method Mix",
    definition: "The distribution of payment instruments (credit card, debit card, ACH, digital wallet) used by customers.",
    lumaNote: "Payment method mix is a silent driver of failed payment rate. Debit cards and prepaid cards have significantly higher decline rates than credit cards. If your customer base skews toward lower-income segments, you'll see higher involuntary churn regardless of your retry logic.",
    domain: "Payments",
    example: "After we added ACH as a payment option for annual plans, enterprise churn from payment failures dropped by 60% — ACH declines are extremely rare compared to card declines.",
  },
  {
    id: "p75-35",
    term: "Authorization Rate",
    definition: "The percentage of payment authorization requests that are approved by the issuing bank.",
    lumaNote: "Authorization rate is highly controllable through engineering and payment processor optimization. Smart retry logic, card account updater services, and network tokenization can meaningfully improve authorization rates. A 1% lift in authorization rate on large GMV is significant revenue.",
    domain: "Payments",
    example: "Implementing network tokenization increased our authorization rate from 91% to 96% — recovering approximately $340K in monthly GMV that had been silently leaking.",
  },
  /* ── Research ── */
  {
    id: "p75-36",
    term: "Jobs to Be Done (JTBD)",
    definition: "A framework for understanding what goal a customer is trying to accomplish when they 'hire' a product.",
    lumaNote: "JTBD reframes the question from 'who is the user?' to 'what job is the user trying to get done?' The canonical example: people don't buy a drill, they buy a hole in the wall. The real job is often one level more abstract than the surface-level task.",
    domain: "Research",
    example: "Our JTBD research revealed users weren't hiring our analytics tool to understand data — they were hiring it to convince stakeholders, which completely changed our visualization priorities.",
  },
  {
    id: "p75-37",
    term: "User Persona",
    definition: "A semi-fictional representation of a key user segment, based on research about real users' goals and behaviors.",
    lumaNote: "Personas are useful for alignment, not for research. The mistake is treating persona creation as a research output when it's a communication tool. Personas created without real user research are 'assumption documents' that can do more harm than having no persona at all.",
    domain: "Research",
    example: "Our 'data analyst' persona was so broad it covered both SQL experts and Excel users — opposite needs that produced contradictory product decisions for 18 months.",
  },
  {
    id: "p75-38",
    term: "Problem Interview",
    definition: "A structured user interview focused on understanding existing pain points, not validating a specific solution.",
    lumaNote: "The hardest discipline in problem interviews is not pitching. The moment you describe your solution, users tell you what you want to hear. The goal is to understand the user's world before a specific solution exists — which requires neutral, open-ended questions about past behavior.",
    domain: "Research",
    example: "In 12 problem interviews, not one user mentioned the feature we were planning to build — they were all worried about a data quality problem we'd deprioritized.",
  },
  {
    id: "p75-39",
    term: "Desirability vs. Feasibility vs. Viability",
    definition: "The three lenses of product validation: do users want it, can we build it, does it make business sense.",
    lumaNote: "Most product failures can be traced to overweighting one dimension. Technically feasible products that no one wants. Desirable products that are financially unsustainable. All three must be true simultaneously for a product to succeed, and each requires different validation methods.",
    domain: "Research",
    example: "Our feature scored high on feasibility and viability but low on desirability — we'd solved a problem users didn't care enough about to change their behavior for.",
  },
  {
    id: "p75-40",
    term: "Survey Bias",
    definition: "Systematic distortions in survey responses caused by question design, sampling, or social desirability effects.",
    lumaNote: "The most common survey biases in product work: acquiescence bias (users say 'yes' to please you), social desirability bias (users answer as they wish they behaved), and leading questions (the question implies the correct answer). Always test behavioral intent against actual behavior.",
    domain: "Research",
    example: "Our survey showed 78% of users would pay for the premium tier, but A/B testing the actual paywall revealed a 4% conversion rate — a 20× gap driven by survey bias.",
  },
  /* ── Strategy ── */
  {
    id: "p75-41",
    term: "Opportunity Solution Tree",
    definition: "A visual framework (Teresa Torres) mapping product outcomes → opportunities → solutions → experiments.",
    lumaNote: "The OST prevents the most common product mistake: jumping from a goal directly to a solution. It forces you to identify the opportunity (customer problem) between the outcome and the solution, and to think in parallel solutions before committing to one.",
    domain: "Strategy",
    example: "Building our OST revealed we had 11 solutions mapped to only 2 opportunities — we were over-engineering problems that weren't the biggest levers for our outcome.",
  },
  {
    id: "p75-42",
    term: "Product-Market Fit (PMF)",
    definition: "The degree to which a product satisfies a strong market demand — the point where growth becomes pull-based.",
    lumaNote: "Marc Andreessen's original definition is qualitative — 'you can feel it.' Sean Ellis's 40% rule is operational: if 40%+ of users say they'd be 'very disappointed' without your product, you have PMF. Both are useful; neither is sufficient alone. Retention curve flattening is the most objective signal.",
    domain: "Strategy",
    example: "We knew we'd hit PMF when our support queue flipped from bug reports to feature requests — users had stopped fighting the product and started depending on it.",
  },
  {
    id: "p75-43",
    term: "Minimum Viable Product (MVP)",
    definition: "The smallest version of a product that delivers enough value to attract early adopters and generate learning.",
    lumaNote: "MVP is widely misunderstood as 'minimum quality.' The MVP isn't the smallest thing you can build — it's the smallest thing that tests your riskiest assumption. If your riskiest assumption is 'users will pay,' your MVP must include payment. A landing page is only an MVP for the assumption 'users will sign up.'",
    domain: "Strategy",
    example: "Our first MVP was a Notion template we sent to 20 users — it tested the workflow assumption without writing a line of code.",
  },
  {
    id: "p75-44",
    term: "Moat",
    definition: "A durable competitive advantage that protects a business from competition over time.",
    lumaNote: "Product moats come in four types: network effects (value grows with users), switching costs (painful to leave), proprietary data (unique insights from usage), and scale economics (cheaper to serve at size). Features are not moats — they can be copied. Understanding your moat shapes product strategy for years.",
    domain: "Strategy",
    example: "Our real moat wasn't the algorithm — it was the proprietary dataset generated by 3 years of user behavior that no competitor could replicate quickly.",
  },
  {
    id: "p75-45",
    term: "Network Effect",
    definition: "A product becomes more valuable as more people use it — each new user increases value for all existing users.",
    lumaNote: "Network effects are often claimed but rarely real. True network effects require that the product is meaningfully better for user A when user B joins. Marketplace network effects (more buyers → better for sellers) are the most powerful. Communication network effects (Slack, WhatsApp) are the most durable.",
    domain: "Strategy",
    example: "Our network effect only kicked in at team size 5+ — below that, users saw no benefit from others joining, which meant our viral loop was broken for small teams.",
  },
  /* ── Execution ── */
  {
    id: "p75-46",
    term: "OKRs (Objectives and Key Results)",
    definition: "A goal-setting framework: an ambitious objective paired with measurable key results that define success.",
    lumaNote: "The most common OKR failure is treating key results as output metrics (shipped the feature) instead of outcome metrics (40% of users use the feature weekly). Key results should describe the world you want to exist, not the work you plan to do.",
    domain: "Execution",
    example: "Our OKR moved from 'Ship collaboration v2' to 'Increase team adoption rate from 22% to 45%' — which produced a completely different sprint backlog.",
  },
  {
    id: "p75-47",
    term: "Opportunity Sizing",
    definition: "Estimating the potential business value of addressing a specific user problem or market segment.",
    lumaNote: "Opportunity sizing is a prioritization input, not a business plan. The goal is directional accuracy — is this a $1M opportunity or a $10M opportunity — not precision. Use top-down (TAM × share) and bottom-up (unit × volume) estimates and triangulate. If they disagree by 10×, revisit your assumptions.",
    domain: "Execution",
    example: "Bottom-up sizing put the enterprise segment at $2.4M ARR; top-down put it at $18M — the gap pointed to a key assumption about enterprise deal size we needed to validate.",
  },
  {
    id: "p75-48",
    term: "RICE Framework",
    definition: "A prioritization model scoring features by Reach × Impact × Confidence ÷ Effort.",
    lumaNote: "RICE is most useful for making tradeoffs explicit and visible, not for producing a definitive answer. The confidence score is often underweighted — ideas with high reach/impact but low confidence often dominate lists and then underperform. Interrogate the assumptions behind the score.",
    domain: "Execution",
    example: "Our RICE scores consistently put foundational reliability work last because reach was low, until we added customer retention impact to the 'impact' definition.",
  },
  {
    id: "p75-49",
    term: "Dogfooding",
    definition: "The practice of using your own product internally before shipping it to customers.",
    lumaNote: "Dogfooding is most useful for catching usability and reliability issues, not for validating whether the product solves the right problem. Your team's context is too different from your users' context for dogfooding to replace user research. It's a quality check, not a research method.",
    domain: "Execution",
    example: "Dogfooding our mobile app before launch caught 3 friction points the QA team had missed, but it didn't surface the core workflow mismatch that caused low adoption.",
  },
  {
    id: "p75-50",
    term: "A/B Test",
    definition: "A controlled experiment comparing two variants (A and B) to determine which produces a better outcome.",
    lumaNote: "The most common A/B testing mistake is ending tests too early. Statistical significance requires a predetermined sample size calculated before the experiment starts, based on expected effect size and desired power. Peeking at results and stopping when 'significant' produces a 30%+ false positive rate.",
    domain: "Execution",
    example: "We ran our pricing A/B test to 2,000 users per variant over 4 weeks — not until 'significant,' which would have produced a false result at day 6.",
  },
  /* ── More Metrics ── */
  {
    id: "p75-51",
    term: "Guardrail Metric",
    definition: "A metric that must not degrade during an experiment, even if the primary metric improves.",
    lumaNote: "Guardrail metrics are the immune system of your experimentation program. Without them, optimization on one dimension silently degrades another. A common pattern: optimizing for engagement increases notification sends, which increases unsubscribes. The guardrail on unsubscribe rate catches this.",
    domain: "Metrics",
    example: "Our primary metric (upgrade rate) improved 12%, but our guardrail metric (D30 retention) dropped 8% — the 'upgrade' was mostly users converting before they understood the product, then churning.",
  },
  {
    id: "p75-52",
    term: "Funnel Analysis",
    definition: "Measuring conversion at each step of a multi-stage user journey to identify where users drop off.",
    lumaNote: "Funnel analysis tells you where people leave — it doesn't tell you why. The analysis gives you the address of the problem; user research gives you the cause. Build the funnel first, identify the biggest drop-off point, then investigate the reason before designing a solution.",
    domain: "Metrics",
    example: "Our funnel showed a 72% drop-off at the payment step — turned out users needed to create an account before seeing pricing, which they discovered for the first time at checkout.",
  },
  {
    id: "p75-53",
    term: "Marginal Revenue",
    definition: "The additional revenue generated by producing or serving one additional unit or customer.",
    lumaNote: "In SaaS, marginal revenue from an additional seat or user is nearly zero — but marginal cost isn't. Customer success, support, and infrastructure costs scale with users. Understanding marginal economics shapes packaging decisions: unlimited seat pricing vs. per-seat pricing.",
    domain: "Monetization",
    example: "Our marginal cost analysis showed enterprise accounts became profitable after month 3 regardless of seat count — justifying unlimited seat pricing for annual deals.",
  },
  {
    id: "p75-54",
    term: "Power User",
    definition: "A user who engages with a product at significantly higher frequency and depth than the average user.",
    lumaNote: "Power users are your best signal for what the product is capable of and your worst signal for what average users need. Optimizing for power users often produces a product that's too complex for mainstream adoption. Use power users to discover what's possible; use average users to decide what to prioritize.",
    domain: "Engagement",
    example: "Our power users loved keyboard shortcuts, but interview data showed 80% of users didn't know they existed — we needed better discoverability before adding more shortcuts.",
  },
  {
    id: "p75-55",
    term: "Segmentation",
    definition: "Dividing a user base or market into groups with shared characteristics, behaviors, or needs.",
    lumaNote: "Segmentation is the antidote to averaging. Almost every aggregate product metric is the weighted average of several very different user groups with very different behaviors. The moment you segment, the product strategy becomes clearer — because different segments need different solutions.",
    domain: "Strategy",
    example: "Segmenting by company size revealed that SMB users churned at 28% annually while enterprise churned at 3% — two different products masquerading as one.",
  },
  {
    id: "p75-56",
    term: "Signal vs. Noise",
    definition: "Distinguishing meaningful information (signal) from random variation or irrelevant data (noise).",
    lumaNote: "The most dangerous noise in product work is a metric that moved. A 2% change in a metric on Tuesday is almost always noise. A 2% sustained change over 3 weeks following a specific intervention is signal. Always ask: is this change large enough, sustained enough, and correlated with something real enough to act on?",
    domain: "Metrics",
    example: "We chased a one-day 15% spike in signups for a week before realizing it was caused by a single tweet from a micro-influencer — noise, not a repeatable channel.",
  },
  {
    id: "p75-57",
    term: "Vanity Metric",
    definition: "A metric that looks impressive but doesn't correlate with business outcomes or actionable decisions.",
    lumaNote: "Total registered users, total downloads, and social media followers are the canonical vanity metrics. They trend up almost regardless of what you do. The test: if the metric went down, would you know what to change? If not, it's vanity. If yes, it might be actionable.",
    domain: "Metrics",
    example: "We celebrated 100K total signups while DAU was 1,200 — the vanity metric had been masking the retention problem for months.",
  },
  {
    id: "p75-58",
    term: "Pirate Metrics (AARRR)",
    definition: "Dave McClure's framework: Acquisition, Activation, Retention, Revenue, Referral.",
    lumaNote: "AARRR is a checklist, not a framework. Its real value is forcing teams to think across the full funnel instead of fixating on one stage. The most commonly neglected stage is Activation — teams focus on Acquisition and Revenue and wonder why growth doesn't compound.",
    domain: "Growth",
    example: "Our AARRR audit showed we had strong Acquisition and Revenue metrics but Activation at 12% — every dollar of paid acquisition was leaking through a broken activation experience.",
  },
  {
    id: "p75-59",
    term: "Qualitative vs. Quantitative Research",
    definition: "Qualitative research explores why users behave a certain way; quantitative measures how many do.",
    lumaNote: "Quantitative data tells you what is happening; qualitative tells you why. The canonical workflow: use quant to find the anomaly (retention drops at D7), use qual to explain it (users hit a complexity wall in week 2). Teams that skip qual build a lot of solutions to the wrong problem.",
    domain: "Research",
    example: "Quantitative data showed a 60% drop-off at step 4 of onboarding; qualitative interviews revealed users didn't understand why step 4 was necessary — a framing problem, not a UX problem.",
  },
  {
    id: "p75-60",
    term: "Feature Flag",
    definition: "A software mechanism that allows features to be enabled or disabled for specific users without a code deploy.",
    lumaNote: "Feature flags are a product tool, not just an engineering tool. They enable percentage rollouts, targeted experiments, and instant rollbacks — without requiring a hotfix. The discipline is keeping the flag registry clean: stale flags that never get cleaned up become technical debt that blocks future experiments.",
    domain: "Execution",
    example: "We used feature flags to roll out the new dashboard to 5% of users first, catching a performance regression before it affected the full user base.",
  },
  {
    id: "p75-61",
    term: "Regression Testing",
    definition: "Testing that verifies that new code changes haven't broken existing functionality.",
    lumaNote: "Regressions in product metrics are as important as code regressions. After any significant release, run a 'metric regression check' — verify that none of your guardrail or core metrics moved in the wrong direction. Many product teams discover they shipped a retention regression 4 weeks after the release.",
    domain: "Execution",
    example: "Our post-launch metric regression check caught a 14% increase in session abandonment 3 days after shipping — which we traced to a new loading state that had no error handling.",
  },
  {
    id: "p75-62",
    term: "TAM / SAM / SOM",
    definition: "Total Addressable Market / Serviceable Addressable Market / Serviceable Obtainable Market — market sizing tiers.",
    lumaNote: "TAM is the ceiling of ambition; SOM is what matters for your next 3 years. The mistake is citing TAM in product prioritization decisions — it's a fundraising metric, not a planning metric. Use SAM to evaluate whether a segment is worth building for, and SOM to set realistic near-term goals.",
    domain: "Strategy",
    example: "Our TAM was $4B, but our SAM was $180M (mid-market US companies) and our SOM for year 3 was $12M — which produced a very different product strategy than chasing the full TAM.",
  },
  {
    id: "p75-63",
    term: "Competitive Moat Analysis",
    definition: "Systematic assessment of the defensibility of your product's competitive position over time.",
    lumaNote: "The common mistake is evaluating your moat based on where you are today, not where your competitors will be in 18 months. A feature advantage is not a moat. A moat must be something that gets stronger as you grow — network effects, data advantages, and switching costs all compound. Features don't.",
    domain: "Strategy",
    example: "Our 'moat' was a better algorithm — which a competitor replicated in 6 months. The real moat we should have been building was the proprietary training data our users were generating.",
  },
  {
    id: "p75-64",
    term: "User Story",
    definition: "A short description of a feature from the user's perspective: 'As a [user], I want to [action] so that [outcome].'",
    lumaNote: "The 'so that' clause is the part most teams write weakly or omit entirely. It forces you to articulate the user's actual goal — not just the action. A story without a clear 'so that' is a feature request, not a user need.",
    domain: "Execution",
    example: "'As a data analyst, I want to export filtered results to CSV so that I can share findings with stakeholders who don't have product access' — the 'so that' revealed we should also consider a shareable link feature.",
  },
  {
    id: "p75-65",
    term: "Acceptance Criteria",
    definition: "The specific conditions that must be met for a user story or feature to be considered complete.",
    lumaNote: "Acceptance criteria are a communication contract between product and engineering. Vague criteria ('the feature should feel fast') produce disagreement at launch. Specific criteria ('page load < 2 seconds for 95th percentile users on 4G') produce shared definition of done and fewer regressions.",
    domain: "Execution",
    example: "When we formalized acceptance criteria to include performance benchmarks, the number of 'done but not done' arguments at sprint review dropped by 80%.",
  },
  {
    id: "p75-66",
    term: "Technical Debt",
    definition: "The accumulated cost of shortcuts taken during development that must eventually be addressed to maintain velocity.",
    lumaNote: "Technical debt is a product problem, not just an engineering problem. Debt slows feature development, increases bug rate, and raises the risk of critical outages — all of which have direct product impact. PMs who treat debt as 'eng's problem' consistently underinvest in it and then wonder why velocity slows over time.",
    domain: "Execution",
    example: "We deferred our API redesign for 3 quarters to ship features, and it cost us 6 weeks of velocity to fix the architectural problem it created — a negative return on the shortcut.",
  },
  {
    id: "p75-67",
    term: "Sprint Review",
    definition: "A meeting at the end of a sprint where the team demonstrates completed work to stakeholders.",
    lumaNote: "Sprint reviews are most valuable when they focus on outcomes, not output. Demonstrating features is fine; demonstrating whether those features moved the metric is better. Teams that use sprint reviews to show working software without discussing impact are running theater, not product development.",
    domain: "Execution",
    example: "We restructured sprint review to start with the metric we were trying to move, then show what we shipped, then show what happened to the metric — which changed the quality of stakeholder feedback entirely.",
  },
  {
    id: "p75-68",
    term: "Hypothesis-Driven Development",
    definition: "Building features as testable hypotheses with defined success criteria before development begins.",
    lumaNote: "The hypothesis statement format matters: 'We believe that [change] will result in [outcome] for [user segment], which we will measure by [metric].' The rigor is in the measurability — if you can't define the measurement before building, you're not doing hypothesis-driven development.",
    domain: "Execution",
    example: "Instead of 'build a better onboarding,' we wrote: 'We believe that reducing setup steps from 7 to 3 will increase D7 retention by 15% for B2B users, measured by our activation cohort.' This produced a completely different scope.",
  },
  {
    id: "p75-69",
    term: "Decision Log",
    definition: "A record of significant product decisions, the context in which they were made, and the reasoning behind them.",
    lumaNote: "Decision logs solve two problems: they prevent re-litigating decisions when team composition changes, and they enable retrospective analysis of which decisions correlated with outcomes. The format that works: decision made, options considered, key constraint, owner, date. Takes 5 minutes to write; saves hours later.",
    domain: "Execution",
    example: "When a new VP questioned a pricing decision 8 months after it was made, we shared the decision log — which ended a 2-hour meeting in 10 minutes.",
  },
  {
    id: "p75-70",
    term: "Counterfactual Thinking",
    definition: "Evaluating what would have happened if a different decision had been made — used to assess causal impact.",
    lumaNote: "Counterfactuals are the core of experiment design. An A/B test is a controlled counterfactual: 'what would have happened to this user if they'd seen variant B instead of A?' Without a control group, you're comparing observed outcomes to an imagined baseline — which produces attribution errors.",
    domain: "Research",
    example: "Before claiming our onboarding change 'caused' the retention lift, we checked: did macro conditions change during the same period? Was there a seasonality effect? The counterfactual check confirmed the lift was real.",
  },
  {
    id: "p75-71",
    term: "Heuristic Evaluation",
    definition: "Usability assessment conducted by experts using established design principles, without user testing.",
    lumaNote: "Heuristic evaluation finds obvious usability problems cheaply and quickly. It's not a substitute for user testing — experts predict user problems but often miss the actual failure modes because their mental models don't match users'. Use heuristic evaluation to catch the most severe issues before spending user testing budget.",
    domain: "Research",
    example: "A heuristic evaluation found 8 usability issues in 90 minutes; subsequent user testing found those 8 plus 4 additional issues that experts couldn't have predicted.",
  },
  {
    id: "p75-72",
    term: "First-Party Data",
    definition: "Data collected directly from your own users through product interactions, surveys, or direct relationships.",
    lumaNote: "With third-party cookie deprecation, first-party data has become the most valuable and defensible data asset in product. Companies that invested in first-party data collection (email capture, logged-in experiences, consent-based tracking) are significantly less exposed to attribution disruption.",
    domain: "Strategy",
    example: "We shifted our analytics from third-party attribution to first-party behavioral data in logged-in sessions — losing some attribution precision but gaining much higher signal quality.",
  },
  {
    id: "p75-73",
    term: "Switching Cost",
    definition: "The effort, expense, or risk a user incurs when changing from one product to another.",
    lumaNote: "Switching costs are a moat and an acquisition problem simultaneously. High switching costs keep your existing customers but make it harder to win customers from entrenched competitors. The most durable switching costs come from data accumulation (years of history), workflow integration (deep API connections), and team training investment.",
    domain: "Strategy",
    example: "We deliberately made our data export comprehensive and easy, accepting some churn risk in exchange for faster enterprise acquisition — customers wouldn't try us if they feared lock-in.",
  },
  {
    id: "p75-74",
    term: "Iteration Velocity",
    definition: "The speed at which a product team can ship changes, measure results, and incorporate learnings.",
    lumaNote: "Iteration velocity is a product strategy choice, not just an engineering choice. Teams that invest in feature flags, automated testing, and experiment infrastructure can run 10× more experiments per quarter than teams that don't — compounding their learning rate over time. Velocity is a competitive advantage.",
    domain: "Execution",
    example: "After investing 6 weeks in our experimentation infrastructure, we went from 3 A/B tests per quarter to 18 — which compounded into significantly better product decisions over 12 months.",
  },
  {
    id: "p75-75",
    term: "Outcome vs. Output",
    definition: "Output is what you ship (features, code); outcome is the change in user behavior or business metric that results.",
    lumaNote: "This distinction is the central discipline of modern product management. Teams that optimize for output ship a lot and measure little. Teams that optimize for outcome ship less but learn more and compound faster. The hardest organizational habit to build is holding the team accountable to outcomes, not activity.",
    domain: "Strategy",
    example: "We changed our quarterly planning from 'features to ship' to 'metrics to move' — which cut our feature list by 60% but tripled the number of experiments we ran.",
  },
];

export const P75_DOMAINS: P75Domain[] = [
  "Metrics",
  "Growth",
  "Payments",
  "Engagement",
  "Retention",
  "Monetization",
  "Research",
  "Strategy",
  "Execution",
];
