export const CHALLENGES = [
  {
    id: 'pm-coinbase-003',
    title: 'Crypto Product Growth: 10x a Wallet Feature',
    scenario_role: 'Growth PM, Crypto',
    scenario_context: 'Coinbase Wallet has a "dapp browser" tab that lets users interact with decentralized apps directly from the app. Monthly active users on the tab have plateaued at 8% of wallet holders for three consecutive quarters. The growth team is exploring whether it can become a 10x growth lever.',
    scenario_trigger: 'The VP of Product asks for a structured growth plan after seeing that Phantom Wallet grew dapp engagement 4x by redesigning discovery — a pattern the team wants to understand and potentially replicate.',
    scenario_question: 'What growth strategy would 10x dapp browser engagement without burning existing wallet trust?',
    engineer_standout: 'Strong answers will distinguish between supply-side constraints (too few high-quality dapps) and demand-side constraints (discoverability, cold-start friction), and propose infrastructure-level solutions rather than surface UI tweaks.',
    paradigm: 'traditional',
    industry: 'Crypto / Web3',
    sub_vertical: 'Consumer Wallet',
    difficulty: 'advanced',
    estimated_minutes: 20,
    primary_competencies: ['strategic_thinking', 'domain_expertise'],
    secondary_competencies: ['creative_execution'],
    frameworks: ['Supply vs. Demand Analysis', 'Growth Loops'],
    relevant_roles: ['pm', 'swe', 'tech_lead'],
    company_tags: ['Coinbase', 'Phantom', 'MetaMask'],
    tags: ['crypto', 'growth', 'web3', 'wallets', 'dapps'],
    is_published: true,
    is_calibration: false,
    is_premium: false,
    steps: [
      {
        step: 'frame',
        step_nudge: 'Is 8% engagement a supply problem, a discovery problem, or a motivation problem?',
        grading_weight: 0.25,
        step_order: 1,
        questions: [
          {
            question_text: 'What is the most accurate framing of the dapp browser engagement plateau?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'domain_expertise'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Users do not know the dapp browser tab exists — a navigation and onboarding problem', quality: 'surface', points: 1, competencies: ['strategic_thinking'], explanation: 'Discovery is a plausible contributor, but 8% non-zero engagement suggests many users have found the tab. The plateau signals a retention or value problem, not pure discovery.' },
              { option_label: 'B', option_text: 'The dapp ecosystem on-chain is too fragmented and high-risk for casual wallet holders, creating a demand gap the browser cannot solve alone', quality: 'best', points: 3, competencies: ['strategic_thinking', 'domain_expertise'], explanation: 'Phantom\'s growth was partly supply-side curation: they surfaced fewer, higher-quality dapps and reduced cold-start friction. The constraint is dapp quality and trust, not the browser UI.' },
              { option_label: 'C', option_text: 'The UX is too complex compared to centralized exchanges, causing drop-off before first interaction', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'UX friction is real, but fixing UX alone does not solve the underlying issue that most dapps are risky, low-quality, or hard to understand for non-crypto-native users.' },
              { option_label: 'D', option_text: 'Coinbase Wallet lacks brand recognition as a dapp platform versus MetaMask', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Brand awareness may play a role for crypto developers, but it does not explain why existing wallet holders fail to engage with a tab they already have.' },
            ],
          },
        ],
      },
      {
        step: 'list',
        step_nudge: 'What are the structurally distinct growth levers available to a wallet team?',
        grading_weight: 0.25,
        step_order: 2,
        questions: [
          {
            question_text: 'Which set of growth levers is most structurally distinct and actionable for dapp browser growth?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'creative_execution'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Dapp curation + one-tap onboarding for top dapps + social proof (show how many wallet holders use a given dapp)', quality: 'best', points: 3, competencies: ['strategic_thinking', 'creative_execution'], explanation: 'Three structurally distinct levers: supply quality (curation), cold-start friction (one-tap), and social validation. Each addresses a different failure mode in the funnel.' },
              { option_label: 'B', option_text: 'Redesign the dapp tab UI and add a search bar with category filters', quality: 'surface', points: 1, competencies: [], explanation: 'UI improvements are incremental, not transformative. They help discovery marginally but do not address trust, supply quality, or first-dapp completion rates.' },
              { option_label: 'C', option_text: 'Partner with 5 top dapps for in-app promotions and co-marketing', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Partnerships are a legitimate lever but address only one dimension — initial traffic. They do not address retention or the broader fragmented dapp ecosystem problem.' },
              { option_label: 'D', option_text: 'Add a DeFi yield aggregator natively inside the wallet to replace the need for external dapps', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Building a native DeFi product competes with the dapp ecosystem the wallet is meant to serve. It narrows the product into a specific vertical rather than growing the platform.' },
            ],
          },
        ],
      },
      {
        step: 'optimize',
        step_nudge: 'Which lever has the highest expected impact relative to the team\'s effort, and what do you sacrifice by choosing it?',
        grading_weight: 0.30,
        step_order: 3,
        questions: [
          {
            question_text: 'Given limited team resources, which single growth bet should come first and why?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'domain_expertise'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Curated dapp collections ("Top 10 DeFi dapps this week") with safety scores sourced from on-chain analytics, shipped first because it raises perceived quality and trust before investing in broader onboarding', quality: 'best', points: 3, competencies: ['strategic_thinking', 'domain_expertise'], explanation: 'Quality signal raises trust for the entire tab; it is prerequisite for any other lever to work. Phantom\'s curation was the unlock that made everything downstream effective. The sacrifice is speed of surface area expansion.' },
              { option_label: 'B', option_text: 'One-tap wallet connect for top dapps, reducing friction from the current 4-step approval flow', quality: 'good_but_incomplete', points: 2, competencies: ['creative_execution'], explanation: 'Friction reduction matters but assumes users are already motivated to connect. Without quality signal, reducing friction only accelerates users to bad experiences.' },
              { option_label: 'C', option_text: 'Paid growth: promote the dapp browser in Coinbase app onboarding screens to all new users', quality: 'surface', points: 1, competencies: [], explanation: 'Paid promotion drives awareness but does not solve the underlying engagement problem. New users will encounter the same low-quality, fragmented ecosystem.' },
              { option_label: 'D', option_text: 'Build a social feed showing what dapps friends are using, to create FOMO-driven adoption', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Social features require a critical mass of active users to produce meaningful signal. With 8% engagement, the social graph is too sparse to generate useful social proof.' },
            ],
          },
        ],
      },
      {
        step: 'win',
        step_nudge: 'What is the specific 10x metric target, how do you measure it, and what is your 90-day plan?',
        grading_weight: 0.20,
        step_order: 4,
        questions: [
          {
            question_text: 'What does a credible 90-day plan look like, and which metric defines success?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'creative_execution'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Ship curated dapp collections in month 1, one-tap connect in month 2, A/B test social proof in month 3; measure weekly dapp interactions per active wallet holder as north star', quality: 'best', points: 3, competencies: ['strategic_thinking', 'creative_execution'], explanation: 'Sequenced correctly: quality-first, then friction reduction, then social. North star metric (interactions per wallet holder) captures both reach and depth rather than raw user count.' },
              { option_label: 'B', option_text: 'Target 80% of wallet holders visiting the dapp tab at least once in 90 days', quality: 'surface', points: 1, competencies: [], explanation: 'A single visit is vanity — it does not indicate engagement or value. Measuring unique visitors inflates success without confirming behavior change.' },
              { option_label: 'C', option_text: 'Ship all three levers simultaneously in a big-bang launch with a coordinated PR campaign', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Parallel launch makes it impossible to isolate which lever drove results. You lose the ability to learn and double down on what works.' },
              { option_label: 'D', option_text: 'Set a target of 25% dapp tab MAU in 90 days, regardless of which lever ships first', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'The target is reasonable, but without a sequenced plan and a per-user engagement metric, it is unclear how to hit it or whether hitting it would be durable.' },
            ],
          },
        ],
      },
    ],
  },

  {
    id: 'pm-robinhood-001',
    title: 'Fintech Trends: Picking the Right Bet for Your Roadmap',
    scenario_role: 'Senior PM, Fintech Platform',
    scenario_context: 'Robinhood is expanding beyond commission-free trading into broader financial services. The product strategy team is mapping macro fintech trends to identify which should directly shape the next three-year product roadmap, and which should be monitored rather than acted on now.',
    scenario_trigger: 'The CPO asks each PM to present one trend bet at the quarterly roadmap planning session, with a clear rationale for why it is the right timing and how it connects to Robinhood\'s existing user base.',
    scenario_question: 'Which emerging fintech trend should Robinhood prioritize building toward, and what is the first product bet that moves toward it?',
    engineer_standout: 'Strong answers will distinguish between trends that are genuine market shifts versus technology novelties, and connect the chosen trend to Robinhood\'s specific distribution advantage with retail investors.',
    paradigm: 'traditional',
    industry: 'Fintech',
    sub_vertical: 'Retail Investing',
    difficulty: 'standard',
    estimated_minutes: 18,
    primary_competencies: ['strategic_thinking', 'domain_expertise'],
    secondary_competencies: ['motivation_theory'],
    frameworks: ['Market Timing Analysis', 'Jobs To Be Done'],
    relevant_roles: ['pm', 'swe', 'em'],
    company_tags: ['Robinhood', 'Betterment', 'SoFi'],
    tags: ['fintech', 'strategy', 'trends', 'roadmap', 'retail-investing'],
    is_published: true,
    is_calibration: false,
    is_premium: false,
    steps: [
      {
        step: 'frame',
        step_nudge: 'What makes a trend worth acting on now versus monitoring for another year?',
        grading_weight: 0.25,
        step_order: 1,
        questions: [
          {
            question_text: 'What is the most useful framework for deciding whether to build toward a fintech trend now?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'domain_expertise'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Trend size: pick the largest addressable market shift and build toward it', quality: 'surface', points: 1, competencies: ['strategic_thinking'], explanation: 'Market size alone is insufficient — a large trend at the wrong time, or one where Robinhood has no distribution advantage, is still a bad bet.' },
              { option_label: 'B', option_text: 'Timing plus distribution fit: is the trend past proof-of-concept but before mainstream saturation, and can Robinhood\'s retail base give it a head start?', quality: 'best', points: 3, competencies: ['strategic_thinking', 'domain_expertise'], explanation: 'Timing and distribution fit together determine when and whether to move. Robinhood\'s 20M+ retail users are a distribution advantage for trends aimed at individual investors, not enterprises.' },
              { option_label: 'C', option_text: 'Competitive landscape: pick the trend where the fewest incumbents are already established', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Low competition is necessary but not sufficient. A trend with low competition may have low competition because it is not yet viable, not because it is an opportunity.' },
              { option_label: 'D', option_text: 'Customer demand signal: pick the trend that gets the most questions in Robinhood\'s support queue', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Support questions reflect current products, not future opportunities. They systematically underweight emerging needs that customers do not yet know to ask for.' },
            ],
          },
        ],
      },
      {
        step: 'list',
        step_nudge: 'What are the major fintech trends of the next three years, and how do they differ in timing and fit?',
        grading_weight: 0.25,
        step_order: 2,
        questions: [
          {
            question_text: 'Which set of trends is most relevant for Robinhood to evaluate, and why?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['domain_expertise', 'strategic_thinking'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'AI-personalized financial coaching, fractional ownership of real assets, and embedded finance (banking inside non-finance apps)', quality: 'best', points: 3, competencies: ['domain_expertise', 'strategic_thinking'], explanation: 'Three structurally distinct trends at different timing stages: AI coaching is early-mainstream, fractional ownership has proven demand (Robinhood already does fractional equities), and embedded finance is a platform play Robinhood could enter from the supply side.' },
              { option_label: 'B', option_text: 'Cryptocurrency, NFTs, and DeFi yield farming', quality: 'surface', points: 1, competencies: [], explanation: 'These are 2021-era crypto trends. NFTs and DeFi yield farming have collapsed as consumer products. Grouping them together treats a sector as a trend.' },
              { option_label: 'C', option_text: 'BNPL (buy now pay later), digital banking accounts, and stock screeners for retail traders', quality: 'good_but_incomplete', points: 2, competencies: ['domain_expertise'], explanation: 'BNPL and digital banking are real, but BNPL is already crowded and declining in unit economics. Stock screeners are features, not trends. The list lacks forward-looking variety.' },
              { option_label: 'D', option_text: 'Blockchain-based settlement infrastructure and tokenization of securities', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Blockchain settlement is a backend infrastructure bet with a 5-10 year regulatory and adoption horizon. It is not a consumer product trend Robinhood can build toward in three years.' },
            ],
          },
        ],
      },
      {
        step: 'optimize',
        step_nudge: 'Pick one trend and name the specific sacrifice you are making by choosing it over the others.',
        grading_weight: 0.30,
        step_order: 3,
        questions: [
          {
            question_text: 'Which single trend should Robinhood prioritize, and what is the first product bet?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'creative_execution'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'AI-personalized financial coaching: launch a coaching feature that uses Robinhood\'s existing portfolio data to generate personalized weekly insights, starting with a test for Gold subscribers', quality: 'best', points: 3, competencies: ['strategic_thinking', 'creative_execution'], explanation: 'Robinhood already has the data asset (transaction history, portfolio mix, income signals) and the subscriber base to test it. The first bet is low-risk and directly monetizable through Gold tier expansion. The sacrifice is not moving on fractional real assets, which requires more regulatory work.' },
              { option_label: 'B', option_text: 'Embedded finance: become the infrastructure layer for other apps to offer investing inside their products', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Embedded finance is a credible bet, but it requires a platform pivot that takes 18-24 months and pulls focus from the core consumer product. Better as a phase 2 bet.' },
              { option_label: 'C', option_text: 'Fractional real assets: expand fractional ownership from equities to real estate REITs and commodities', quality: 'good_but_incomplete', points: 2, competencies: ['domain_expertise'], explanation: 'Credible extension of existing fractional equity capability, but regulatory friction on real estate REITs is high and customer demand signal is weak compared to AI coaching.' },
              { option_label: 'D', option_text: 'Social investing: let users follow and copy the portfolios of top-performing retail traders', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Social copying has structural regulatory risk (investment advice without a license) and has burned eToro in multiple markets. The trend has failed repeatedly in the US consumer market.' },
            ],
          },
        ],
      },
      {
        step: 'win',
        step_nudge: 'How do you present this bet to the CPO in 60 seconds without losing the nuance?',
        grading_weight: 0.20,
        step_order: 4,
        questions: [
          {
            question_text: 'Which pitch best makes the case for the AI coaching bet at the roadmap session?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['creative_execution', 'motivation_theory'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'AI personalized coaching is the one trend where Robinhood\'s data moat gives it a structural advantage over fintech peers. Wealthfront and Betterment have wealth management data; Robinhood has real-time retail trading behavior. The first bet is a coaching digest for Gold that converts that data into retention, starting in Q2.', quality: 'best', points: 3, competencies: ['creative_execution', 'motivation_theory'], explanation: 'Names the specific data advantage, names the competitor gap, and ends with a concrete product action and timeline. The CPO can say yes or no immediately.' },
              { option_label: 'B', option_text: 'AI coaching is the fastest-growing fintech category and will be worth $5B by 2027. We should move now before the window closes.', quality: 'surface', points: 1, competencies: [], explanation: 'Market size and urgency framing without naming what Robinhood\'s advantage is. This is a generic pitch that could apply to any competitor.' },
              { option_label: 'C', option_text: 'Customers are asking for more personalized guidance in our support channels. AI coaching addresses this gap and could improve NPS significantly.', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Support channel signals are backward-looking. NPS is a lagging indicator and too soft a metric for a roadmap bet.' },
              { option_label: 'D', option_text: 'We can build a coaching MVP in 6 weeks using an off-the-shelf LLM and launch to Gold users. Low-risk, high-upside.', quality: 'good_but_incomplete', points: 2, competencies: ['creative_execution'], explanation: 'Speed framing is helpful, but "off-the-shelf LLM" understates the data integration work and compliance review required for financial advice, which will concern the CPO.' },
            ],
          },
        ],
      },
    ],
  },

  {
    id: 'pm-robinhood-002',
    title: 'CPO Org Design: Three Teams That Define a Fintech Roadmap',
    scenario_role: 'Head of Product, Fintech',
    scenario_context: 'Robinhood is three years post-IPO and has stabilized its core trading product. The company is now deciding whether to deepen its financial services platform or expand into adjacent markets. The leadership team is rethinking the product org structure to reflect the next phase of the business.',
    scenario_trigger: 'The CEO asks the head of product to propose an org design: three teams, each owning a distinct product surface, structured to maximize strategic leverage in the next 18 months.',
    scenario_question: 'Which three product teams would you build, what does each own, and how do they reinforce each other?',
    engineer_standout: 'Strong answers will identify the systems-level interdependencies between teams, name what they share versus what must stay separate, and articulate the moat each team is building.',
    paradigm: 'traditional',
    industry: 'Fintech',
    sub_vertical: 'Retail Investing',
    difficulty: 'advanced',
    estimated_minutes: 22,
    primary_competencies: ['strategic_thinking', 'domain_expertise'],
    secondary_competencies: ['cognitive_empathy'],
    frameworks: ['Platform Thinking', 'Jobs To Be Done'],
    relevant_roles: ['pm', 'em', 'tech_lead'],
    company_tags: ['Robinhood', 'SoFi', 'Chime'],
    tags: ['org-design', 'strategy', 'fintech', 'product-leadership', 'platform'],
    is_published: true,
    is_calibration: false,
    is_premium: false,
    steps: [
      {
        step: 'frame',
        step_nudge: 'What is the right mental model for splitting a fintech product into distinct teams?',
        grading_weight: 0.25,
        step_order: 1,
        questions: [
          {
            question_text: 'What principle should drive how Robinhood\'s product org is divided into teams?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'domain_expertise'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Teams should map to user segments: retail traders, active investors, and passive savers', quality: 'good_but_incomplete', points: 2, competencies: ['cognitive_empathy'], explanation: 'User segment teams work well for discovery and prioritization but create duplication — all three segments use the same trading infrastructure, account layer, and notification systems.' },
              { option_label: 'B', option_text: 'Teams should map to distinct moats they are building: distribution (growth + monetization), platform (shared infrastructure + data), and product depth (new financial products)', quality: 'best', points: 3, competencies: ['strategic_thinking', 'domain_expertise'], explanation: 'Moat-based team design aligns team incentives with long-term defensibility. Each team owns a separate compounding asset, reducing coordination overhead while enabling the right dependencies.' },
              { option_label: 'C', option_text: 'Teams should map to revenue streams: subscription (Gold), transactions (trading), and new revenue (future products)', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Revenue-aligned teams optimize for current monetization but can underinvest in the infrastructure and platform capabilities that make future revenue possible.' },
              { option_label: 'D', option_text: 'Teams should map to functional areas: mobile app, backend services, and data analytics', quality: 'surface', points: 1, competencies: [], explanation: 'Functional org design creates silos between engineering and product ownership, leading to features that are technically complete but lack a clear owner for customer outcomes.' },
            ],
          },
        ],
      },
      {
        step: 'list',
        step_nudge: 'Name the three teams and define what each one owns, measures, and builds toward.',
        grading_weight: 0.25,
        step_order: 2,
        questions: [
          {
            question_text: 'Which three-team structure best positions Robinhood for the next 18 months?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'creative_execution'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Team 1: Core Trading (deepen trading UX, order types, and options); Team 2: Financial Services (retirement accounts, credit cards, banking); Team 3: Growth Platform (referrals, onboarding, Gold conversion)', quality: 'best', points: 3, competencies: ['strategic_thinking', 'creative_execution'], explanation: 'Three structurally distinct scopes: Core Trading owns the revenue-generating product, Financial Services builds adjacent moat, and Growth Platform compounds distribution. They share the account and data layer without competing for roadmap space.' },
              { option_label: 'B', option_text: 'Team 1: Consumer App; Team 2: Institutional Products; Team 3: International Expansion', quality: 'surface', points: 1, competencies: [], explanation: 'Institutional and international are both long-horizon bets that compete with core consumer investment. Three high-risk bets in parallel is likely to underdeliver on all three.' },
              { option_label: 'C', option_text: 'Team 1: AI Coach; Team 2: Social Investing; Team 3: Crypto', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'This groups three experimental features, not strategic product surfaces. None of them owns the core trading product or the account infrastructure that everything else depends on.' },
              { option_label: 'D', option_text: 'Team 1: Monetization (Gold, commissions); Team 2: Engagement (notifications, streaks, challenges); Team 3: Expansion (new asset classes)', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Reasonable split but "Engagement" as a standalone team without a financial product surface is structurally weak — engagement is a function, not a product.' },
            ],
          },
        ],
      },
      {
        step: 'optimize',
        step_nudge: 'Which team is the most critical to staff first, and what is the explicit trade-off?',
        grading_weight: 0.30,
        step_order: 3,
        questions: [
          {
            question_text: 'Which team should get the first wave of senior talent, and what are you trading away?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'cognitive_empathy'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Financial Services Team first: retirement accounts and credit card are regulatory-gated, so the long lead time makes this the constraint that determines the 18-month roadmap; trading and growth can execute with current talent', quality: 'best', points: 3, competencies: ['strategic_thinking', 'domain_expertise'], explanation: 'Regulatory products have a fixed time budget that starts running when you staff the team. Hiring for trading or growth first delays the constraint that cannot be accelerated later.' },
              { option_label: 'B', option_text: 'Growth Platform Team first: without a strong top-of-funnel, the other teams have no users to serve', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Growth matters, but Robinhood already has 20M+ accounts. The constraint is not top-of-funnel; it is product depth and regulatory surface area.' },
              { option_label: 'C', option_text: 'Core Trading Team first: it is the only revenue-generating surface and must not regress', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Protecting core revenue is a valid instinct, but Core Trading is the most mature team with the clearest roadmap. It is the least likely to fail without a surge in senior talent.' },
              { option_label: 'D', option_text: 'Staff all three teams equally in the first wave to avoid creating internal perception of favored teams', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Equal distribution optimizes for internal politics, not strategic priority. Diluting senior talent across all teams early ensures none of them can move fast.' },
            ],
          },
        ],
      },
      {
        step: 'win',
        step_nudge: 'How do the three teams stay aligned without creating coordination overhead that slows them all down?',
        grading_weight: 0.20,
        step_order: 4,
        questions: [
          {
            question_text: 'What is the lightest-weight coordination mechanism that keeps three autonomous product teams aligned?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['creative_execution', 'motivation_theory'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'A shared north star metric (active funded accounts using 2+ products) plus a monthly cross-team review of shared infrastructure dependencies — no other standing meetings', quality: 'best', points: 3, competencies: ['creative_execution', 'motivation_theory'], explanation: 'The north star creates alignment on outcome without mandating process. Infrastructure reviews are the only hard dependency worth a standing meeting. Everything else is async.' },
              { option_label: 'B', option_text: 'Weekly all-hands roadmap review where each team presents progress to the CPO', quality: 'surface', points: 1, competencies: [], explanation: 'Weekly CPO reviews create upward dependency and reporting theater. They slow teams down without adding alignment value that a shared metric cannot provide.' },
              { option_label: 'C', option_text: 'Separate OKRs per team with a quarterly roll-up to ensure strategic coherence', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'OKR roll-ups help but are too infrequent to catch infrastructure conflicts or shared platform decisions that need resolution in-quarter.' },
              { option_label: 'D', option_text: 'Rotate PMs across teams every 6 months to build institutional knowledge and prevent silos', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'PM rotation is a knowledge-sharing tool, not a coordination mechanism. It reduces domain depth and creates ownership gaps at exactly the 6-month mark when teams are most productive.' },
            ],
          },
        ],
      },
    ],
  },

  {
    id: 'pm-reddit-001',
    title: 'Reddit Search: Surfacing the Right Community at the Right Time',
    scenario_role: 'PM, Discovery and Search',
    scenario_context: 'Reddit has over 100,000 active communities, but search is widely cited as its weakest product surface. Users who land on Reddit from Google and then search within the product report frustration: results mix low-quality posts, stale threads, and irrelevant subreddits. The discovery team is tasked with improving search so users can find relevant communities and posts without relying on Google as an intermediary.',
    scenario_trigger: 'A user research study surfaces a clear pattern: 62% of users who visit Reddit via Google do not use Reddit search at all, and 41% of users who do use Reddit search abandon the results page without clicking anything.',
    scenario_question: 'How would you improve Reddit Search to help users find relevant communities and posts more effectively?',
    engineer_standout: 'Strong answers will distinguish between indexing quality (what is searchable), ranking quality (what surfaces first), and intent understanding (what the user actually wants), treating them as separate engineering and product problems.',
    paradigm: 'ai_assisted',
    industry: 'Social Media',
    sub_vertical: 'Community Platforms',
    difficulty: 'standard',
    estimated_minutes: 20,
    primary_competencies: ['strategic_thinking', 'cognitive_empathy'],
    secondary_competencies: ['domain_expertise'],
    frameworks: ['Information Architecture', 'Search Quality Framework'],
    relevant_roles: ['swe', 'pm', 'ml_eng'],
    company_tags: ['Reddit', 'Quora', 'Stack Overflow'],
    tags: ['search', 'discovery', 'communities', 'UX', 'reddit'],
    is_published: true,
    is_calibration: false,
    is_premium: false,
    steps: [
      {
        step: 'frame',
        step_nudge: 'Is this a ranking problem, an intent problem, or an indexing problem?',
        grading_weight: 0.25,
        step_order: 1,
        questions: [
          {
            question_text: 'What is the most accurate root cause of the high search abandonment rate?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'cognitive_empathy'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Reddit Search indexes poorly — too many low-quality posts make it into the results', quality: 'good_but_incomplete', points: 2, competencies: ['domain_expertise'], explanation: 'Indexing quality matters, but a 41% abandonment rate without a click suggests users see results but find them mismatched to intent, not that results are absent.' },
              { option_label: 'B', option_text: 'Reddit Search does not distinguish between post search and community search intent, so results mix the wrong type of content for what users want', quality: 'best', points: 3, competencies: ['strategic_thinking', 'cognitive_empathy'], explanation: 'Intent mismatch is the upstream problem. Users searching "anxiety" may want the r/anxiety community (for ongoing membership) or a specific post (for immediate advice) — current search returns both in an undifferentiated list.' },
              { option_label: 'C', option_text: 'Reddit Search lacks personalization — results are the same for every user regardless of community membership', quality: 'good_but_incomplete', points: 2, competencies: ['cognitive_empathy'], explanation: 'Personalization is a valid improvement area, but it does not explain abandonment among users with no Reddit account, which is a significant portion of the search audience.' },
              { option_label: 'D', option_text: 'Reddit\'s search UI is outdated compared to competitors — the results page design causes abandonment', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Design is rarely the primary driver of search abandonment. Users abandon because results do not match intent, not because the font size is wrong.' },
            ],
          },
        ],
      },
      {
        step: 'list',
        step_nudge: 'What are the distinct types of search users, and what does each need from a results page?',
        grading_weight: 0.25,
        step_order: 2,
        questions: [
          {
            question_text: 'Which user need segmentation best guides search improvements?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['cognitive_empathy', 'strategic_thinking'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Logged-in vs. logged-out users, since personalization changes what is possible', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Authentication state matters for implementation, but it is not a user need segmentation. A logged-in user searching for a community has the same intent problem as a logged-out one.' },
              { option_label: 'B', option_text: 'Community finders (want to join a subreddit), thread readers (want a specific answer or discussion), and information validators (checking if Reddit has covered a topic before Googling)', quality: 'best', points: 3, competencies: ['cognitive_empathy', 'strategic_thinking'], explanation: 'Three intent-based segments with structurally different success states. Community finders need a subscribe CTA; thread readers need a direct answer; validators need date and post quality signals.' },
              { option_label: 'C', option_text: 'New users vs. power users — power users know how to find content, new users do not', quality: 'surface', points: 1, competencies: [], explanation: 'Experience level is a useful lens for onboarding, not for search results design. The same experienced user can have community-finding or post-reading intent depending on the query.' },
              { option_label: 'D', option_text: 'Mobile users vs. desktop users, since search behavior differs across devices', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Device type affects UI treatment, not the fundamental intent mismatch problem. Fixing intent classification on desktop will transfer to mobile.' },
            ],
          },
        ],
      },
      {
        step: 'optimize',
        step_nudge: 'Which single change to search results would have the highest impact on abandonment rate?',
        grading_weight: 0.30,
        step_order: 3,
        questions: [
          {
            question_text: 'What is the most impactful change to the Reddit Search results experience?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'creative_execution'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Add tabbed results: "Communities" tab and "Posts" tab as default filters, with the system auto-detecting query intent to pre-select the right tab', quality: 'best', points: 3, competencies: ['strategic_thinking', 'creative_execution'], explanation: 'Tabs address intent disambiguation directly. The auto-detect on intent means community-finding queries pre-select Communities; question queries pre-select Posts. Abandonment drops when the first result matches what the user needed.' },
              { option_label: 'B', option_text: 'Add a "Best communities for this topic" row at the top of every search results page', quality: 'good_but_incomplete', points: 2, competencies: ['creative_execution'], explanation: 'Community promotion helps community finders but may be noise for users searching for a specific post or fact. It adds a row without solving the underlying intent mismatch.' },
              { option_label: 'C', option_text: 'Improve post ranking to surface higher-upvote, more recent posts by default', quality: 'surface', points: 1, competencies: ['domain_expertise'], explanation: 'Better ranking helps post quality but does not help users who wanted a community rather than a post. The mismatch problem persists even with excellent ranking.' },
              { option_label: 'D', option_text: 'Integrate Reddit Search with Google\'s index to pull in externally-found Reddit content', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'This deepens Reddit\'s dependency on Google rather than fixing its own search infrastructure. It also surfaces content that users can already find via Google, not the hard-to-find in-community content.' },
            ],
          },
        ],
      },
      {
        step: 'win',
        step_nudge: 'How do you measure success for search improvements, and what is your 90-day ship plan?',
        grading_weight: 0.20,
        step_order: 4,
        questions: [
          {
            question_text: 'What metric and timeline would you commit to for the search improvement project?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'creative_execution'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'North star: search session click-through rate (CTR) from results to any content. Target: reduce 41% abandonment to 25% in 90 days via tabbed UI + intent classification, starting with A/B on 10% of traffic', quality: 'best', points: 3, competencies: ['strategic_thinking', 'creative_execution'], explanation: 'CTR directly measures abandonment (the problem). The target is specific and falsifiable. Staged rollout on 10% lets you measure without full exposure risk. 90-day horizon is aggressive but achievable for a UI plus ML intent model.' },
              { option_label: 'B', option_text: 'Track NPS for users who interact with search; target 5-point improvement over the quarter', quality: 'surface', points: 1, competencies: [], explanation: 'NPS for a sub-feature is very noisy and too slow to give actionable signal within 90 days. Search quality needs behavioral metrics, not satisfaction proxies.' },
              { option_label: 'C', option_text: 'Measure search volume growth; if more users use search, the product is improving', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Search volume is a reach metric, not a quality metric. You can grow search volume through more search entry points while making each search session worse.' },
              { option_label: 'D', option_text: 'Ship the tabbed UI in month 1 and measure impact on 30-day retention for users who searched at least once', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Retention is a meaningful downstream metric, but 30-day retention is too long to measure as a primary success indicator for a single search session improvement.' },
            ],
          },
        ],
      },
    ],
  },

  {
    id: 'pm-reddit-002',
    title: 'Reddit Videos: Improving Algorithmic Ranking for Video Content',
    scenario_role: 'PM, Content Discovery',
    scenario_context: 'Reddit hosts significant video content, but videos consistently underperform relative to text and image posts in the feed algorithm. The content team believes videos are structurally disadvantaged in Reddit\'s ranking model, which was designed primarily around upvote velocity, not watch time or completion rate.',
    scenario_trigger: 'Data shows that video posts receive 30% fewer upvotes per view than image posts at the same engagement time, causing the feed algorithm to suppress videos despite users spending 2x longer on them. The product team is asked to fix the ranking disparity.',
    scenario_question: 'How would you make videos rank higher on Reddit without breaking the trust users have in the core feed algorithm?',
    engineer_standout: 'Strong answers will identify that the problem is a signal design issue (upvotes as proxy for engagement quality), not a display or promotion problem, and will propose alternative engagement signals that better capture video consumption behavior.',
    paradigm: 'ai_assisted',
    industry: 'Social Media',
    sub_vertical: 'Community Platforms',
    difficulty: 'standard',
    estimated_minutes: 20,
    primary_competencies: ['strategic_thinking', 'domain_expertise'],
    secondary_competencies: ['creative_execution'],
    frameworks: ['Algorithm Design', 'Engagement Signal Framework'],
    relevant_roles: ['swe', 'ml_eng', 'pm'],
    company_tags: ['Reddit', 'YouTube', 'TikTok'],
    tags: ['video', 'ranking', 'algorithm', 'engagement', 'reddit'],
    is_published: true,
    is_calibration: false,
    is_premium: false,
    steps: [
      {
        step: 'frame',
        step_nudge: 'Is this a ranking problem, a signal problem, or a content quality problem?',
        grading_weight: 0.25,
        step_order: 1,
        questions: [
          {
            question_text: 'What is the most accurate root cause of video underperformance in Reddit\'s feed?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'domain_expertise'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Reddit videos have lower production quality than image memes, causing users to upvote less', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Content quality may vary, but the data shows users spend 2x longer on videos, indicating quality is not the issue. The problem is a signal mismatch, not a content quality gap.' },
              { option_label: 'B', option_text: 'The feed algorithm uses upvote velocity as its primary signal, which systematically underweights video because upvoting requires interrupting watch time in a way that clicking an image does not', quality: 'best', points: 3, competencies: ['strategic_thinking', 'domain_expertise'], explanation: 'This is the correct upstream diagnosis: upvoting a video requires stopping playback, which reduces upvote rate independent of quality. The algorithm uses a proxy signal that is structurally biased against videos.' },
              { option_label: 'C', option_text: 'Reddit does not auto-play videos in the feed, so users scroll past before engaging', quality: 'good_but_incomplete', points: 2, competencies: ['cognitive_empathy'], explanation: 'Auto-play is a real product gap but it is downstream of the ranking problem. Even with auto-play, the algorithm would still underrank videos if it only uses upvote velocity.' },
              { option_label: 'D', option_text: 'Reddit lacks a dedicated video tab, so video content is buried in the main feed competing with all content types', quality: 'surface', points: 1, competencies: [], explanation: 'A dedicated video tab is a product intervention, not a root cause. The ranking problem would persist in the dedicated tab if the same algorithm signals are used.' },
            ],
          },
        ],
      },
      {
        step: 'list',
        step_nudge: 'What alternative engagement signals exist that would better represent video quality in the ranking model?',
        grading_weight: 0.25,
        step_order: 2,
        questions: [
          {
            question_text: 'Which set of alternative engagement signals best captures video consumption quality?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['domain_expertise', 'strategic_thinking'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Watch time, completion rate, and share rate', quality: 'best', points: 3, competencies: ['domain_expertise', 'strategic_thinking'], explanation: 'Three distinct signals at different funnel stages: watch time captures initial engagement, completion rate captures quality (users do not finish bad videos), and share rate captures content value that users are willing to put their name on.' },
              { option_label: 'B', option_text: 'Comment count and share count', quality: 'good_but_incomplete', points: 2, competencies: ['domain_expertise'], explanation: 'Comments and shares are valid signals but capture only post-consumption behavior. They miss the majority of video consumption that happens without any downstream action.' },
              { option_label: 'C', option_text: 'Click-to-play rate from the feed', quality: 'surface', points: 1, competencies: [], explanation: 'Click-to-play measures whether the thumbnail and title are compelling, not whether the video itself is good. It is a top-of-funnel signal, not a quality signal.' },
              { option_label: 'D', option_text: 'Number of times a video is saved to a user\'s profile', quality: 'good_but_incomplete', points: 2, competencies: ['cognitive_empathy'], explanation: 'Save rate is a high-intent signal but too infrequent to generate enough data to rank most videos reliably. It should supplement, not replace, watch-time signals.' },
            ],
          },
        ],
      },
      {
        step: 'optimize',
        step_nudge: 'How do you weight new signals against upvotes without breaking the feed algorithm for non-video content?',
        grading_weight: 0.30,
        step_order: 3,
        questions: [
          {
            question_text: 'What is the safest way to introduce video-specific signals into Reddit\'s ranking model?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'creative_execution'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Replace upvote weight with watch-time weight for all video posts globally', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Global replacement is a high-risk change that removes the signal users most understand and trust. Sudden ranking changes on video will produce complaints and gaming behavior as creators learn to optimize for watch time.' },
              { option_label: 'B', option_text: 'Add a content-type-specific ranking branch: video posts are ranked by a blended score of upvotes (40%) + completion rate (40%) + share rate (20%), while all other content uses the existing algorithm unchanged', quality: 'best', points: 3, competencies: ['strategic_thinking', 'creative_execution'], explanation: 'Content-type branching protects non-video content from unintended effects, is testable in isolation, and allows the video signal weights to be tuned independently. This is how YouTube and TikTok handle multi-format feeds.' },
              { option_label: 'C', option_text: 'Apply a blanket 1.5x boost to all video posts to compensate for the upvote rate disadvantage', quality: 'surface', points: 1, competencies: [], explanation: 'A static boost is crude and will over-rank bad videos that happen to be videos. It addresses the symptom without fixing the signal design.' },
              { option_label: 'D', option_text: 'Add watch-time as an additional ranking signal alongside upvotes for all content types, not just video', quality: 'good_but_incomplete', points: 2, competencies: ['domain_expertise'], explanation: 'Adding watch-time to text and image posts does not make sense semantically and would be undefined for non-video content. The intervention needs to be video-specific.' },
            ],
          },
        ],
      },
      {
        step: 'win',
        step_nudge: 'How do you validate the new ranking model and communicate the change to Reddit\'s creator community?',
        grading_weight: 0.20,
        step_order: 4,
        questions: [
          {
            question_text: 'What is the right validation and communication plan for the new video ranking model?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['creative_execution', 'strategic_thinking'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'A/B test the new blended signal on 20% of users for 30 days; success criteria are video CTR up 15% and overall feed satisfaction score maintained; publish the signal change in the Reddit developer blog before full rollout', quality: 'best', points: 3, competencies: ['creative_execution', 'strategic_thinking'], explanation: 'A/B test on a subset limits exposure risk. Two success criteria (video CTR and feed satisfaction) catch both the improvement and the potential regression. Developer blog communication prevents creator community backlash by being transparent before rollout.' },
              { option_label: 'B', option_text: 'Roll out to all users at once and monitor for a 2-week impact assessment window', quality: 'surface', points: 1, competencies: [], explanation: 'Full rollout without a holdout group means you cannot measure the counterfactual. If the change has an unexpected effect, you have no clean A/B data to diagnose it.' },
              { option_label: 'C', option_text: 'Run the new model in parallel with the old one and manually compare results for a week before shipping', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Manual comparison is useful for sanity checking but cannot replace a controlled A/B test on real user behavior at scale.' },
              { option_label: 'D', option_text: 'Announce the change in subreddits for video creators and gather feedback before shipping the algorithm update', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Community feedback on an algorithm change will surface creator self-interest, not user interest. Algorithm changes should be validated with behavioral data, not creator sentiment.' },
            ],
          },
        ],
      },
    ],
  },

  {
    id: 'pm-tiktok-001',
    title: 'TikTok DAU Growth: Ranking Three Levers with Experiments',
    scenario_role: 'PM, Growth Analytics',
    scenario_context: 'TikTok\'s growth team is evaluating three potential levers for increasing daily active users: improving the recommendation algorithm, investing in user acquisition campaigns, and building new creator tools. Each lever has a clear cost structure and a set of proposed experiments, but the team needs to decide which one to prioritize for the next quarter.',
    scenario_trigger: 'The VP of Growth asks for a data-driven recommendation: which lever will most effectively boost DAU, and what experiments would give the highest-confidence answer before committing full resources?',
    scenario_question: 'Which data and experiments would you run to decide whether recommendations, user acquisition, or creator tools will boost TikTok\'s DAU most effectively?',
    engineer_standout: 'Strong answers will separate experiment design from intuition, identify the right proxy metrics for each lever, and be explicit about which lever has the highest variance and requires the most conservative experiment budget.',
    paradigm: 'ai_assisted',
    industry: 'Social Media',
    sub_vertical: 'Short-Form Video',
    difficulty: 'advanced',
    estimated_minutes: 22,
    primary_competencies: ['strategic_thinking', 'domain_expertise'],
    secondary_competencies: ['creative_execution'],
    frameworks: ['Experiment Design', 'Growth Accounting'],
    relevant_roles: ['pm', 'data_eng', 'ml_eng'],
    company_tags: ['TikTok', 'Instagram', 'YouTube'],
    tags: ['growth', 'experimentation', 'DAU', 'recommendations', 'creator-tools'],
    is_published: true,
    is_calibration: false,
    is_premium: false,
    steps: [
      {
        step: 'frame',
        step_nudge: 'What is TikTok\'s current DAU growth constraint: acquisition, activation, or retention?',
        grading_weight: 0.25,
        step_order: 1,
        questions: [
          {
            question_text: 'What diagnostic question should you answer before choosing which lever to test first?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'domain_expertise'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Which lever is cheapest to experiment on — start with the lowest-cost test first', quality: 'surface', points: 1, competencies: [], explanation: 'Cost of experimentation is a valid tiebreaker but not the primary criterion. A cheap test on the wrong lever generates cheap but useless data.' },
              { option_label: 'B', option_text: 'Where is DAU growth currently constrained: is it new users coming in (acquisition), new users staying (activation), or existing users churning (retention)?', quality: 'best', points: 3, competencies: ['strategic_thinking', 'domain_expertise'], explanation: 'Growth accounting first: if churn is high, user acquisition spending will not move DAU sustainably. If activation is low, creator tools will not help. The constraint determines which lever is load-bearing.' },
              { option_label: 'C', option_text: 'Which lever has the most cross-functional dependencies — pick the one with fewest blockers', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Execution feasibility matters, but choosing the easiest lever rather than the right lever optimizes for speed over impact. The constraint analysis comes first.' },
              { option_label: 'D', option_text: 'Which lever is most commonly cited in growth literature for social apps', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Benchmarks from other apps ignore TikTok-specific constraints. What worked for Instagram at a different growth stage may be exactly wrong for TikTok today.' },
            ],
          },
        ],
      },
      {
        step: 'list',
        step_nudge: 'Design one experiment for each lever that gives a high-confidence answer in under 30 days.',
        grading_weight: 0.25,
        step_order: 2,
        questions: [
          {
            question_text: 'Which experiment set best measures each lever\'s impact on DAU?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['domain_expertise', 'creative_execution'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Recommendations: holdback test where 10% of users get the current algorithm vs. a retrained model; User acquisition: geo-isolated paid campaign at 2x budget; Creator tools: invite 500 creators to a new tool beta and measure their follower growth and posting frequency', quality: 'best', points: 3, competencies: ['domain_expertise', 'creative_execution'], explanation: 'Three structurally different experiment designs matching each lever\'s nature: holdback for algorithm (needs a true counterfactual), geo-isolated for acquisition (isolates paid signal from organic), and beta cohort for creator tools (measures the creator supply effect on downstream DAU).' },
              { option_label: 'B', option_text: 'Survey 1,000 users on which lever they prefer, then build what they vote for', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Stated preference surveys systematically overestimate acquisition and creator interest. Users do not understand algorithm changes and cannot reliably predict what would improve their own retention.' },
              { option_label: 'C', option_text: 'Run all three as simultaneous A/B tests on overlapping user populations', quality: 'surface', points: 1, competencies: ['strategic_thinking'], explanation: 'Simultaneous overlapping tests create interference between treatments. If a user is in both the recommendation experiment and receives a creator tool, you cannot isolate which lever caused the DAU change.' },
              { option_label: 'D', option_text: 'Measure the correlation between recommendation quality scores and DAU over the past 12 months to infer lever impact', quality: 'good_but_incomplete', points: 2, competencies: ['domain_expertise'], explanation: 'Historical correlation is useful context but cannot establish causality. Algorithm changes often coincide with seasonal effects or competitor events that make correlation misleading.' },
            ],
          },
        ],
      },
      {
        step: 'optimize',
        step_nudge: 'Based on the experiments, how do you decide which lever gets the Q4 budget, and what is the risk you are accepting?',
        grading_weight: 0.30,
        step_order: 3,
        questions: [
          {
            question_text: 'Experiments show: recommendations +4% DAU, user acquisition +9% DAU (in test geo), creator tools +1.5% DAU. How do you allocate Q4 resources?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'creative_execution'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Put full Q4 budget into user acquisition since it showed the highest DAU lift in the test geo', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Geo-isolated acquisition tests systematically overstate global impact due to network effects and saturation in new geos. A +9% result in a test market may produce +2-3% globally when the campaign scales and bids against itself.' },
              { option_label: 'B', option_text: 'Primary bet on recommendations at 50% of budget (durable, compound over time), secondary bet on acquisition at 35% (with expectation that global lift is closer to 4-5%), and creator tools at 15% as a longer-horizon bet', quality: 'best', points: 3, competencies: ['strategic_thinking', 'creative_execution'], explanation: 'Recommendations produce compounding returns since each improvement makes future improvements more valuable. Acquisition is capped by budget and decays immediately when spending stops. Creator tools build supply-side moat that acquisition cannot replicate. The split reflects durability, not just point-in-time lift.' },
              { option_label: 'C', option_text: 'Split equally: 33% to each lever since the experiment results are all within the margin of error', quality: 'surface', points: 1, competencies: [], explanation: 'Equal split is a political decision, not a data-driven one. If the experiments were powered correctly, the 4% vs. 1.5% difference is meaningful and should drive resource concentration.' },
              { option_label: 'D', option_text: 'Drop creator tools entirely since +1.5% DAU is below the cost of the team, and split remaining budget between recommendations and acquisition at 60/40', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Reasonable allocation, but dropping creator tools based on a 30-day experiment misses the 6-12 month compounding effect on content supply and organic growth that creator investment produces.' },
            ],
          },
        ],
      },
      {
        step: 'win',
        step_nudge: 'How do you present this recommendation to the VP of Growth and get a fast decision?',
        grading_weight: 0.20,
        step_order: 4,
        questions: [
          {
            question_text: 'Which presentation structure would most effectively get the VP of Growth to a decision in one meeting?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['creative_execution', 'motivation_theory'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'One slide per lever: experiment result, extrapolated global impact, 90-day cost, and key risk. Final slide: recommended allocation with confidence level for each lever. End with a single decision: approve the allocation or shift recommendation budget to acquisition.', quality: 'best', points: 3, competencies: ['creative_execution', 'motivation_theory'], explanation: 'Forces a binary decision on the one real variable (recommendations vs. acquisition split) after giving the VP all the data. Executives can approve or redirect in one move without reopening the entire analysis.' },
              { option_label: 'B', option_text: 'Present all three experiment findings in detail, then open the floor to the leadership team to discuss allocations', quality: 'surface', points: 1, competencies: [], explanation: 'Open discussion after detailed findings produces inconclusive committee decisions. The team will argue about experiment validity rather than making a resource call.' },
              { option_label: 'C', option_text: 'Send a written doc 48 hours before the meeting with the data, and use the meeting only for Q&A', quality: 'good_but_incomplete', points: 2, competencies: ['creative_execution'], explanation: 'Pre-read docs are good practice but do not guarantee a decision — the VP may read the doc, have concerns, and use the meeting to reopen questions rather than decide.' },
              { option_label: 'D', option_text: 'Present only the winning lever recommendation without showing the other experiment results, to avoid scope creep', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Omitting the other results removes context the VP needs to sanity-check the recommendation. Executives who feel data was hidden lose trust in the analysis even if the conclusion is correct.' },
            ],
          },
        ],
      },
    ],
  },

  {
    id: 'pm-tiktok-002',
    title: 'TikTok Shop Creator Ads: Designing Cross-Sell for Creators',
    scenario_role: 'PM, Commerce and Creator Monetization',
    scenario_context: 'TikTok Shop has built a growing e-commerce layer directly inside the TikTok app, where creators can tag products in videos and earn commissions. The ads business and the creator monetization team have identified an untapped opportunity: creators who already run TikTok Shop storefronts are not buying TikTok ads to promote their Shop listings, and TikTok is not proactively surfacing ads as a tool for creators who are already selling.',
    scenario_trigger: 'The Head of Commerce asks for a product plan to cross-sell TikTok ads to TikTok Shop creators, increasing the share of creators who run at least one paid ad campaign within 90 days of opening a Shop storefront.',
    scenario_question: 'How would you design the cross-sell of TikTok ads to TikTok Shop creators, and what would make a creator choose to spend on ads?',
    engineer_standout: 'Strong answers will address the creator\'s mental model about organic reach versus paid reach, the friction in TikTok\'s existing ads product (Ads Manager), and the cold-start problem for creators with no previous ads experience.',
    paradigm: 'ai_native',
    industry: 'Social Commerce',
    sub_vertical: 'Creator Monetization',
    difficulty: 'advanced',
    estimated_minutes: 22,
    primary_competencies: ['strategic_thinking', 'motivation_theory'],
    secondary_competencies: ['creative_execution'],
    frameworks: ['Jobs To Be Done', 'Funnel Analysis'],
    relevant_roles: ['pm', 'swe', 'tech_lead'],
    company_tags: ['TikTok', 'Meta', 'Shopify'],
    tags: ['creator-economy', 'ads', 'ecommerce', 'cross-sell', 'tiktok-shop'],
    is_published: true,
    is_calibration: false,
    is_premium: false,
    steps: [
      {
        step: 'frame',
        step_nudge: 'Why isn\'t a creator who is already selling on TikTok Shop buying ads to sell more?',
        grading_weight: 0.25,
        step_order: 1,
        questions: [
          {
            question_text: 'What is the most accurate reason TikTok Shop creators are not buying ads?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['motivation_theory', 'cognitive_empathy'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Creators do not know TikTok has an ads product for Shop listings', quality: 'surface', points: 1, competencies: [], explanation: 'Awareness may be low, but creators who are actively running storefronts have seen ad prompts in the Creator Center. The gap is motivation and ease, not pure awareness.' },
              { option_label: 'B', option_text: 'Creators believe organic video content is cheaper and builds a more authentic audience than paid ads, so ads feel like admitting the content is not good enough', quality: 'best', points: 3, competencies: ['motivation_theory', 'cognitive_empathy'], explanation: 'Creator identity is tied to organic reach. Paying for ads conflicts with the creator\'s self-image as someone who grows through content quality, not budget. This is a motivational barrier, not an awareness or pricing barrier.' },
              { option_label: 'C', option_text: 'TikTok Ads Manager is too complex for creators who are not professional marketers', quality: 'good_but_incomplete', points: 2, competencies: ['cognitive_empathy'], explanation: 'Friction in Ads Manager is a real barrier, but it is a downstream friction point. If creators believed ads would clearly pay off, they would navigate the complexity. The motivation gap comes first.' },
              { option_label: 'D', option_text: 'Creators cannot afford ads because their Shop margins are too thin to invest in paid promotion', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Budget is a constraint for some creators but not the primary driver. Many creators with healthy Shop revenue still do not buy ads. The issue is perceived ROI, not ability to pay.' },
            ],
          },
        ],
      },
      {
        step: 'list',
        step_nudge: 'What product surfaces and triggers could bridge creators from running a Shop to running an ad?',
        grading_weight: 0.25,
        step_order: 2,
        questions: [
          {
            question_text: 'Which cross-sell surfaces would most effectively move creators from Shop to Ads?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'creative_execution'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'A TikTok Shop dashboard widget showing "boost this video for $X, estimated reach Y" when a Shop video goes above average watch time, plus a post-campaign ROI summary that shows earnings attributable to the ad', quality: 'best', points: 3, competencies: ['strategic_thinking', 'creative_execution'], explanation: 'Three cross-sell triggers at the right moments: when a video is already performing well (motivation to push further), with a concrete projected reach (addresses the ROI uncertainty), and with an ROI summary that closes the loop and builds future willingness to spend.' },
              { option_label: 'B', option_text: 'A banner ad on the TikTok Creator Center homepage promoting TikTok Ads Manager', quality: 'surface', points: 1, competencies: [], explanation: 'Passive banners on the Creator Center are treated as background noise. They reach creators at the wrong moment (browsing, not selling) and do not address the motivation barrier.' },
              { option_label: 'C', option_text: 'Email campaign to all Shop creators with a $50 ad credit and a link to Ads Manager', quality: 'good_but_incomplete', points: 2, competencies: ['motivation_theory'], explanation: 'Ad credits reduce the financial risk of trying ads, which is a real activation lever. But the Ads Manager link sends creators into a complex product without the contextual framing of which video to promote or why.' },
              { option_label: 'D', option_text: 'Add an "advertise this product" button directly on each Shop listing page in the app', quality: 'good_but_incomplete', points: 2, competencies: ['creative_execution'], explanation: 'Good placement (contextual) but product-level ads are a different mental model from video-level ads. Creators think in videos, not product listings, for organic content.' },
            ],
          },
        ],
      },
      {
        step: 'optimize',
        step_nudge: 'Which surface should you build first, and what does the simplified ad-creation flow look like for a creator with no ads experience?',
        grading_weight: 0.30,
        step_order: 3,
        questions: [
          {
            question_text: 'What does the minimum viable creator ads flow look like inside TikTok Shop?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'creative_execution'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'A three-step flow inside the Creator Center: (1) select a Shop video, (2) set a budget ($10/$20/$50 presets), (3) tap "Boost" — TikTok automatically targets the video to users similar to those who already bought from the creator\'s Shop', quality: 'best', points: 3, competencies: ['strategic_thinking', 'creative_execution'], explanation: 'Three-step flow removes every Ads Manager complexity. Budget presets eliminate the blank-box anxiety. Auto-targeting based on existing Shop buyer lookalikes reduces the creator\'s need to understand audience configuration.' },
              { option_label: 'B', option_text: 'Redirect creators to TikTok Ads Manager with a pre-filled template based on their most recent Shop video', quality: 'good_but_incomplete', points: 2, competencies: ['creative_execution'], explanation: 'Pre-filling helps, but Ads Manager itself is still a context switch that exposes creators to dozens of settings they do not understand. The first-time conversion rate will remain low.' },
              { option_label: 'C', option_text: 'Build an AI-powered ads advisor inside Creator Center that recommends ad settings based on creator performance history', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'AI advisor addresses the knowledge gap but requires the creator to trust a recommendation and still navigate a purchase flow. It is a good phase 2 feature, not the MVP.' },
              { option_label: 'D', option_text: 'Auto-boost creators\' top-performing Shop videos automatically and charge them afterward, with the option to turn off', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Automatic charges without explicit creator consent will create immediate trust damage and platform backlash. Opt-out billing models in creator tools have historically caused brand crises.' },
            ],
          },
        ],
      },
      {
        step: 'win',
        step_nudge: 'What is the activation metric and 90-day target for the cross-sell program?',
        grading_weight: 0.20,
        step_order: 4,
        questions: [
          {
            question_text: 'Which metric and target best captures success for the creator ads cross-sell program?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'motivation_theory'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Shop-to-Ads conversion rate: percentage of new Shop storefronts that run at least one paid campaign within 90 days. Target: 15% within 90 days of the simplified boost flow launch.', quality: 'best', points: 3, competencies: ['strategic_thinking', 'motivation_theory'], explanation: 'Directly measures the cross-sell goal as stated. 15% is ambitious but achievable given the simplified flow. It is falsifiable and points to a specific product change as the lever.' },
              { option_label: 'B', option_text: 'Total ad spend from Shop creators in Q3 versus Q2', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Total spend growth is an important business metric but it is influenced by existing heavy spenders who were already running ads. Conversion rate of new creators is a cleaner signal of cross-sell effectiveness.' },
              { option_label: 'C', option_text: 'Number of creators who visit the Boost feature landing page within 30 days of opening a Shop', quality: 'surface', points: 1, competencies: [], explanation: 'Page visits measure awareness, not conversion. A creator who visits and leaves without spending is not a win for the program.' },
              { option_label: 'D', option_text: 'Creator satisfaction score for the ads experience, measured via post-campaign survey', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Satisfaction surveys are too slow and too soft to measure a cross-sell program. The program\'s success is measured by creators spending, not by how they felt about it.' },
            ],
          },
        ],
      },
    ],
  },

  {
    id: 'pm-netflix-001',
    title: 'Netflix Podcast: Designing an Audio Product for a Video Platform',
    scenario_role: 'Senior PM, New Products',
    scenario_context: 'Netflix has built its brand entirely around premium video content. As the podcast market has grown to 500M listeners globally, Netflix\'s original content library (documentaries, true crime series, scripted dramas) represents an untapped audio adjacency. Several Netflix originals have already generated significant podcast spin-off interest from external producers.',
    scenario_trigger: 'The VP of Product asks the new products team to evaluate building a podcast product natively inside Netflix, starting with the existing original content library as the content seed.',
    scenario_question: 'Build a podcast product for Netflix: what is the core concept, who is the primary user, what is on the roadmap, and what are the risks?',
    engineer_standout: 'Strong answers will distinguish between audio-native podcasts and video-derived audio, address the discovery and recommendation system required, and be explicit about the risk of cannibalizing Netflix\'s watch time with listen time.',
    paradigm: 'traditional',
    industry: 'Entertainment',
    sub_vertical: 'Streaming and Podcasting',
    difficulty: 'advanced',
    estimated_minutes: 25,
    primary_competencies: ['strategic_thinking', 'creative_execution'],
    secondary_competencies: ['domain_expertise', 'taste'],
    frameworks: ['Jobs To Be Done', 'Platform Thinking'],
    relevant_roles: ['pm', 'swe', 'em'],
    company_tags: ['Netflix', 'Spotify', 'Apple Podcasts'],
    tags: ['netflix', 'podcasts', 'audio', 'product-design', 'new-product'],
    is_published: true,
    is_calibration: false,
    is_premium: false,
    steps: [
      {
        step: 'frame',
        step_nudge: 'What is the core user problem that a Netflix podcast product would solve, and for whom?',
        grading_weight: 0.25,
        step_order: 1,
        questions: [
          {
            question_text: 'What is the most accurate framing of the opportunity for a Netflix podcast product?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'cognitive_empathy'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Netflix wants to capture podcast market share from Spotify and Apple Podcasts by launching a competing platform', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Market share competition with Spotify would require an open podcast catalog, which Netflix cannot fill and which would commoditize the product. Netflix\'s advantage is exclusive content, not catalog breadth.' },
              { option_label: 'B', option_text: 'Netflix subscribers who love a specific show want to go deeper after watching — a podcast product serves the continuation of engagement for super-fans of existing Netflix originals', quality: 'best', points: 3, competencies: ['strategic_thinking', 'cognitive_empathy'], explanation: 'The job is "extend the story" for existing fans, not "find new content." This framing anchors the product in Netflix\'s existing content moat and targets a user who is already proven (paid subscriber, engaged viewer).' },
              { option_label: 'C', option_text: 'Netflix needs an audio product to compete with Spotify\'s push into video podcasts and audiobooks', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Competitive framing is real context, but it does not identify what user problem Netflix would uniquely solve. Entering a competition without a user need anchor leads to undifferentiated products.' },
              { option_label: 'D', option_text: 'Netflix can increase subscriber value by bundling podcasts with the existing subscription to reduce churn', quality: 'good_but_incomplete', points: 2, competencies: ['motivation_theory'], explanation: 'Churn reduction through bundle value is a valid business rationale, but it does not define what the podcast product should actually be or who should use it.' },
            ],
          },
        ],
      },
      {
        step: 'list',
        step_nudge: 'What are the structurally distinct types of podcast content Netflix could launch, and how do they differ?',
        grading_weight: 0.25,
        step_order: 2,
        questions: [
          {
            question_text: 'Which content strategy gives Netflix the strongest foundation for a podcast product?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'domain_expertise'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Open catalog: license existing podcasts from independent creators to populate the platform at launch', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Open catalog requires content licensing infrastructure Netflix does not have and creates direct competition with Spotify and Apple, where Netflix has no distribution advantage and weaker brand association with audio.' },
              { option_label: 'B', option_text: 'Three tiers: show-companion podcasts (behind-the-scenes, creator interviews for existing originals), deep-dive audio originals (audio-first content in genres where Netflix is strong: true crime, documentary), and serialized fiction audio (audio dramas tied to Netflix IP)', quality: 'best', points: 3, competencies: ['strategic_thinking', 'domain_expertise'], explanation: 'Three structurally distinct content types, ordered by production complexity. Companion podcasts ship fastest using existing IP and interviews. Deep-dive audio originals expand the addressable audience. Serialized fiction builds new IP moat. Each serves the core user (Netflix super-fan) at different depth.' },
              { option_label: 'C', option_text: 'Start with a single format: one companion podcast per Netflix original show, tied to new season releases', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Single-format focus is operationally achievable and tied to proven content interest. The limitation is that companion podcasts alone do not attract users who are not already fans of a specific show.' },
              { option_label: 'D', option_text: 'Launch a creator marketplace where external podcasters can produce Netflix-licensed content', quality: 'surface', points: 1, competencies: [], explanation: 'Marketplace models require platform mass before creators have incentive to participate. Netflix has no podcast audience to attract creators at launch.' },
            ],
          },
        ],
      },
      {
        step: 'optimize',
        step_nudge: 'What is the biggest risk in building this product, and how do you design around it?',
        grading_weight: 0.30,
        step_order: 3,
        questions: [
          {
            question_text: 'What is the biggest structural risk in a Netflix podcast product, and what design choice mitigates it?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'creative_execution'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'The biggest risk is low podcast production quality compared to established podcast studios; mitigate by hiring experienced audio producers from Spotify and NPR', quality: 'surface', points: 1, competencies: [], explanation: 'Production quality is an execution risk but not the structural risk. Netflix already produces high-quality audio through documentaries. Hiring audio producers does not address the fundamental question of whether subscribers will listen.' },
              { option_label: 'B', option_text: 'The biggest risk is listen-time cannibalizing watch-time, reducing the core viewing engagement that justifies the subscription price; mitigate by making podcasts available only during times Netflix cannot capture watch-time (commute, exercise, sleep)', quality: 'best', points: 3, competencies: ['strategic_thinking', 'creative_execution'], explanation: 'Cannibalization is the structural risk unique to Netflix (not a risk for Spotify or Apple). The mitigation is use-case scoping: position podcasts explicitly as "for moments when video is not possible," not as a replacement for watching. This design choice preserves the watch-time north star.' },
              { option_label: 'C', option_text: 'The biggest risk is that Netflix cannot compete with Spotify\'s recommendation algorithm for audio content; mitigate by building a dedicated podcast recommendation system', quality: 'good_but_incomplete', points: 2, competencies: ['domain_expertise'], explanation: 'Algorithm quality is a real challenge, but Netflix starts with a significant advantage: it already knows what shows each subscriber watches and can recommend companion content with high relevance. The algorithm risk is overstated.' },
              { option_label: 'D', option_text: 'The biggest risk is regulatory: podcast advertising revenue may require different licensing agreements than streaming video', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Regulatory risk is manageable and not structural. Netflix can launch ad-free podcasts included in the subscription without advertising, completely avoiding this risk in the initial product.' },
            ],
          },
        ],
      },
      {
        step: 'win',
        step_nudge: 'How do you pitch this to the VP of Product as a two-year roadmap with a clear Phase 1 that can ship in 6 months?',
        grading_weight: 0.20,
        step_order: 4,
        questions: [
          {
            question_text: 'What does the Phase 1 pitch look like, and what proof point would make the VP say yes?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['creative_execution', 'motivation_theory'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Phase 1 in 6 months: companion podcasts for the top 10 Netflix originals by watch-time, surfaced inside the Netflix app on the show detail page. Success metric: 5% of viewers who finish a show start a companion podcast episode. Proof point at the VP meeting: cite Stranger Things and Wednesday fan communities that have already created unofficial companion content, proving latent demand.', quality: 'best', points: 3, competencies: ['creative_execution', 'motivation_theory'], explanation: 'Phase 1 is scoped to the minimum: no new content infrastructure, no new app surfaces. The success metric is behavioral and measurable in 90 days. The proof point references observable existing demand (unofficial fan podcasts), not a hypothetical market analysis.' },
              { option_label: 'B', option_text: 'Phase 1 in 6 months: launch a standalone Netflix Podcast app with 50 companion episodes across 20 shows. Success metric: 1M app downloads in the first month.', quality: 'surface', points: 1, competencies: [], explanation: 'A standalone app is a major distribution bet that isolates podcast listeners from Netflix\'s existing app user base. 1M downloads is a reach metric that does not confirm listener engagement or subscription impact.' },
              { option_label: 'C', option_text: 'Phase 1 in 6 months: pilot three companion podcasts for upcoming originals and measure whether podcast listeners have higher 90-day retention than non-listeners.', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Retention correlation is the right long-term metric, but 90 days is too slow to use as a VP proof point for a 6-month Phase 1. Retention studies require 12+ months to produce reliable signal.' },
              { option_label: 'D', option_text: 'Phase 1: license 500 existing podcast episodes from Spotify and Apple to populate the Netflix audio library, then measure subscriber engagement.', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Licensing from Spotify and Apple creates a competitor dependency and does not use Netflix\'s content moat. It is the slowest, most expensive, and strategically weakest Phase 1 option.' },
            ],
          },
        ],
      },
    ],
  },
] as const
