// PM Interview Challenges — Batch 1: OpenAI (q001-q007)
// Generated for HackProduct content pipeline

export const CHALLENGES = [
  {
    id: 'pm-openai-001',
    title: 'AI Pet Communication: Defining the Problem Space',
    scenario_role: 'Staff Engineer, AI Products',
    scenario_context: 'OpenAI is exploring consumer AI applications beyond text. A research team has prototyped a model that interprets pet vocalizations, body language signals, and biometric data. The question is whether there is a real product here.',
    scenario_trigger: 'A VP asks for a product brief on whether to invest further — not a demo, but a product direction with a clear user problem and a defined success metric.',
    scenario_question: 'How do you frame the problem space, identify the real user need, and define what success looks like for an AI pet communication product?',
    engineer_standout: "A strong engineer would immediately ask about the model's actual signal quality and error rate — pet communication accuracy is not binary, and a product built on low-confidence outputs needs very different UX than one built on high-confidence ones.",
    paradigm: 'ai_native',
    industry: 'Consumer AI',
    sub_vertical: 'Pet Tech',
    difficulty: 'standard',
    estimated_minutes: 20,
    primary_competencies: ['motivation_theory', 'strategic_thinking'],
    secondary_competencies: ['cognitive_empathy'],
    frameworks: ['Jobs To Be Done', 'North Star Framework'],
    relevant_roles: ['swe', 'pm', 'ml_eng'],
    company_tags: ['OpenAI', 'Whisper', 'Petcube'],
    tags: ['consumer-ai', 'product-design', 'pet-tech', 'ai-native'],
    is_published: true,
    is_calibration: false,
    is_premium: false,
    steps: [
      {
        step: 'frame',
        step_nudge: 'Before designing anything, what is the actual human need — and is the pet the user or a means to something else?',
        grading_weight: 0.25,
        step_order: 1,
        questions: [
          {
            question_text: 'What is the most accurate framing of the user problem for an AI pet communication product?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['motivation_theory', 'cognitive_empathy'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Pet owners want to understand what their pet is trying to communicate when it is distressed, so they can act faster and feel less helpless', quality: 'best', points: 3, competencies: ['motivation_theory', 'cognitive_empathy'], explanation: 'This frames the job correctly: the emotional driver is anxiety reduction and faster response, not novelty. Distress signals are the highest-value case because the stakes are real.' },
              { option_label: 'B', option_text: 'Pet owners want real-time translation of pet sounds into natural language because existing tools cannot do this', quality: 'surface', points: 1, competencies: ['strategic_thinking'], explanation: 'Framing around capability rather than need produces a feature, not a product. Translation without a clear use case has no natural success metric.' },
              { option_label: 'C', option_text: 'Veterinarians need better diagnostic data from pet behavior to reduce misdiagnosis rates at initial consultations', quality: 'good_but_incomplete', points: 2, competencies: ['domain_expertise'], explanation: 'A real and high-value segment, but this frames a B2B clinical tool rather than a consumer product, which changes the build entirely.' },
              { option_label: 'D', option_text: 'Pet owners are underserved by current wearables that only track activity, not emotional state', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'This restates a competitive gap, not a user need. Competitive gaps do not define what the product should be or who it serves.' },
            ],
          },
        ],
      },
      {
        step: 'list',
        step_nudge: 'What are the structurally distinct approaches to this product, considering both the AI capability and the human use case?',
        grading_weight: 0.25,
        step_order: 2,
        questions: [
          {
            question_text: 'Which set of product directions represents the widest range of structurally distinct approaches?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'creative_execution'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'A real-time alert app, a daily mood summary app, a weekly behavior report app, and a monthly health digest app', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'All four are the same product at different cadences. This is a variation list, not a direction list. Width before depth means structurally different paradigms.' },
              { option_label: 'B', option_text: 'A distress alert tool for owners, a behavior data API for vet EMR systems, a companion app for enrichment coaching, and a pet health insurance underwriting signal', quality: 'best', points: 3, competencies: ['strategic_thinking', 'creative_execution'], explanation: 'Each direction targets a different user, distribution model, and value driver. This forces a real choice rather than an incremental one.' },
              { option_label: 'C', option_text: 'A consumer app for dog owners, a consumer app for cat owners, and a consumer app for small animals', quality: 'surface', points: 1, competencies: ['cognitive_empathy'], explanation: 'Species segmentation is table stakes, not a strategic direction. These are the same product with different training data.' },
              { option_label: 'D', option_text: 'A social app where owners share pet mood data, a subscription app for expert consultations, and a marketplace for pet accessories', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'These are distinct directions but the marketplace option drifts far from the AI capability. Two of three are coherent, one is a distraction.' },
            ],
          },
        ],
      },
      {
        step: 'optimize',
        step_nudge: 'If you had to pick one direction and ship in 6 months, what is the explicit criterion you are optimizing for, and what are you giving up?',
        grading_weight: 0.30,
        step_order: 3,
        questions: [
          {
            question_text: 'Which approach best identifies the optimization criterion and names the explicit sacrifice?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'domain_expertise'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Optimize for clinical credibility by launching with vets first — sacrifice consumer scale to build a defensible data moat before the consumer market matures', quality: 'best', points: 3, competencies: ['strategic_thinking', 'domain_expertise'], explanation: 'Names the criterion (clinical credibility) and the sacrifice (consumer scale) explicitly. Starting with vets produces labeled ground truth that raises model accuracy before a consumer launch.' },
              { option_label: 'B', option_text: 'Focus on dog owners first because it is the largest segment and dogs have the most behavioral research available', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Reasonable segment choice, but this names a reason without naming the optimization criterion or what is being sacrificed.' },
              { option_label: 'C', option_text: 'Build for all pet types and all use cases simultaneously to maximize addressable market from launch', quality: 'plausible_wrong', points: 0, competencies: [], explanation: "Breadth-first at launch is rarely right for AI products where model quality depends on focused training data. This sacrifices depth without acknowledging it." },
              { option_label: 'D', option_text: 'Prioritize the distress alert use case because it has the clearest emotional hook and is easiest to demonstrate in a press launch', quality: 'surface', points: 1, competencies: ['cognitive_empathy'], explanation: 'Press launch appeal is not a strategic criterion. The reasoning is marketing-backward, not product-backward.' },
            ],
          },
        ],
      },
      {
        step: 'win',
        step_nudge: 'What is your crisp, falsifiable bet on the product direction, and how would you know within 90 days if you are right?',
        grading_weight: 0.20,
        step_order: 4,
        questions: [
          {
            question_text: 'Which recommendation best represents a falsifiable hypothesis with a named test?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'creative_execution'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Ship a distress alert beta to 500 dog owners; if 40% respond to an alert within 5 minutes over 30 days, the core loop is real and the clinical partnership track opens', quality: 'best', points: 3, competencies: ['strategic_thinking', 'creative_execution'], explanation: 'Crisp, falsifiable, time-bounded. The 40% response rate tests behavioral intent, not stated preference. Success unlocks the next bet.' },
              { option_label: 'B', option_text: 'Conduct user research with 50 pet owners and 10 vets to validate the problem before building anything', quality: 'good_but_incomplete', points: 2, competencies: ['cognitive_empathy'], explanation: 'Research is fine but not a recommendation. This defers the bet rather than making one, and stated preference research is a weak signal for new behavior.' },
              { option_label: 'C', option_text: 'Present three options to leadership and let them decide based on their risk tolerance', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Presenting options without a recommendation is not a win — it restates the original question without advancing the decision.' },
              { option_label: 'D', option_text: 'Recommend building the consumer app because it has the largest market and the lowest regulatory burden', quality: 'surface', points: 1, competencies: ['strategic_thinking'], explanation: 'A recommendation, but not falsifiable. There is no test or signal that would tell you whether this was right in 90 days.' },
            ],
          },
        ],
      },
    ],
  },

  {
    id: 'pm-openai-002',
    title: 'Future of Music: Structuring a Platform Redesign',
    scenario_role: 'Tech Lead, Consumer AI',
    scenario_context: 'OpenAI is evaluating whether to build a music product. The prompt is broad: design the future of music platform. A working group of engineers and designers needs a structured problem breakdown before any wireframes are drawn.',
    scenario_trigger: 'The working group meets for the first time and realizes no one has defined which music problems are actually worth solving or who the primary user is.',
    scenario_question: 'How do you frame the design space, identify the most valuable user segment, and prioritize the first capability to build?',
    engineer_standout: 'A strong engineer would ask about the latency and quality ceiling of current generative audio models before committing to any real-time interaction features, since the entire product direction depends on what the model can reliably do.',
    paradigm: 'ai_native',
    industry: 'Consumer AI',
    sub_vertical: 'Music Tech',
    difficulty: 'standard',
    estimated_minutes: 20,
    primary_competencies: ['taste', 'strategic_thinking'],
    secondary_competencies: ['creative_execution'],
    frameworks: ['Jobs To Be Done', 'Value Chain Analysis'],
    relevant_roles: ['swe', 'pm', 'ml_eng', 'tech_lead'],
    company_tags: ['OpenAI', 'Spotify', 'Suno', 'Udio'],
    tags: ['consumer-ai', 'product-design', 'music', 'generative-ai'],
    is_published: true,
    is_calibration: false,
    is_premium: false,
    steps: [
      {
        step: 'frame',
        step_nudge: 'Who in the music ecosystem has the most friction today, and is that friction addressable by AI specifically?',
        grading_weight: 0.25,
        step_order: 1,
        questions: [
          {
            question_text: 'Which framing of the "future of music platform" problem is most useful for directing product investment?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'taste'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'The problem is that existing platforms do not use AI at all, so anything AI-powered will be differentiated', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Spotify, YouTube Music, and Apple Music all use AI for recommendations. Differentiation requires a clearer problem than "add AI."' },
              { option_label: 'B', option_text: 'The core tension is that music creation is inaccessible to the 99% who have ideas but not skills, while discovery is broken for the long tail of artists who make music but cannot find audiences', quality: 'best', points: 3, competencies: ['strategic_thinking', 'taste'], explanation: 'Frames two real structural gaps — creation access and discovery — that are both addressable by generative AI in ways incumbents cannot easily replicate.' },
              { option_label: 'C', option_text: 'The problem is that music streaming economics are unfair to artists, and a new platform should fix the royalty model', quality: 'good_but_incomplete', points: 2, competencies: ['domain_expertise'], explanation: "Real problem, but royalty model reform is a business model problem, not a product or AI problem. It would not meaningfully use OpenAI's capabilities." },
              { option_label: 'D', option_text: 'Music listeners want personalization beyond playlist curation, including mood-adaptive and situational recommendations', quality: 'surface', points: 1, competencies: ['cognitive_empathy'], explanation: 'True but Spotify already addresses this. Framing around incremental recommendation improvement undersells the design space.' },
            ],
          },
        ],
      },
      {
        step: 'list',
        step_nudge: 'What are the structurally different models for a music platform, and what does each bet on being true?',
        grading_weight: 0.25,
        step_order: 2,
        questions: [
          {
            question_text: 'Which set of platform directions is most structurally distinct?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'creative_execution'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'A creation tool for non-musicians, a collaboration network for working artists, a personalized listening engine, and an AI licensing marketplace for sync deals', quality: 'best', points: 3, competencies: ['strategic_thinking', 'creative_execution'], explanation: 'Each direction targets a different user (hobbyist, professional, listener, rights holder) and a different value driver. These are genuinely orthogonal bets.' },
              { option_label: 'B', option_text: 'A streaming app, a podcast app, a live events app, and a merchandise app', quality: 'surface', points: 1, competencies: [], explanation: 'These are media categories, not platform directions. None of them is specific to AI or to the problem framed in the previous step.' },
              { option_label: 'C', option_text: 'A text-to-song tool, a melody-to-song tool, a voice-to-song tool, and an image-to-song tool', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'These are input modality variations on the same product. They do not represent structurally distinct strategic bets.' },
              { option_label: 'D', option_text: 'A creation tool for non-musicians, a collaboration network for artists, and a better discovery surface for listeners', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: "Three real and distinct directions, but stops short. Missing the rights and licensing dimension, which is a major source of AI disruption in music." },
            ],
          },
        ],
      },
      {
        step: 'optimize',
        step_nudge: "Given OpenAI's assets — model quality, API distribution, brand — which direction creates the most defensible position, and what does that require you to give up?",
        grading_weight: 0.30,
        step_order: 3,
        questions: [
          {
            question_text: "Which prioritization best uses OpenAI's specific assets while naming an explicit sacrifice?",
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'domain_expertise'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Prioritize the creation tool for non-musicians, optimizing for viral sharing of AI-generated songs — sacrifice audio quality ceilings to ship fast and build a data flywheel', quality: 'best', points: 3, competencies: ['strategic_thinking', 'domain_expertise'], explanation: 'Names the criterion (viral distribution and data flywheel) and the sacrifice (audio quality ceiling). Non-musicians are a massive underserved market and Suno has shown this segment converts.' },
              { option_label: 'B', option_text: 'Start with the professional artist tool to avoid copyright risk and focus on the highest-value users', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Copyright risk avoidance is a real consideration, but this does not name a criterion or an explicit sacrifice. Professionals also require much higher quality bars.' },
              { option_label: 'C', option_text: 'Build all four directions in parallel to maximize coverage before Suno or Udio captures the market', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Parallel expansion without focus rarely beats focused competitors in AI products where model fine-tuning requires concentrated data.' },
              { option_label: 'D', option_text: "Focus on the listening experience because it is the largest user base and the lowest regulatory risk", quality: 'surface', points: 1, competencies: ['cognitive_empathy'], explanation: "Spotify has 600 million users on listening. Competing on the listening surface is the least differentiated use of OpenAI's generative capability." },
            ],
          },
        ],
      },
      {
        step: 'win',
        step_nudge: 'What is the single falsifiable bet you would make, and what metric in 60 days tells you whether the bet was right?',
        grading_weight: 0.20,
        step_order: 4,
        questions: [
          {
            question_text: 'Which recommendation is the most testable within 60 days?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'creative_execution'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Launch a waitlist for a text-to-song tool; if 100K signups arrive in 30 days and 30% share their first generated song publicly, the viral creation loop is real', quality: 'best', points: 3, competencies: ['strategic_thinking', 'creative_execution'], explanation: 'Tests two things simultaneously: demand (signups) and the viral mechanic (sharing). Both are observable without building the full product.' },
              { option_label: 'B', option_text: 'Recommend a six-month research phase to study the competitive landscape before committing to a direction', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Suno and Udio already have millions of users. Six months of research without a bet is not a win — it is a deferral.' },
              { option_label: 'C', option_text: 'Present the four directions to leadership with a scoring matrix and let the team vote on which to pursue', quality: 'surface', points: 1, competencies: [], explanation: 'Voting is not a recommendation. It dissolves accountability without advancing the decision.' },
              { option_label: 'D', option_text: 'Partner with an independent music label on a pilot to test AI-generated music in their catalog pipeline', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'A real and specific bet, but the test is slow (label partnerships take months) and skips the consumer creation hypothesis entirely.' },
            ],
          },
        ],
      },
    ],
  },

  {
    id: 'pm-openai-003',
    title: 'Measuring OpenAI Success: North Star and Fallback',
    scenario_role: 'Staff Engineer, Data Platform',
    scenario_context: 'OpenAI has grown into a multi-product company: ChatGPT, the API, Sora, and the enterprise tier all generate revenue and usage. The data team has been asked to define a single North Star metric and design a fallback measurement protocol for when instrumentation fails.',
    scenario_trigger: 'The head of data tells the team that last quarter\'s instrumentation outage lasted 14 hours and the company had no reliable signal on whether the product was working during that window.',
    scenario_question: 'How do you define a North Star metric for OpenAI and design a fallback measurement system for instrumentation outages?',
    engineer_standout: 'A strong engineer would immediately think about what signals are observable at the infrastructure layer even when application-level telemetry is down: GPU utilization, inference queue depth, and CDN request volume are all proxy signals that do not depend on the product instrumentation stack.',
    paradigm: 'ai_native',
    industry: 'AI Infrastructure',
    sub_vertical: 'AI Platform',
    difficulty: 'advanced',
    estimated_minutes: 25,
    primary_competencies: ['strategic_thinking', 'domain_expertise'],
    secondary_competencies: ['creative_execution'],
    frameworks: ['North Star Framework', 'Metric Trees'],
    relevant_roles: ['swe', 'em', 'pm', 'data_eng', 'ml_eng'],
    company_tags: ['OpenAI', 'Anthropic', 'Google DeepMind'],
    tags: ['metrics', 'north-star', 'instrumentation', 'data-platform', 'ai-platform'],
    is_published: true,
    is_calibration: false,
    is_premium: false,
    steps: [
      {
        step: 'frame',
        step_nudge: 'Before picking a metric, what is the actual value OpenAI delivers — and is it the same across consumer and API products?',
        grading_weight: 0.25,
        step_order: 1,
        questions: [
          {
            question_text: 'What is the most accurate framing of what a North Star metric should capture for OpenAI?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'domain_expertise'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Revenue is the most honest North Star because it reflects whether users value the product enough to pay', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Revenue is a lagging indicator that captures commercial success but not product value. A company can grow revenue while product quality declines.' },
              { option_label: 'B', option_text: 'The North Star should measure AI-delivered value to users, not usage — the upstream question is whether users accomplish something they could not do otherwise', quality: 'best', points: 3, competencies: ['strategic_thinking', 'domain_expertise'], explanation: 'Value-delivered framing is the right upstream anchor. Session count or token consumption metrics reward volume, not outcomes. This framing also accommodates both API and consumer products.' },
              { option_label: 'C', option_text: 'DAU is the standard North Star for consumer products and OpenAI should use it for ChatGPT specifically', quality: 'surface', points: 1, competencies: ['strategic_thinking'], explanation: 'DAU measures presence, not value delivered. A user who opens ChatGPT and leaves unsatisfied counts the same as one who completes a complex task.' },
              { option_label: 'D', option_text: 'OpenAI is too multi-product to have a single North Star — each product needs its own metric and they should be tracked separately', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Multi-product companies still benefit from a unifying North Star. Without one, teams optimize locally and the company cannot measure aggregate progress.' },
            ],
          },
        ],
      },
      {
        step: 'list',
        step_nudge: 'What are the structurally different metric families available, and which can survive an instrumentation outage?',
        grading_weight: 0.25,
        step_order: 2,
        questions: [
          {
            question_text: 'Which set of candidate North Star metrics represents the most distinct measurement approaches?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'domain_expertise'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'DAU, WAU, MAU, and monthly active paying users', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'These are all time-window variations of the same metric family. None captures outcome quality or survives instrumentation failure at the application layer.' },
              { option_label: 'B', option_text: 'Tasks completed per user per week, API tokens generating downstream value, user-reported satisfaction at session end, and session depth (multi-turn rate)', quality: 'best', points: 3, competencies: ['strategic_thinking', 'domain_expertise'], explanation: 'Each captures a different dimension of value: behavioral output, commercial leverage, subjective experience, and engagement depth. These are structurally orthogonal.' },
              { option_label: 'C', option_text: 'Revenue, gross margin, API call volume, and enterprise seat count', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'These are real business metrics but they are all lagging and commercial. None directly measures whether the AI is delivering value to users.' },
              { option_label: 'D', option_text: 'NPS, CSAT, thumbs-up rate, and five-star rating', quality: 'surface', points: 1, competencies: ['cognitive_empathy'], explanation: 'All satisfaction signals — same family, different collection mechanisms. No behavioral or infrastructure signal that could survive a telemetry outage.' },
            ],
          },
        ],
      },
      {
        step: 'optimize',
        step_nudge: 'If you pick a North Star that requires full instrumentation, what does the fallback system look like, and what does it sacrifice?',
        grading_weight: 0.30,
        step_order: 3,
        questions: [
          {
            question_text: 'Which fallback instrumentation design is most defensible during a 14-hour application telemetry outage?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['domain_expertise', 'strategic_thinking'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Use GPU cluster utilization and inference queue depth as a proxy for demand, accepting that it measures capacity consumption rather than user value', quality: 'best', points: 3, competencies: ['domain_expertise', 'strategic_thinking'], explanation: 'GPU utilization and queue depth are observable at the infrastructure layer independently of application telemetry. The sacrifice (capacity vs. value) is named explicitly and is the right tradeoff.' },
              { option_label: 'B', option_text: 'Set up a parallel Datadog pipeline that mirrors all events so a single outage cannot take down all instrumentation', quality: 'good_but_incomplete', points: 2, competencies: ['domain_expertise'], explanation: 'Redundant pipelines reduce outage risk but do not solve the problem if the outage is at the instrumentation source, not the collection pipeline.' },
              { option_label: 'C', option_text: 'Send a user survey during outages and use response rate as a proxy for engagement', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Survey response during an outage is a highly biased signal and has a multi-day lag. This is not a fallback system; it is a gap-filler with poor quality.' },
              { option_label: 'D', option_text: 'Alert the engineering team within 15 minutes of any telemetry gap and treat the missing period as unreported', quality: 'surface', points: 1, competencies: [], explanation: 'Detection is necessary but not sufficient. Without a fallback signal, the company still has no data for the 14-hour window.' },
            ],
          },
        ],
      },
      {
        step: 'win',
        step_nudge: 'What is your specific North Star recommendation for OpenAI, and how would you validate it is the right one within a quarter?',
        grading_weight: 0.20,
        step_order: 4,
        questions: [
          {
            question_text: 'Which recommendation is the most specific and falsifiable?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'creative_execution'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Propose "valuable tasks completed per weekly active user" as the North Star, defined as sessions with three or more turns ending without a correction; validate by correlating it against 90-day retention in cohort analysis', quality: 'best', points: 3, competencies: ['strategic_thinking', 'creative_execution'], explanation: 'Specific definition, testable proxy (multi-turn without correction), and a validation method. This is falsifiable: if retention does not correlate, the metric is wrong.' },
              { option_label: 'B', option_text: 'Recommend a cross-functional working group to align all teams on a shared North Star before committing to any definition', quality: 'surface', points: 1, competencies: [], explanation: 'Working groups are process, not a recommendation. The question asks for a crisp bet, not a governance structure.' },
              { option_label: 'C', option_text: 'Use API token consumption as the North Star because it is measurable, commercial, and already tracked in all production systems', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Token consumption is already tracked and commercially grounded, but it rewards verbosity rather than value. A model that generates more tokens per task scores better regardless of outcome quality.' },
              { option_label: 'D', option_text: 'Recommend weekly active users with a target of 500M by end of year', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'WAU with an arbitrary target is not a recommendation grounded in the value-delivered framing established earlier. It measures presence, not impact.' },
            ],
          },
        ],
      },
    ],
  },

  {
    id: 'pm-openai-004',
    title: 'ChatGPT Product Audit: Proposing Three Improvements',
    scenario_role: 'Founding Engineer, Consumer AI',
    scenario_context: 'ChatGPT has 175 million weekly active users and a growing gap between power users who build workflows around it and casual users who try it once and churn. The product team has been asked to propose improvements that increase engagement depth, not just top-of-funnel signups.',
    scenario_trigger: 'A retention analysis shows that 60% of first-time users have zero sessions in week two, while users who complete more than five sessions in week one retain at 80% through month three.',
    scenario_question: 'Which three product improvements would most effectively move the week-one engagement needle for new ChatGPT users?',
    engineer_standout: 'A strong engineer would note that the week-one retention cliff is likely a "blank cursor problem" — new users do not know what to ask or how to prompt effectively — and that the solution is structural scaffolding, not just better onboarding copy.',
    paradigm: 'ai_native',
    industry: 'Consumer AI',
    sub_vertical: 'AI Assistant',
    difficulty: 'standard',
    estimated_minutes: 20,
    primary_competencies: ['cognitive_empathy', 'creative_execution'],
    secondary_competencies: ['strategic_thinking'],
    frameworks: ['Jobs To Be Done', 'Habit Formation Loop'],
    relevant_roles: ['swe', 'pm', 'ml_eng', 'tech_lead'],
    company_tags: ['OpenAI', 'Google Gemini', 'Anthropic Claude'],
    tags: ['chatgpt', 'retention', 'engagement', 'consumer-ai', 'product-improvement'],
    is_published: true,
    is_calibration: false,
    is_premium: false,
    steps: [
      {
        step: 'frame',
        step_nudge: 'The data shows week-one drop-off is the problem — but what is actually causing it at the moment a new user lands in the product?',
        grading_weight: 0.25,
        step_order: 1,
        questions: [
          {
            question_text: 'What is the most accurate framing of why 60% of new ChatGPT users do not return in week two?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['cognitive_empathy', 'strategic_thinking'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'New users cannot form a clear mental model of what ChatGPT is for, which means the blank prompt box creates anxiety rather than possibility', quality: 'best', points: 3, competencies: ['cognitive_empathy', 'strategic_thinking'], explanation: 'This frames the root cause as a mental model gap, not a feature gap. The blank cursor problem is well-documented in creative and productivity tools and explains the specific week-one pattern.' },
              { option_label: 'B', option_text: 'ChatGPT lacks the features new users expect based on competitor products like Gemini and Copilot', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Feature parity is not the root cause when the product already has more capability than users can utilize. The retention data points to onboarding, not features.' },
              { option_label: 'C', option_text: "The free tier has too many limitations that frustrate new users before they see the product's value", quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Paywall friction is real but secondary. The 60% drop happens before users hit the paywall ceiling — they are not getting far enough to encounter it.' },
              { option_label: 'D', option_text: 'New users try ChatGPT out of curiosity but have no ongoing task that requires them to return', quality: 'surface', points: 1, competencies: ['cognitive_empathy'], explanation: 'This describes the symptom, not the cause. The question is why users who have tasks still do not return, not why curious-but-taskless users churn.' },
            ],
          },
        ],
      },
      {
        step: 'list',
        step_nudge: 'Three improvements — what are the most structurally different interventions that each address a different lever?',
        grading_weight: 0.25,
        step_order: 2,
        questions: [
          {
            question_text: 'Which set of three improvements is most structurally distinct in the levers it pulls?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['creative_execution', 'strategic_thinking'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'A "start with a template" onboarding rail for use-case discovery, a "continue where you left off" persistent memory layer, and a weekly digest of what ChatGPT helped you accomplish', quality: 'best', points: 3, competencies: ['creative_execution', 'strategic_thinking'], explanation: 'Each improvement targets a distinct moment: first session (discovery), return session (continuity), and re-engagement (reflection loop). These are structurally different interventions.' },
              { option_label: 'B', option_text: 'A better onboarding video, a clearer tooltip on the text box, and a "did you know" tip carousel on first login', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'All three are first-session education mechanisms. None creates a pull for session two or beyond, which is where the retention cliff actually occurs.' },
              { option_label: 'C', option_text: 'A mobile app improvement, a voice input feature, and an image generation shortcut', quality: 'surface', points: 1, competencies: ['creative_execution'], explanation: 'These are feature additions with no direct connection to the week-one retention problem identified in the framing step.' },
              { option_label: 'D', option_text: 'A "suggested prompts" panel for discovery, a shared library of community-created prompts, and in-context prompt improvement suggestions', quality: 'good_but_incomplete', points: 2, competencies: ['creative_execution', 'cognitive_empathy'], explanation: 'All three address prompt scaffolding, which is the right problem, but they are variations of the same intervention rather than structurally distinct levers.' },
            ],
          },
        ],
      },
      {
        step: 'optimize',
        step_nudge: 'If you could only ship one of the three improvements first, which criterion tells you which one to pick, and what does deprioritizing the others cost?',
        grading_weight: 0.30,
        step_order: 3,
        questions: [
          {
            question_text: 'Which prioritization argument is most specific about the criterion and the cost of the choice?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'creative_execution'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Ship the template onboarding rail first, optimizing for first-session task completion rate — sacrifice the re-engagement loop and continuity layer, which matter more for month-two retention than week-one', quality: 'best', points: 3, competencies: ['strategic_thinking', 'creative_execution'], explanation: 'Names the criterion (first-session task completion), the sacrifice (month-two levers), and correctly scopes the tradeoff to the week-one problem the data identified.' },
              { option_label: 'B', option_text: 'Ship the memory layer first because memory is the most technically difficult and should be de-risked earliest', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Technical complexity is a build sequencing consideration, not a product prioritization criterion. The question is which improvement has the most impact on the retention metric.' },
              { option_label: 'C', option_text: 'Ship all three simultaneously since they are interdependent and will not work as well in isolation', quality: 'surface', points: 1, competencies: [], explanation: 'These improvements are not interdependent — each addresses a distinct session moment. Simultaneous shipping avoids the prioritization question rather than answering it.' },
              { option_label: 'D', option_text: 'Prioritize the weekly digest because it is the cheapest to build and will test re-engagement signal quickly', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Build cost and speed are real inputs, but the framing step identified week-one first-session drop-off as the root cause, which the digest does not address.' },
            ],
          },
        ],
      },
      {
        step: 'win',
        step_nudge: 'What is the falsifiable test you would run, and what does success look like in 30 days?',
        grading_weight: 0.20,
        step_order: 4,
        questions: [
          {
            question_text: 'Which recommendation gives you the clearest signal on whether the improvement worked?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'creative_execution'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'A/B test the template onboarding rail on 10% of new signups; success is week-two return rate rising from 40% to 55% within 30 days', quality: 'best', points: 3, competencies: ['strategic_thinking', 'creative_execution'], explanation: 'Named test, named metric, named threshold, named time window. This is falsifiable: if week-two return rate does not move, the hypothesis is wrong.' },
              { option_label: 'B', option_text: 'Ship to 100% of users and monitor week-two DAU over 60 days', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'DAU is too aggregate to isolate the onboarding effect. Without a control group, you cannot attribute any change to the improvement.' },
              { option_label: 'C', option_text: 'Run a qualitative interview study with 20 new users to understand their first-session experience', quality: 'surface', points: 1, competencies: ['cognitive_empathy'], explanation: 'Qualitative interviews produce directional insight, not a falsifiable outcome. Twenty users cannot measure a 15-point retention rate shift.' },
              { option_label: 'D', option_text: 'Track NPS change among new users in the first 30 days post-launch', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'NPS is too slow and too noisy for a 30-day retention test. It also lags behavioral change and conflates many variables.' },
            ],
          },
        ],
      },
    ],
  },

  {
    id: 'pm-openai-005',
    title: 'ChatGPT Image Creation: 2x Growth with 3 Engineers',
    scenario_role: 'Tech Lead, Growth',
    scenario_context: 'ChatGPT image creation has 175 million weekly active users. Leadership has set a target of 350 million weekly active users in 3 months. The growth team has been allocated 3 engineers for this sprint.',
    scenario_trigger: 'The team lead asks for a focused strategy — not a wishlist, but a concrete three-engineer plan that could realistically double a product used by 175 million people.',
    scenario_question: 'How do you prioritize and sequence growth investments to double weekly active users of ChatGPT image creation in 3 months with 3 engineers?',
    engineer_standout: 'A strong engineer would immediately ask whether the constraint is top-of-funnel awareness or bottom-of-funnel activation, because the right three engineers depend entirely on which problem is bigger. Misdiagnosing this wastes all three.',
    paradigm: 'ai_native',
    industry: 'Consumer AI',
    sub_vertical: 'AI Image Generation',
    difficulty: 'advanced',
    estimated_minutes: 25,
    primary_competencies: ['strategic_thinking', 'creative_execution'],
    secondary_competencies: ['domain_expertise'],
    frameworks: ['Growth Loops', 'ICE Prioritization'],
    relevant_roles: ['swe', 'pm', 'tech_lead', 'em'],
    company_tags: ['OpenAI', 'Midjourney', 'Adobe Firefly', 'Canva'],
    tags: ['growth', 'chatgpt', 'image-generation', 'constraint-based', 'activation'],
    is_published: true,
    is_calibration: false,
    is_premium: false,
    steps: [
      {
        step: 'frame',
        step_nudge: 'Before picking a strategy, which part of the funnel is actually broken — and can 3 engineers meaningfully move it?',
        grading_weight: 0.25,
        step_order: 1,
        questions: [
          {
            question_text: 'What is the most important question to answer before allocating the 3 engineers?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'domain_expertise'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'What percentage of ChatGPT weekly active users have never tried image creation, and what is their drop-off point when they do try?', quality: 'best', points: 3, competencies: ['strategic_thinking', 'domain_expertise'], explanation: 'This question separates the awareness problem from the activation problem. The answer determines whether 3 engineers should build discovery surfaces or improve the first-use experience.' },
              { option_label: 'B', option_text: 'Which geographic markets are growing fastest and should receive localized campaigns?', quality: 'surface', points: 1, competencies: ['strategic_thinking'], explanation: 'Geographic analysis is a targeting question, not a prioritization question. With 3 engineers, localizing content is not the right first move.' },
              { option_label: 'C', option_text: 'What features do Midjourney and Adobe Firefly have that ChatGPT image creation lacks?', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Feature parity analysis with competitors does not tell you which feature unlocks the next 175 million users. It produces a backlog, not a growth strategy.' },
              { option_label: 'D', option_text: 'How much does it cost to acquire a new image creation user through paid channels?', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'CAC is a useful input but 3 engineers cannot run paid acquisition. The question is about product-led growth, and CAC data alone does not point to a specific engineering investment.' },
            ],
          },
        ],
      },
      {
        step: 'list',
        step_nudge: 'What are the structurally different growth bets available to a team of 3, each targeting a different part of the funnel?',
        grading_weight: 0.25,
        step_order: 2,
        questions: [
          {
            question_text: 'Which set of growth bets is most structurally distinct given a 3-engineer constraint?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['creative_execution', 'strategic_thinking'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'A viral sharing loop (users share images with attribution), a discovery surface inside ChatGPT (suggested image prompts in conversation), and a social proof trigger (show trending images in the empty state)', quality: 'best', points: 3, competencies: ['creative_execution', 'strategic_thinking'], explanation: 'Each bet targets a different growth mechanism: viral distribution, in-product activation, and first-session conversion. These are structurally orthogonal and all achievable with one engineer each.' },
              { option_label: 'B', option_text: 'Better image quality, faster generation speed, and more style options', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Quality and speed improvements may retain existing users but are unlikely to double WAU in 3 months. These are optimization plays, not growth plays.' },
              { option_label: 'C', option_text: 'A mobile-optimized UI, an API for third-party developers, and a plugin for design tools like Figma', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'These expand distribution channels, which is a real growth lever. But an API and a Figma plugin both require significant integration work that exceeds a 3-engineer 3-month budget.' },
              { option_label: 'D', option_text: 'A referral program, an ambassador program, and a social media partnership campaign', quality: 'surface', points: 1, competencies: ['creative_execution'], explanation: 'Referral and partnership programs require marketing and partnership resources, not engineering. These are not 3-engineer bets.' },
            ],
          },
        ],
      },
      {
        step: 'optimize',
        step_nudge: 'You have one engineer per bet — how do you sequence them, and what does the 3-month constraint force you to sacrifice?',
        grading_weight: 0.30,
        step_order: 3,
        questions: [
          {
            question_text: 'Which sequencing argument is most explicit about the criterion and the sacrifice?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'creative_execution'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Ship the viral sharing loop first, optimizing for compounding growth over 90 days — sacrifice immediate activation gains to build a distribution mechanism that works without continued engineering investment', quality: 'best', points: 3, competencies: ['strategic_thinking', 'creative_execution'], explanation: 'Names the criterion (compounding growth), the sacrifice (near-term activation), and the reasoning (virality compounds while activation improvements are one-time). Correct for a 90-day window.' },
              { option_label: 'B', option_text: 'Sequence all three bets in parallel so all three engineers are unblocked from day one', quality: 'good_but_incomplete', points: 2, competencies: ['creative_execution'], explanation: 'Parallel execution is reasonable but does not name a criterion for sequencing or acknowledge what is being sacrificed. It avoids the prioritization question.' },
              { option_label: 'C', option_text: 'Focus all 3 engineers on the fastest bet to ship a win in the first 30 days and build momentum', quality: 'surface', points: 1, competencies: [], explanation: 'Speed-to-ship is not a growth criterion. A fast win that does not compound does not get to 350M WAU by month three.' },
              { option_label: 'D', option_text: 'Run A/B tests on each bet before committing resources to ensure the highest-impact initiative gets the most engineering time', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'With 3 engineers and 3 months, A/B testing before building is not sequencing — it is stalling. By the time tests run, the window has closed.' },
            ],
          },
        ],
      },
      {
        step: 'win',
        step_nudge: 'What is the single most important bet you are making, and how do you know by day 30 whether it is working?',
        grading_weight: 0.20,
        step_order: 4,
        questions: [
          {
            question_text: 'Which final recommendation is most specific about the bet and the 30-day signal?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'creative_execution'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Launch the viral sharing loop with a watermarked attribution tag; if 15% of new image creation sessions originate from shared images by day 30, the viral coefficient is sufficient to reach 350M by month 3', quality: 'best', points: 3, competencies: ['strategic_thinking', 'creative_execution'], explanation: 'Names the mechanic (watermarked attribution), the metric (15% of sessions from shares), and the threshold that unlocks the second-order growth projection. Falsifiable.' },
              { option_label: 'B', option_text: 'Track WAU weekly and adjust strategy if the growth rate falls below linear trajectory toward 350M', quality: 'surface', points: 1, competencies: ['strategic_thinking'], explanation: 'WAU tracking is hygiene, not a recommendation. "Adjust strategy" is not a plan — it defers the decision to a future moment.' },
              { option_label: 'C', option_text: 'Report progress to leadership at the 30-day mark and request additional engineers if the trajectory is below plan', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Requesting more resources is not a growth strategy. The question is about making the most of the 3-engineer constraint, not escalating past it.' },
              { option_label: 'D', option_text: 'Set a 60-day checkpoint to evaluate whether the combined three bets have added 50M WAU', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'A 60-day WAU checkpoint is a reasonable milestone but it is a lagging measurement, not an early signal. Day 30 proxy metrics would catch problems earlier.' },
            ],
          },
        ],
      },
    ],
  },

  {
    id: 'pm-openai-006',
    title: 'Launching a New ChatGPT Model: Go-to-Market Strategy',
    scenario_role: 'Tech Lead, Platform',
    scenario_context: 'OpenAI is preparing to launch a new ChatGPT model with significantly improved reasoning and a new multimodal capability. The model is ready for release, but the go-to-market strategy has not been finalized. Previous launches have created demand spikes that overwhelmed infrastructure.',
    scenario_trigger: 'The launch is scheduled for six weeks from now. The platform team needs a go-to-market plan that manages demand, maximizes adoption, and protects the API business during the transition.',
    scenario_question: 'How do you design the go-to-market strategy for a new ChatGPT model release that balances consumer excitement with infrastructure stability and API continuity?',
    engineer_standout: 'A strong engineer would immediately flag that a model launch is not just a product event — it is an infrastructure event. The biggest risk is not low adoption but an adoption spike that degrades quality for existing API customers and triggers a trust incident.',
    paradigm: 'ai_native',
    industry: 'AI Platform',
    sub_vertical: 'Foundation Models',
    difficulty: 'advanced',
    estimated_minutes: 25,
    primary_competencies: ['strategic_thinking', 'domain_expertise'],
    secondary_competencies: ['creative_execution'],
    frameworks: ['Go-to-Market Framework', 'Staged Rollout'],
    relevant_roles: ['swe', 'em', 'pm', 'tech_lead', 'ml_eng'],
    company_tags: ['OpenAI', 'Anthropic', 'Google DeepMind', 'AWS'],
    tags: ['go-to-market', 'model-launch', 'infrastructure', 'api', 'staged-rollout'],
    is_published: true,
    is_calibration: false,
    is_premium: false,
    steps: [
      {
        step: 'frame',
        step_nudge: 'A model launch is different from a feature launch — what is the unique risk profile that shapes the entire strategy?',
        grading_weight: 0.25,
        step_order: 1,
        questions: [
          {
            question_text: 'What is the most important constraint to frame the go-to-market strategy around?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['domain_expertise', 'strategic_thinking'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'The primary constraint is demand management: a successful launch creates an adoption spike that the infrastructure must absorb without degrading existing API customer SLAs', quality: 'best', points: 3, competencies: ['domain_expertise', 'strategic_thinking'], explanation: 'This frames the real tension: success is dangerous. The biggest GTM risk is not low adoption but an adoption spike that breaks existing API customers who pay for reliability.' },
              { option_label: 'B', option_text: 'The primary constraint is media coverage: without major press, the launch will not reach the consumer audience that drives ChatGPT growth', quality: 'surface', points: 1, competencies: ['creative_execution'], explanation: 'Media coverage is a consideration but not the primary constraint for a ChatGPT model launch. The brand already commands outsized media attention — the risk is infrastructure, not awareness.' },
              { option_label: 'C', option_text: 'The primary constraint is API backward compatibility: enterprise customers need time to migrate their integrations before the old model is deprecated', quality: 'good_but_incomplete', points: 2, competencies: ['domain_expertise'], explanation: 'API migration is a real concern but it is a post-launch operational issue, not the primary framing constraint for the GTM strategy. Demand management comes first.' },
              { option_label: 'D', option_text: 'The primary constraint is pricing: the new model must be priced to maintain revenue while staying competitive with Anthropic Claude and Gemini', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Pricing is a commercial decision that follows the GTM strategy, not one that shapes it. The infrastructure risk is the primary constraint that determines rollout design.' },
            ],
          },
        ],
      },
      {
        step: 'list',
        step_nudge: 'What are the structurally different rollout approaches, and what does each assume about the infrastructure and the audience?',
        grading_weight: 0.25,
        step_order: 2,
        questions: [
          {
            question_text: 'Which set of rollout approaches is most structurally distinct?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'domain_expertise'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'A global launch to all users simultaneously, a phased geographic rollout starting with the US, and a phased geographic rollout starting with Europe', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'These are geographic variations on the same rollout model. They are not structurally distinct approaches to balancing demand and quality.' },
              { option_label: 'B', option_text: 'A research preview to API developers only, a Plus-subscriber early access period, a staged percentage rollout to all ChatGPT users, and a simultaneous full launch', quality: 'best', points: 3, competencies: ['strategic_thinking', 'domain_expertise'], explanation: 'Each approach targets a different audience with different quality expectations and different risk profiles. The sequence is also naturally additive: each stage validates the next.' },
              { option_label: 'C', option_text: 'A waitlist launch, a closed beta, and an open beta before full release', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Three real stages but they are all consumer-facing variations. Missing the API developer track, which has different SLA requirements and is the highest-revenue segment.' },
              { option_label: 'D', option_text: 'A big-bang launch with a major press event, then immediate global availability to maximize attention', quality: 'surface', points: 1, competencies: ['creative_execution'], explanation: 'This is a single approach, not a set of distinct options. It also ignores the infrastructure risk framing from the previous step.' },
            ],
          },
        ],
      },
      {
        step: 'optimize',
        step_nudge: 'Given the six-week timeline and the infrastructure constraint, which rollout approach do you commit to, and what do you explicitly accept as the cost?',
        grading_weight: 0.30,
        step_order: 3,
        questions: [
          {
            question_text: 'Which approach best names the optimization criterion and the explicit sacrifice?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'domain_expertise'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Commit to a two-week API developer preview followed by a percentage-gated consumer rollout — optimize for API SLA protection at the cost of consumer launch excitement and press timing control', quality: 'best', points: 3, competencies: ['strategic_thinking', 'domain_expertise'], explanation: 'Names the criterion (API SLA protection), the sacrifice (press timing and consumer excitement), and a specific mechanism (two-week developer preview plus gated rollout). Grounded in the infrastructure risk framing.' },
              { option_label: 'B', option_text: 'Optimize for consumer virality with a full launch and accept that some API degradation is tolerable for 48 hours', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Explicitly accepting API degradation violates the SLA commitments that enterprise customers pay for. This is a customer trust incident, not a tolerable tradeoff.' },
              { option_label: 'C', option_text: 'Invest the six weeks in infrastructure scaling so the full launch can happen without any rollout gating', quality: 'good_but_incomplete', points: 2, competencies: ['domain_expertise'], explanation: 'Infrastructure scaling is necessary but insufficient. Six weeks is not enough time to scale infrastructure for an unknown demand spike. Gating is still required.' },
              { option_label: 'D', option_text: 'Delay the launch until infrastructure is fully ready rather than risk a degraded experience', quality: 'surface', points: 1, competencies: [], explanation: 'Delay avoids the problem without solving it. Infrastructure is never perfectly ready for a major launch — the question is how to manage the risk, not whether to launch.' },
            ],
          },
        ],
      },
      {
        step: 'win',
        step_nudge: 'What is the crisp launch decision you would make, and what is the signal by day 14 that tells you the rollout is succeeding?',
        grading_weight: 0.20,
        step_order: 4,
        questions: [
          {
            question_text: 'Which recommendation is most specific about the launch decision and the 14-day signal?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'creative_execution'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Launch to API developers in week one; gate consumer rollout at 5% per day starting week two; success signal is API p99 latency remaining below 2 seconds through 50% consumer rollout', quality: 'best', points: 3, competencies: ['strategic_thinking', 'creative_execution'], explanation: 'Specific rollout rate, specific success metric (p99 latency), specific threshold, and a natural gate condition. This is falsifiable and actionable.' },
              { option_label: 'B', option_text: 'Monitor user satisfaction scores daily during the rollout and pause if satisfaction drops below baseline', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'A pause condition is good practice but satisfaction scores lag performance issues by days. Infrastructure metrics like latency and error rate are faster signals.' },
              { option_label: 'C', option_text: 'Report rollout progress weekly to leadership and adjust pacing based on their feedback', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Weekly reporting to leadership is not a success signal. By the time leadership reviews weekly data, an infrastructure incident has already affected customers.' },
              { option_label: 'D', option_text: 'Set a 30-day target of 50% of ChatGPT users on the new model and evaluate at that milestone', quality: 'surface', points: 1, competencies: ['strategic_thinking'], explanation: 'A 30-day milestone is too late to catch infrastructure problems in the first 14 days of rollout. Early signals are needed before scale exposure.' },
            ],
          },
        ],
      },
    ],
  },

  {
    id: 'pm-openai-007',
    title: 'Brain-Scan Belief Ranking: Bringing a Neurotech Product to Market',
    scenario_role: 'Founding Engineer, Neurotech Startup',
    scenario_context: 'A startup has built a model that scans brain activity and ranks a person\'s beliefs and perspectives by conviction strength. The technology works in lab conditions. The founders need a go-to-market plan that is both commercially viable and does not trigger an immediate regulatory or public backlash.',
    scenario_trigger: 'An investor has given a 90-day deadline to present a viable GTM plan or the funding round closes without a term sheet.',
    scenario_question: 'How do you bring a brain-scan belief-ranking product to market in a way that creates real commercial value while managing the ethical and regulatory risks of this specific capability?',
    engineer_standout: 'A strong engineer would immediately think about the consent architecture — specifically, who controls the scan data, who sees the output, and what the system does with ranked beliefs. The entire regulatory exposure depends on these three technical decisions.',
    paradigm: 'ai_native',
    industry: 'Neurotech',
    sub_vertical: 'Cognitive AI',
    difficulty: 'advanced',
    estimated_minutes: 25,
    primary_competencies: ['strategic_thinking', 'domain_expertise'],
    secondary_competencies: ['motivation_theory'],
    frameworks: ['Go-to-Market Framework', 'Ethical AI Framework'],
    relevant_roles: ['swe', 'pm', 'ml_eng', 'tech_lead'],
    company_tags: ['Neuralink', 'Emotiv', 'Kernel'],
    tags: ['neurotech', 'go-to-market', 'ethics', 'regulatory', 'ai-native'],
    is_published: true,
    is_calibration: false,
    is_premium: false,
    steps: [
      {
        step: 'frame',
        step_nudge: 'What is the actual risk that makes this product different from any other AI product, and which stakeholder is most exposed to it?',
        grading_weight: 0.25,
        step_order: 1,
        questions: [
          {
            question_text: 'What is the most accurate framing of the central challenge for bringing this product to market?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'domain_expertise'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'The product creates a new class of personal data — ranked internal beliefs — that has no existing legal framework, which means any deployment creates regulatory exposure for both the company and the customer deploying it', quality: 'best', points: 3, competencies: ['strategic_thinking', 'domain_expertise'], explanation: 'This frames the root structural challenge: ranked belief data is legally novel. Customers who deploy it inherit unknown regulatory liability, which is the biggest barrier to commercial adoption.' },
              { option_label: 'B', option_text: 'The product is ethically controversial and will generate negative press that damages the brand before it can build a user base', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Press risk is real but secondary. The more fundamental barrier is that potential customers cannot evaluate their legal exposure before deploying, which blocks procurement entirely.' },
              { option_label: 'C', option_text: 'The technology is not proven at scale, so the go-to-market should wait until lab conditions can be replicated in real environments', quality: 'surface', points: 1, competencies: ['domain_expertise'], explanation: 'Technology scale-up is an engineering problem, not the primary GTM challenge. Many successful products launch from lab-validated tech into controlled environments.' },
              { option_label: 'D', option_text: 'Consumer privacy concerns will limit adoption, so the company should build a privacy-preserving architecture before launching', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Privacy architecture is part of the answer but it does not frame the problem. "Build privacy features first" is a solution disguised as a framing, and it skips the regulatory novelty issue.' },
            ],
          },
        ],
      },
      {
        step: 'list',
        step_nudge: 'What are the structurally distinct market entry points, each with a different regulatory profile and value proposition?',
        grading_weight: 0.25,
        step_order: 2,
        questions: [
          {
            question_text: 'Which set of market entry points is most structurally distinct?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'creative_execution'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Individual consumer self-insight app, employer screening tool, court-ordered belief assessment, and political campaign targeting', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Employer screening, court-ordered assessments, and political targeting are the most legally and ethically exposed use cases. Listing them as options without flagging this is a strategic error.' },
              { option_label: 'B', option_text: 'A self-insight tool (individual consents, only individual sees output), a clinical research API (IRB-governed, academic use only), a team dynamics tool (anonymous aggregate only), and a coaching platform (consent-first, coach facilitates)', quality: 'best', points: 3, competencies: ['strategic_thinking', 'creative_execution'], explanation: 'Each market entry has a distinct consent model, regulatory pathway, and value proposition. The individual-consent and IRB-governed tracks are the only commercially viable starting points given the regulatory novelty.' },
              { option_label: 'C', option_text: 'A B2C app, a B2B enterprise product, and a government contract', quality: 'surface', points: 1, competencies: ['strategic_thinking'], explanation: 'These are go-to-market channels, not market entry points with distinct value propositions. They do not account for the consent architecture that determines regulatory exposure.' },
              { option_label: 'D', option_text: 'A clinical trial platform, an HR tool, and a consumer wellness app', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Three real options but the HR tool carries significant employment discrimination liability. Two of the three are defensible; one requires much more careful framing.' },
            ],
          },
        ],
      },
      {
        step: 'optimize',
        step_nudge: 'Given the 90-day investor deadline and the legal novelty, which market entry do you commit to first, and what does that force you to sacrifice?',
        grading_weight: 0.30,
        step_order: 3,
        questions: [
          {
            question_text: 'Which prioritization argument names the optimization criterion and the explicit sacrifice?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'domain_expertise'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Start with the clinical research API under IRB governance — optimize for regulatory defensibility and academic credibility, sacrificing near-term revenue to build the legal precedent that makes every other market entry possible', quality: 'best', points: 3, competencies: ['strategic_thinking', 'domain_expertise'], explanation: 'Names the criterion (regulatory defensibility), the sacrifice (near-term revenue), and the strategic logic (IRB precedent unlocks other markets). Clinical research is the only track that produces publishable data and regulatory cover simultaneously.' },
              { option_label: 'B', option_text: 'Launch the consumer self-insight app first because it is the fastest path to revenue and individual consent removes employer liability', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Consumer consent removes employer liability but does not address the regulatory novelty of ranked belief data. A consumer launch without published clinical validation creates a fragile legal position.' },
              { option_label: 'C', option_text: 'Build all four products simultaneously to demonstrate market breadth to the investor within 90 days', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Building four products in 90 days with a startup team produces four inadequate products. Investor confidence comes from depth of execution in one market, not breadth of promise across four.' },
              { option_label: 'D', option_text: 'Engage a law firm to map the regulatory landscape before committing to any market entry', quality: 'surface', points: 1, competencies: [], explanation: 'Legal review is necessary but it is not a GTM strategy. Without a committed market entry, the 90-day deadline passes with no commercial progress.' },
            ],
          },
        ],
      },
      {
        step: 'win',
        step_nudge: 'What is the crisp recommendation to the investor, and what is the specific evidence by day 90 that validates the commercial thesis?',
        grading_weight: 0.20,
        step_order: 4,
        questions: [
          {
            question_text: 'Which recommendation is most specific and falsifiable within the 90-day investor window?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'creative_execution'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Sign three university research partnerships under IRB protocol by day 90; if two generate publishable study designs, the clinical API has a defensible legal position and the consumer market becomes accessible in year two', quality: 'best', points: 3, competencies: ['strategic_thinking', 'creative_execution'], explanation: 'Specific milestone (three partnerships), specific success signal (two publishable study designs), and a clear pathway to the next market. Falsifiable and time-bound.' },
              { option_label: 'B', option_text: 'Publish an ethics white paper and a technical brief to establish thought leadership before commercial launch', quality: 'surface', points: 1, competencies: [], explanation: 'Thought leadership does not produce commercial evidence for an investor. It is marketing, not a GTM milestone.' },
              { option_label: 'C', option_text: 'Present a detailed financial model showing path to $10M ARR in year two based on clinical API pricing', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'A financial model is a planning artifact, not commercial evidence. Investors in this space need proof of regulatory traction, not revenue projections from an unvalidated model.' },
              { option_label: 'D', option_text: 'Recommend pivoting to a less controversial application of the technology to reduce regulatory risk', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Pivoting away from the core technology is not a GTM strategy — it is abandoning the product. The investor funded the belief-ranking capability specifically.' },
            ],
          },
        ],
      },
    ],
  },
]
