export const CHALLENGES = [
  {
    id: 'pm-doordash-001',
    title: 'Merchant Retention: The Forgotten Side of DoorDash',
    scenario_role: 'Product Manager, Marketplace Growth',
    scenario_context: 'Merchant churn on DoorDash has ticked up 8 percentage points over the past two quarters. Internal data shows that the bottom 30% of merchants by order volume are churning at 3x the rate of top performers. Customer success flags that these merchants feel invisible to the platform.',
    scenario_trigger: 'A quarterly business review reveals that merchant churn is eroding GMV by $40M annually, with new merchant acquisition costs outpacing the losses only barely.',
    scenario_question: 'What feature or set of features would most effectively reduce churn for low-volume merchants on DoorDash?',
    engineer_standout: 'A strong engineer would recognize that merchant retention is partly an information problem: low-volume merchants lack visibility into why they underperform relative to similar restaurants, and a diagnostic layer would be more durable than promotional fixes.',
    paradigm: 'traditional',
    industry: 'Marketplace',
    sub_vertical: 'Food Delivery',
    difficulty: 'standard',
    estimated_minutes: 20,
    primary_competencies: ['cognitive_empathy', 'strategic_thinking'],
    secondary_competencies: ['creative_execution'],
    frameworks: ['Jobs To Be Done', 'North Star Framework'],
    relevant_roles: ['pm', 'swe', 'tech_lead'],
    company_tags: ['DoorDash', 'Uber Eats', 'Grubhub'],
    tags: ['marketplace', 'merchant', 'retention', 'three-sided', 'doordash'],
    is_published: true,
    is_calibration: false,
    is_premium: false,
    steps: [
      {
        step: 'frame',
        step_nudge: 'What is the actual job these low-volume merchants are hiring DoorDash to do, and where does DoorDash fail them?',
        grading_weight: 0.25,
        step_order: 1,
        questions: [
          {
            question_text: 'What is the most accurate framing of why low-volume merchants churn from DoorDash?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['cognitive_empathy', 'strategic_thinking'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Merchant fees are too high relative to revenue generated, making DoorDash unprofitable for small restaurants', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Fee sensitivity is real, but high-fee restaurants with strong order volume stay. The root cause is low volume, not high fees per se.' },
              { option_label: 'B', option_text: 'Low-volume merchants lack visibility into why they underperform peers, so they cannot improve and eventually give up', quality: 'best', points: 3, competencies: ['cognitive_empathy', 'strategic_thinking'], explanation: 'Information asymmetry is the upstream cause. Merchants who cannot diagnose their own underperformance have no path to improvement, making churn inevitable.' },
              { option_label: 'C', option_text: 'DoorDash prioritizes high-rated restaurants in algorithmic ranking, creating a winner-takes-most dynamic that squeezes smaller players', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Algorithmic ranking bias is a contributing factor but not the root cause of the churn pattern. Fixing ranking without improving merchant capability would not resolve the underlying problem.' },
              { option_label: 'D', option_text: 'Merchant onboarding is too complex and many restaurants never set up their menus or photos correctly', quality: 'surface', points: 1, competencies: ['cognitive_empathy'], explanation: 'Onboarding friction affects new merchants but does not explain why merchants who have been on the platform for multiple quarters are churning.' },
            ],
          },
        ],
      },
      {
        step: 'list',
        step_nudge: 'What are the structurally distinct types of interventions available, and what does each one address?',
        grading_weight: 0.25,
        step_order: 2,
        questions: [
          {
            question_text: 'Which set of retention levers is most strategically distinct and addresses different root causes of merchant churn?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'creative_execution'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Discounted commission for first 6 months, promotional placement in search results, and a $200 credit for advertising', quality: 'surface', points: 1, competencies: [], explanation: 'All three are promotional subsidies that address cost, not capability. They do not fix the information asymmetry and create subsidy dependency.' },
              { option_label: 'B', option_text: 'Merchant performance dashboard (diagnostic), personalized playbook with peer benchmarks (prescriptive), and a dedicated success tier for at-risk merchants (relational)', quality: 'best', points: 3, competencies: ['strategic_thinking', 'creative_execution'], explanation: 'These address three distinct failure modes: lack of visibility, lack of direction, and lack of relationship. Each layer targets a different reason merchants disengage.' },
              { option_label: 'C', option_text: 'Better menu photo tooling, automated hours management, and a direct messaging channel to dashers', quality: 'good_but_incomplete', points: 2, competencies: ['cognitive_empathy'], explanation: 'These are valid operational improvements but all address the same layer: menu and operational quality. They are not structurally distinct interventions.' },
              { option_label: 'D', option_text: 'In-app merchant community forum, monthly webinars on best practices, and a certification badge program', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Community and education are low-urgency investments that do not address why merchants are leaving within their first year on the platform.' },
            ],
          },
        ],
      },
      {
        step: 'optimize',
        step_nudge: 'Given limited engineering capacity, which single feature would move the needle most on merchant retention, and what would you sacrifice?',
        grading_weight: 0.30,
        step_order: 3,
        questions: [
          {
            question_text: 'If you could ship only one merchant retention feature in Q3, which would you prioritize?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'cognitive_empathy'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'A merchant performance dashboard showing orders, average basket size, and customer reorder rate benchmarked against similar nearby restaurants', quality: 'best', points: 3, competencies: ['strategic_thinking', 'cognitive_empathy'], explanation: 'Peer benchmarking converts abstract underperformance into actionable gaps. Merchants who see that similar restaurants have 40% higher reorder rates know exactly what to work on. This is durable: it compounds as data accumulates.' },
              { option_label: 'B', option_text: 'A 30-day promotional boost for any merchant whose order volume drops below their 90-day average', quality: 'surface', points: 1, competencies: [], explanation: 'Promotional boosts create short-term volume spikes without building merchant capability. Once the boost ends, the churn risk returns unchanged.' },
              { option_label: 'C', option_text: 'A dedicated merchant success manager tier for the bottom 20% of merchants by revenue', quality: 'good_but_incomplete', points: 2, competencies: ['cognitive_empathy'], explanation: 'High-touch support is effective but does not scale. It addresses the symptom for a subset of merchants while leaving the systemic information problem in place.' },
              { option_label: 'D', option_text: 'An automated re-engagement email sequence triggered when merchant order volume declines for two consecutive weeks', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Re-engagement emails identify the problem too late and provide no actionable guidance. Merchants who are already disengaging need a reason to act, not a notification that they are struggling.' },
            ],
          },
        ],
      },
      {
        step: 'win',
        step_nudge: 'How do you measure whether this feature is actually improving merchant retention versus just improving merchant satisfaction scores?',
        grading_weight: 0.20,
        step_order: 4,
        questions: [
          {
            question_text: 'What is the right success metric for the merchant retention feature you shipped?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: '12-month merchant retention rate for the bottom-30% cohort that accessed the dashboard at least twice', quality: 'best', points: 3, competencies: ['strategic_thinking'], explanation: 'Retention rate in the exact cohort you are targeting, with a usage gate to filter out merchants who never engaged, is the cleanest test of whether the feature works.' },
              { option_label: 'B', option_text: 'Merchant NPS score improvement 60 days post-launch', quality: 'surface', points: 1, competencies: [], explanation: 'NPS measures satisfaction, not retention. A merchant can give you a 9 and still churn if their order volume stays low.' },
              { option_label: 'C', option_text: 'Dashboard feature adoption rate (% of low-volume merchants who opened it at least once)', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Adoption is a leading indicator of engagement but not a direct measure of whether churn improved. A merchant can open the dashboard and still leave.' },
              { option_label: 'D', option_text: 'Average order volume growth for all DoorDash merchants in the quarter after launch', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Platform-wide order volume conflates too many signals. A strong Q4 for restaurant demand would show the same number regardless of feature impact.' },
            ],
          },
        ],
      },
    ],
  },

  {
    id: 'pm-doordash-002',
    title: 'Marketplace Health: Metrics Across Three Sides of DoorDash',
    scenario_role: 'Product Lead, Marketplace Intelligence',
    scenario_context: 'DoorDash operates a three-sided marketplace: consumers order food, Dashers deliver it, and merchants prepare it. Each side has distinct motivations and can be optimized in ways that harm the other two. The growth team has been focused primarily on consumer metrics for the past year.',
    scenario_trigger: 'A board review flags that consumer order frequency is up 12% YoY, but Dasher utilization has dropped and merchant reorder rates have stagnated. The board asks whether the marketplace is actually getting healthier.',
    scenario_question: 'How would you design a success measurement framework that captures the health of all three sides of the DoorDash marketplace in a single view?',
    engineer_standout: 'A strong engineer would recognize that a three-sided marketplace requires a constraint graph, not three parallel dashboards. Optimizing one side without monitoring feedback effects on the other two produces local maxima that hurt the overall system.',
    paradigm: 'traditional',
    industry: 'Marketplace',
    sub_vertical: 'Food Delivery',
    difficulty: 'advanced',
    estimated_minutes: 25,
    primary_competencies: ['strategic_thinking', 'domain_expertise'],
    secondary_competencies: ['creative_execution'],
    frameworks: ['North Star Framework', 'System Thinking'],
    relevant_roles: ['pm', 'data_eng', 'tech_lead'],
    company_tags: ['DoorDash', 'Lyft', 'Airbnb'],
    tags: ['metrics', 'marketplace', 'three-sided', 'measurement', 'doordash'],
    is_published: true,
    is_calibration: false,
    is_premium: false,
    steps: [
      {
        step: 'frame',
        step_nudge: 'What does "marketplace health" actually mean when three different groups all need to win simultaneously?',
        grading_weight: 0.25,
        step_order: 1,
        questions: [
          {
            question_text: 'What is the most accurate definition of marketplace health for a three-sided platform like DoorDash?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'domain_expertise'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Marketplace health is the rate at which all three sides are growing simultaneously', quality: 'surface', points: 1, competencies: ['strategic_thinking'], explanation: 'Growth on all sides can still be unhealthy if the sides are growing at mismatched rates or if one side is extracting value from another.' },
              { option_label: 'B', option_text: 'Marketplace health is the degree to which value is created and fairly distributed across all three sides, such that each side prefers the marketplace over alternatives', quality: 'best', points: 3, competencies: ['strategic_thinking', 'domain_expertise'], explanation: 'Multi-sided preference captures the right idea: a marketplace is healthy when all participants would choose it again, not just when aggregate GMV is rising.' },
              { option_label: 'C', option_text: 'Marketplace health is GMV growth divided by platform operating cost, the efficiency of turning supply into demand', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Efficiency is one dimension of health but ignores whether Dashers are earning sustainably and merchants are building profitable relationships with the platform.' },
              { option_label: 'D', option_text: 'Marketplace health is consumer satisfaction score, since consumers drive demand and demand drives everything else', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Consumer-centric definitions collapse the three-sided problem into a one-sided one. DoorDash cannot survive if Dashers quit or merchants pull their listings.' },
            ],
          },
        ],
      },
      {
        step: 'list',
        step_nudge: 'Map one or two leading metrics per side that would give you early warning before a side deteriorates.',
        grading_weight: 0.25,
        step_order: 2,
        questions: [
          {
            question_text: 'Which metric set best captures leading health signals across all three marketplace sides?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'domain_expertise'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Consumer: order frequency. Dasher: earnings per active hour. Merchant: 90-day reorder rate and average basket growth', quality: 'best', points: 3, competencies: ['strategic_thinking', 'domain_expertise'], explanation: 'Each metric is a leading indicator of that side\'s continued participation: frequency signals consumer habit, earnings per hour signals Dasher economics, reorder rate signals merchant business value from the platform.' },
              { option_label: 'B', option_text: 'Consumer: average order value. Dasher: deliveries per hour. Merchant: average rating', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'These are operational metrics, not health metrics. A Dasher who completes 6 deliveries per hour but earns below minimum wage is not a sign of marketplace health.' },
              { option_label: 'C', option_text: 'Consumer: NPS. Dasher: retention rate. Merchant: NPS', quality: 'surface', points: 1, competencies: [], explanation: 'Satisfaction surveys measure perception, not economic participation. A Dasher who is unhappy but has no better option will show high retention until they find one.' },
              { option_label: 'D', option_text: 'GMV growth, CAC for each side, and supply-to-demand ratio by geography', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'These are important business metrics but not side-specific health signals. Supply-demand ratio is an operational input, not a health outcome for any participant.' },
            ],
          },
        ],
      },
      {
        step: 'optimize',
        step_nudge: 'Metrics without thresholds are decorative. What are the tension points between the three sides, and how do you decide when one side\'s gain is acceptable if another side pays the cost?',
        grading_weight: 0.30,
        step_order: 3,
        questions: [
          {
            question_text: 'DoorDash is considering a pricing algorithm change that increases consumer order frequency by 15% but reduces Dasher earnings per hour by 8%. How do you evaluate this tradeoff?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'domain_expertise'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Accept the tradeoff: consumer order frequency drives GMV and Dasher earnings decline is small relative to the volume gain', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'This applies consumer-first logic without modeling the downstream effect. If Dasher earnings decline below local alternatives, supply drops, delivery times increase, and consumer order frequency falls back within 90 days.' },
              { option_label: 'B', option_text: 'Reject the change until the algorithm can increase consumer frequency without reducing Dasher earnings, since both are required for a healthy marketplace', quality: 'surface', points: 1, competencies: ['strategic_thinking'], explanation: 'The zero-compromise stance misses that some tradeoffs are acceptable within bounds. The question is what bounds, not whether tradeoffs exist.' },
              { option_label: 'C', option_text: 'Evaluate against a Dasher earnings floor: if projected earnings per hour stays above the local minimum wage equivalent, the tradeoff is acceptable; if not, it requires compensating measures', quality: 'best', points: 3, competencies: ['strategic_thinking', 'domain_expertise'], explanation: 'Floor-based evaluation models the actual risk: Dasher supply drops when earnings fall below alternatives. Defining an earnings floor converts a subjective tradeoff into a testable constraint.' },
              { option_label: 'D', option_text: 'Run the change in one market and monitor all three sides for 30 days before deciding', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'A market test is good experimental hygiene, but without a pre-defined threshold for what constitutes an acceptable Dasher earnings decline, you will not know how to interpret the results.' },
            ],
          },
        ],
      },
      {
        step: 'win',
        step_nudge: 'What does the single-view health dashboard look like, and how do you make it actionable for a team that owns growth?',
        grading_weight: 0.20,
        step_order: 4,
        questions: [
          {
            question_text: 'Design the structure of a marketplace health scorecard that the growth team reviews weekly.',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['creative_execution', 'strategic_thinking'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Three rows (consumer, Dasher, merchant), each with a primary health metric, a floor threshold in red/green, and a trend arrow. A fourth row shows GMV as the output metric. Any side in red triggers a mandatory investigation before the next growth experiment launches.', quality: 'best', points: 3, competencies: ['creative_execution', 'strategic_thinking'], explanation: 'The gate logic is what makes this actionable: connecting floor thresholds to a hold on growth experiments forces the team to treat side health as a prerequisite, not a vanity metric.' },
              { option_label: 'B', option_text: 'A single composite health score that weights consumer (50%), Dasher (30%), and merchant (20%) metrics into one number', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'A composite score hides which side is deteriorating and allows the strong side to mask the weak one. The board question was about imbalance, which a composite cannot surface.' },
              { option_label: 'C', option_text: 'Separate dashboards for each team (consumer growth, Dasher ops, merchant success) that are linked in Notion for cross-functional reference', quality: 'surface', points: 1, competencies: [], explanation: 'Siloed dashboards are what created the imbalance in the first place. Linking them in Notion does not create accountability across teams.' },
              { option_label: 'D', option_text: 'A weekly report email sent to leadership with consumer, Dasher, and merchant metrics in separate tables', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'A report email is not a health system. It creates awareness without accountability and does not gate any decisions on side health status.' },
            ],
          },
        ],
      },
    ],
  },

  {
    id: 'pm-doordash-003',
    title: 'DashPass Deceleration: Diagnosing Subscription Slowdown',
    scenario_role: 'Product Manager, Subscription Growth',
    scenario_context: 'DashPass, DoorDash\'s subscription product offering free delivery and reduced service fees, has been a key driver of consumer LTV. After three years of strong growth, new subscriber additions have slowed 40% compared to the same quarter last year. The retention rate among existing subscribers remains healthy at 78%.',
    scenario_trigger: 'The VP of Consumer asks the team to present a diagnosis and 90-day response plan within two weeks.',
    scenario_question: 'What is causing DashPass adoption to slow, and what would you do to restore growth?',
    engineer_standout: 'A strong engineer would ask whether DashPass slowdown is a product problem or a market saturation problem. The diagnostic matters: treating saturation as a feature gap leads to wasted shipping cycles.',
    paradigm: 'traditional',
    industry: 'Marketplace',
    sub_vertical: 'Food Delivery',
    difficulty: 'standard',
    estimated_minutes: 20,
    primary_competencies: ['strategic_thinking', 'cognitive_empathy'],
    secondary_competencies: ['domain_expertise'],
    frameworks: ['Problem Tree Analysis', 'Jobs To Be Done'],
    relevant_roles: ['pm', 'data_eng', 'swe'],
    company_tags: ['DoorDash', 'Amazon Prime', 'Instacart+'],
    tags: ['subscription', 'growth', 'dashpass', 'doordash', 'diagnosis'],
    is_published: true,
    is_calibration: false,
    is_premium: false,
    steps: [
      {
        step: 'frame',
        step_nudge: 'Before proposing a fix, what are the two or three structurally distinct reasons a subscription product can stop growing, and which is most likely here?',
        grading_weight: 0.25,
        step_order: 1,
        questions: [
          {
            question_text: 'What is the most accurate framing of the DashPass adoption slowdown?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'domain_expertise'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'The value proposition has weakened because competitors have launched comparable subscriptions', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Competitive parity is a real hypothesis worth testing, but it does not explain why existing subscriber retention is still healthy at 78%. If the value proposition weakened, you would see both problems.' },
              { option_label: 'B', option_text: 'DashPass has saturated the most valuable subscriber segment; remaining non-subscribers are lower-frequency users for whom the subscription economics do not work', quality: 'best', points: 3, competencies: ['strategic_thinking', 'domain_expertise'], explanation: 'S-curve saturation explains the pattern: strong retention (existing subscribers still see value) plus slow new additions (the remaining unsubscribed users order too infrequently to benefit). This distinction drives very different solutions.' },
              { option_label: 'C', option_text: 'The onboarding and trial experience is weak; users are not activating from free trial to paid fast enough', quality: 'surface', points: 1, competencies: ['cognitive_empathy'], explanation: 'Onboarding friction is a common hypothesis but would have been visible in conversion funnel data for years. It does not explain a sudden deceleration.' },
              { option_label: 'D', option_text: 'DashPass pricing is too high relative to perceived value, and a price reduction would unlock the next wave of subscribers', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Price sensitivity does not explain why existing subscribers at the same price are staying at 78%. If pricing were the barrier, churn would have risen alongside slower acquisition.' },
            ],
          },
        ],
      },
      {
        step: 'list',
        step_nudge: 'Given the saturation hypothesis, what are the distinct levers you have, and what does each one actually change about who joins DashPass?',
        grading_weight: 0.25,
        step_order: 2,
        questions: [
          {
            question_text: 'Which set of growth levers best addresses the saturation diagnosis for DashPass?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'creative_execution'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Reduce price, extend the free trial, and add a referral bonus for existing subscribers who bring in new members', quality: 'surface', points: 1, competencies: ['motivation_theory'], explanation: 'These levers all target price sensitivity. If the problem is that remaining non-subscribers order too infrequently to value the subscription, lower prices do not change that economics.' },
              { option_label: 'B', option_text: 'Expand DashPass value to cover new verticals (grocery, alcohol, convenience) to make it compelling for lower-frequency restaurant orderers', quality: 'best', points: 3, competencies: ['strategic_thinking', 'creative_execution'], explanation: 'Vertical expansion changes who can justify the subscription. A user who orders restaurant delivery once a month but groceries twice a week becomes a viable subscriber. This directly addresses the saturation problem by enlarging the viable subscriber pool.' },
              { option_label: 'C', option_text: 'Run targeted ads highlighting DashPass savings to users who have ordered 3 or more times without subscribing', quality: 'good_but_incomplete', points: 2, competencies: ['cognitive_empathy'], explanation: 'Targeting non-subscribers with high order frequency is smart, but these users are probably already aware of DashPass. Awareness campaigns help little once awareness is not the gap.' },
              { option_label: 'D', option_text: 'Launch a family plan at a higher price point to increase ARPU from existing subscribers without needing new ones', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'A family plan increases revenue from existing subscribers but does not address the adoption slowdown. The VP asked for restored growth, not improved monetization per subscriber.' },
            ],
          },
        ],
      },
      {
        step: 'optimize',
        step_nudge: 'Vertical expansion is a multi-quarter investment. What is the 90-day version that tests the hypothesis before full commitment?',
        grading_weight: 0.30,
        step_order: 3,
        questions: [
          {
            question_text: 'How do you test the vertical expansion hypothesis within 90 days before committing to a full roadmap?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'creative_execution'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Launch a full grocery subscription tier in two markets and measure subscriber additions over three months', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'A market test is reasonable, but a full grocery tier launch is a significant engineering investment for a hypothesis test. You would want a faster signal first.' },
              { option_label: 'B', option_text: 'Partner with DashMart or a grocery partner to offer a 30-day DashPass trial that includes grocery delivery benefits, targeting users with 0-2 restaurant orders in the past month, and measure trial-to-paid conversion', quality: 'best', points: 3, competencies: ['strategic_thinking', 'creative_execution'], explanation: 'This is a minimal-investment test of the exact hypothesis: do low-frequency restaurant users subscribe when grocery benefits are included? Trial data and conversion rates answer the question without a full product build.' },
              { option_label: 'C', option_text: 'Survey non-subscribers about what additional benefits would make DashPass worth purchasing', quality: 'surface', points: 1, competencies: ['cognitive_empathy'], explanation: 'Surveys measure stated preferences, not actual willingness to pay. Users routinely say they would pay for features they then ignore in practice.' },
              { option_label: 'D', option_text: 'A/B test the DashPass marketing page with a version that highlights grocery delivery benefits alongside restaurant delivery', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Changing the marketing page tests messaging, not product value. If grocery delivery is not actually included, the improved page will generate clicks but not conversions.' },
            ],
          },
        ],
      },
      {
        step: 'win',
        step_nudge: 'What does success look like, and what would tell you the vertical expansion hypothesis was wrong?',
        grading_weight: 0.20,
        step_order: 4,
        questions: [
          {
            question_text: 'What metrics and thresholds would confirm or refute the vertical expansion hypothesis within 90 days?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Trial-to-paid conversion among low-frequency restaurant users (0-2 orders/month) above 15%; and grocery order frequency among new DashPass subscribers above 1.5x/week within 60 days of subscribing', quality: 'best', points: 3, competencies: ['strategic_thinking'], explanation: 'Two conditions test different parts of the hypothesis: conversion tests whether groceries attract new subscriber types, and post-subscription usage tests whether the value is real or just a sign-up hook.' },
              { option_label: 'B', option_text: 'Overall DashPass subscriber growth returning to prior-year rate within 90 days', quality: 'surface', points: 1, competencies: [], explanation: 'Platform-wide growth recovery is the desired outcome but not a clean hypothesis test. It conflates the grocery expansion effect with seasonal trends and other concurrent changes.' },
              { option_label: 'C', option_text: 'Grocery GMV attributed to DashPass subscribers in the test group exceeding $1M within 60 days', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'GMV is a business metric but not a hypothesis test. High GMV could come from existing high-frequency subscribers who would have ordered grocery anyway.' },
              { option_label: 'D', option_text: 'NPS of trial participants who converted to paid exceeding 50', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Satisfaction of people who already converted tells you the experience is good, not whether the expansion hypothesis is correct for non-subscribers.' },
            ],
          },
        ],
      },
    ],
  },

  {
    id: 'pm-doordash-004',
    title: 'Refund Policy Design: Balancing Trust, Fairness, and Revenue',
    scenario_role: 'Product Manager, Trust and Safety',
    scenario_context: 'DoorDash currently handles refund requests case-by-case, with inconsistent decisions across customer support agents. Consumer complaints about refund denials are up 22% QoQ. Merchants report that approvals feel arbitrary and that fraudulent refund claims are hurting their bottom line. Finance flags that refund payouts have grown faster than GMV.',
    scenario_trigger: 'The Head of Trust asks the product team to design a standardized refund policy that can be implemented across all order types within one quarter.',
    scenario_question: 'How would you design and roll out a standardized refund policy that balances consumer trust, merchant fairness, and revenue impact?',
    engineer_standout: 'A strong engineer would recognize that a refund policy is fundamentally a classification system: given an order and a claim, what bucket does it fall into? The right design question is about the classification logic, the signals used, and how to handle edge cases, not just the policy tiers.',
    paradigm: 'traditional',
    industry: 'Marketplace',
    sub_vertical: 'Food Delivery',
    difficulty: 'advanced',
    estimated_minutes: 25,
    primary_competencies: ['strategic_thinking', 'domain_expertise'],
    secondary_competencies: ['cognitive_empathy'],
    frameworks: ['Stakeholder Mapping', 'Policy Design'],
    relevant_roles: ['pm', 'swe', 'tech_lead', 'data_eng'],
    company_tags: ['DoorDash', 'Uber Eats', 'Amazon'],
    tags: ['policy', 'trust', 'refunds', 'multi-stakeholder', 'doordash'],
    is_published: true,
    is_calibration: false,
    is_premium: false,
    steps: [
      {
        step: 'frame',
        step_nudge: 'Before writing a policy, what is the actual problem with the current system, and who is being harmed most?',
        grading_weight: 0.25,
        step_order: 1,
        questions: [
          {
            question_text: 'What is the root cause of the current refund system problems?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'cognitive_empathy'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Consumer expectations are too high; food delivery inherently has quality variance and refund requests reflect unrealistic standards', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Blaming consumer expectations does not explain why the same order issue gets different refund decisions from different agents, which is the pattern generating complaints.' },
              { option_label: 'B', option_text: 'The absence of a decision framework means that refund outcomes depend on which agent handles the case, creating both consumer frustration and merchant distrust', quality: 'best', points: 3, competencies: ['strategic_thinking', 'cognitive_empathy'], explanation: 'Inconsistency is the root cause. Both consumers and merchants are reacting to the same problem from different sides: consumers distrust the process when they get denied, and merchants distrust it when they see approvals that seem unjustified.' },
              { option_label: 'C', option_text: 'Refund fraud by a small segment of serial claimants is inflating costs and contaminating the pool, making legitimate claims collateral damage', quality: 'good_but_incomplete', points: 2, competencies: ['domain_expertise'], explanation: 'Fraud is a real and contributing factor, but the 22% increase in consumer complaints suggests that over-denial is also occurring. Treating this as purely a fraud problem misdiagnoses the dual failure.' },
              { option_label: 'D', option_text: 'The refund process is too slow; consumers are frustrated with wait times more than outcomes', quality: 'surface', points: 1, competencies: ['cognitive_empathy'], explanation: 'Speed matters but complaints are specifically about denials, not delays. Faster inconsistent decisions would not resolve the underlying trust problem.' },
            ],
          },
        ],
      },
      {
        step: 'list',
        step_nudge: 'Map out the different types of refund claims that exist. What signals distinguish a legitimate claim from a fraudulent one?',
        grading_weight: 0.25,
        step_order: 2,
        questions: [
          {
            question_text: 'Which claim classification approach would give DoorDash the most accurate and scalable refund decisions?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['domain_expertise', 'strategic_thinking'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Classify claims by the consumer\'s stated reason (wrong item, missing item, quality issue, late delivery) and auto-approve specific categories above a dollar threshold', quality: 'surface', points: 1, competencies: ['strategic_thinking'], explanation: 'Stated reasons are easily gamed by consumers. Auto-approvals based on self-reported categories will increase fraud without reducing inconsistency in ambiguous cases.' },
              { option_label: 'B', option_text: 'Build a risk score using order history, claim history, Dasher GPS data, restaurant error rates, and claim-to-order timing to classify claims into auto-approve, auto-deny, and human review buckets', quality: 'best', points: 3, competencies: ['domain_expertise', 'strategic_thinking'], explanation: 'Multi-signal classification addresses both problems: it reduces inconsistency by standardizing decisions, and it catches fraud patterns (repeated claims, implausible timing) that human agents miss. GPS and restaurant error rate data are sources DoorDash already has.' },
              { option_label: 'C', option_text: 'Ask merchants to confirm or dispute each refund claim, then use the merchant response as the deciding signal', quality: 'good_but_incomplete', points: 2, competencies: ['cognitive_empathy'], explanation: 'Merchant confirmation adds a useful signal but creates a conflict of interest: merchants have a financial incentive to dispute all claims regardless of legitimacy, which would shift the trust problem to consumers.' },
              { option_label: 'D', option_text: 'Establish fixed dollar thresholds: auto-approve claims under $10, human review for $10-50, deny claims over $50 unless escalated', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Dollar thresholds create perverse incentives: consumers learn to keep claims under $10, and high-value legitimate claims (a large order with multiple missing items) get denied by default.' },
            ],
          },
        ],
      },
      {
        step: 'optimize',
        step_nudge: 'A risk-score system optimized purely for fraud prevention will over-deny legitimate claims. How do you calibrate it for the right balance?',
        grading_weight: 0.30,
        step_order: 3,
        questions: [
          {
            question_text: 'How do you set the approval thresholds in the risk-score system to balance consumer trust, merchant fairness, and revenue impact?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'domain_expertise'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Set thresholds to minimize total refund payout while maintaining a consumer complaint rate below the current baseline', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Cost minimization with a complaint floor is a reasonable starting point but ignores merchant fairness and does not distinguish between types of incorrect decisions (false positives vs. false negatives).' },
              { option_label: 'B', option_text: 'Set thresholds such that the false denial rate for first-time claimants stays below 5%, while applying stricter scoring to users with three or more prior claims within 90 days', quality: 'best', points: 3, competencies: ['strategic_thinking', 'domain_expertise'], explanation: 'Segmenting by claim history lets you protect new and legitimate claimants while targeting tighter controls at the behavioral pattern most associated with abuse. This is calibrated rather than blunt.' },
              { option_label: 'C', option_text: 'Set thresholds to maximize the percentage of claims auto-resolved without human review, reducing support cost', quality: 'surface', points: 1, competencies: [], explanation: 'Maximizing auto-resolution prioritizes operational efficiency over decision quality. A system that auto-denies 90% of claims will hit the efficiency target while destroying consumer trust.' },
              { option_label: 'D', option_text: 'Ask a cross-functional team of consumer, merchant, and finance representatives to agree on a shared threshold and revisit quarterly', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Committee-based threshold setting is too slow and too influenced by organizational politics. Finance will push for lower thresholds, consumer success will push for higher ones, and the outcome will be a compromise that satisfies no one.' },
            ],
          },
        ],
      },
      {
        step: 'win',
        step_nudge: 'A policy rollout that surprises merchants or consumers will generate backlash even if the policy itself is fair. How do you sequence the launch?',
        grading_weight: 0.20,
        step_order: 4,
        questions: [
          {
            question_text: 'What is the right rollout sequence for the standardized refund policy?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'creative_execution'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Shadow-run the new scoring system alongside the existing process for 30 days, compare decisions, identify systematic gaps, then launch with merchant and consumer notifications describing what changed and why', quality: 'best', points: 3, competencies: ['strategic_thinking', 'creative_execution'], explanation: 'Shadow mode catches systematic errors before they affect real users. The notification step converts a policy change from a surprise into a trust signal. Both steps are necessary: one manages technical risk, the other manages stakeholder trust.' },
              { option_label: 'B', option_text: 'Launch in one market first, monitor complaint and fraud rates for 60 days, then expand to all markets', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Market test is a sensible approach but skips the shadow validation step, meaning systematic classification errors will affect real users in the test market during evaluation.' },
              { option_label: 'C', option_text: 'Announce the new policy to consumers and merchants two weeks before launch, then flip the switch on day one', quality: 'surface', points: 1, competencies: ['cognitive_empathy'], explanation: 'Advance notice is good practice but without shadow validation, the announced policy may need emergency changes on day one, which damages credibility more than silence would have.' },
              { option_label: 'D', option_text: 'Launch the new policy for new consumers and keep the old process for existing consumers to avoid disruption', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Two-tier policies create support complexity and are perceived as unfair when existing consumers learn about the discrepancy, which they inevitably will.' },
            ],
          },
        ],
      },
    ],
  },

  {
    id: 'pm-doordash-005',
    title: 'Faster Deliveries Without Raising Dasher Pay',
    scenario_role: 'Product Manager, Logistics and Operations',
    scenario_context: 'Average DoorDash delivery time has increased from 31 minutes to 38 minutes over the past year as order volume grew faster than Dasher supply. Consumer satisfaction scores correlate directly with delivery time, and the marketing team is running ads promising fast delivery that the operation cannot consistently support.',
    scenario_trigger: 'The COO sets a target to reduce average delivery time to 33 minutes within two quarters without increasing average Dasher pay per delivery.',
    scenario_question: 'How would you improve delivery times without increasing Dasher pay?',
    engineer_standout: 'A strong engineer would frame this as an optimization problem with three variables: time from order to pickup (restaurant preparation), time from pickup to drop-off (routing efficiency), and idle time between deliveries (batching and dispatch logic). Improving delivery time without changing pay means improving the system, not the incentive.',
    paradigm: 'traditional',
    industry: 'Marketplace',
    sub_vertical: 'Food Delivery',
    difficulty: 'standard',
    estimated_minutes: 20,
    primary_competencies: ['strategic_thinking', 'domain_expertise'],
    secondary_competencies: ['creative_execution'],
    frameworks: ['Constraint Analysis', 'System Thinking'],
    relevant_roles: ['pm', 'swe', 'ml_eng', 'data_eng'],
    company_tags: ['DoorDash', 'Uber Eats', 'Instacart'],
    tags: ['logistics', 'operations', 'delivery-time', 'optimization', 'doordash'],
    is_published: true,
    is_calibration: false,
    is_premium: false,
    steps: [
      {
        step: 'frame',
        step_nudge: 'Delivery time is an end-to-end measurement. Which segment of the delivery journey accounts for most of the variance?',
        grading_weight: 0.25,
        step_order: 1,
        questions: [
          {
            question_text: 'What is the most accurate framing of where delivery time is being lost?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'domain_expertise'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Dashers are taking too long to accept orders, creating acceptance lag that compounds into longer delivery times', quality: 'surface', points: 1, competencies: ['domain_expertise'], explanation: 'Acceptance lag is a real component of delivery time but is typically small. The larger variance sources are restaurant wait time and routing inefficiency.' },
              { option_label: 'B', option_text: 'Restaurant preparation time is the largest variable; Dashers arrive before food is ready and wait, consuming time that looks like delivery time in the consumer-facing estimate', quality: 'best', points: 3, competencies: ['strategic_thinking', 'domain_expertise'], explanation: 'In most delivery marketplaces, restaurant preparation is the dominant source of time variance. Dashers waiting at restaurants is dead time that inflates delivery windows and cannot be fixed by routing alone.' },
              { option_label: 'C', option_text: 'Routing algorithms are suboptimal; Dashers are not taking the fastest path from restaurant to consumer', quality: 'good_but_incomplete', points: 2, competencies: ['domain_expertise'], explanation: 'Routing quality matters, but real-time navigation is largely solved by map providers. The marginal gain from routing improvement is smaller than the gain from reducing restaurant wait time.' },
              { option_label: 'D', option_text: 'Order batching causes Dashers to carry multiple orders, adding drop-off time for each delivery in the batch', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Batching increases individual delivery time for some orders but improves efficiency overall. Removing batching would increase delivery time for the average order, not decrease it.' },
            ],
          },
        ],
      },
      {
        step: 'list',
        step_nudge: 'Given that restaurant preparation is the dominant variable, map out the distinct product or system interventions available.',
        grading_weight: 0.25,
        step_order: 2,
        questions: [
          {
            question_text: 'Which set of interventions most directly reduces the restaurant preparation-to-pickup gap?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'creative_execution'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Dynamic preparation time estimates per restaurant fed into dispatch timing, plus a Dasher dispatch algorithm that delays pickup requests until the restaurant\'s predicted ready time', quality: 'best', points: 3, competencies: ['strategic_thinking', 'creative_execution'], explanation: 'Smarter dispatch timing eliminates the primary source of dead time: Dashers waiting at restaurants. The preparation time model is a data product DoorDash is uniquely positioned to build from order history.' },
              { option_label: 'B', option_text: 'Incentivize restaurants to use DoorDash tablet confirmations so the system knows when food is ready', quality: 'good_but_incomplete', points: 2, competencies: ['cognitive_empathy'], explanation: 'Tablet confirmations are a useful signal, but most restaurants will not adopt them reliably. This approach is dependent on merchant behavior change, which is slow.' },
              { option_label: 'C', option_text: 'Hire more Dashers in high-demand areas to reduce the time from order acceptance to Dasher arrival', quality: 'surface', points: 1, competencies: [], explanation: 'More Dashers reduces the wait from order to Dasher dispatch, but if Dashers still arrive before food is ready, total delivery time stays the same.' },
              { option_label: 'D', option_text: 'Introduce a consumer-facing delivery time guarantee with a credit for late orders to create accountability pressure', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'A guarantee creates financial accountability but does not fix the underlying system. Credits cost money without improving operations.' },
            ],
          },
        ],
      },
      {
        step: 'optimize',
        step_nudge: 'Building a restaurant preparation time model is a multi-sprint ML project. What data signals are available today, and what is the minimal viable version?',
        grading_weight: 0.30,
        step_order: 3,
        questions: [
          {
            question_text: 'What is the minimal viable preparation time model that could reduce Dasher wait time within 60 days?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'domain_expertise'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Use historical order-to-pickup timestamps per restaurant to compute a rolling 30-day preparation time percentile, then use the 75th percentile as the dispatch delay for that restaurant', quality: 'best', points: 3, competencies: ['strategic_thinking', 'domain_expertise'], explanation: 'This uses data DoorDash already has, requires no restaurant behavior change, and can ship within weeks. The 75th percentile target means Dashers arrive on time for most orders while erring toward readiness over waiting.' },
              { option_label: 'B', option_text: 'Build a full ML model using restaurant category, order size, time of day, and historical prep time to predict real-time readiness', quality: 'good_but_incomplete', points: 2, competencies: ['domain_expertise'], explanation: 'A full ML model is the right long-term solution, but it requires weeks of feature engineering, training data labeling, and validation before deployment. It does not fit a 60-day window.' },
              { option_label: 'C', option_text: 'Ask restaurants to self-report their average preparation time during onboarding and use that as the dispatch delay', quality: 'surface', points: 1, competencies: [], explanation: 'Self-reported times are inaccurate and static. Restaurants will understate preparation time during onboarding and will not update it as their operation changes.' },
              { option_label: 'D', option_text: 'Add a Dasher in-app timer that starts when they arrive and submit that data to build a preparation time dataset before building any model', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'This collects future data instead of using existing data. DoorDash already has order-to-pickup timestamps from historical deliveries that contain the same signal without requiring new Dasher behavior.' },
            ],
          },
        ],
      },
      {
        step: 'win',
        step_nudge: 'What is your success criteria, and how do you know the improvement came from the dispatch model versus other changes happening in the same period?',
        grading_weight: 0.20,
        step_order: 4,
        questions: [
          {
            question_text: 'How do you measure whether the dispatch timing improvement reduced delivery times, controlling for confounding variables?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'A/B test the dispatch model in matched markets: same restaurant density, same demand levels, same Dasher supply ratios. Primary metric: median delivery time. Secondary metric: Dasher idle time at restaurants.', quality: 'best', points: 3, competencies: ['strategic_thinking'], explanation: 'Matched market A/B test isolates the intervention from seasonal and market-mix confounders. Tracking both delivery time and Dasher idle time confirms the mechanism of action, not just the outcome.' },
              { option_label: 'B', option_text: 'Track average delivery time across all markets before and after the model ships', quality: 'surface', points: 1, competencies: [], explanation: 'Before-after comparison cannot separate the model\'s effect from seasonal demand changes, weather, Dasher supply shifts, or concurrent product changes.' },
              { option_label: 'C', option_text: 'Monitor the 30-day rolling average delivery time and declare success if it reaches 33 minutes within 8 weeks of launch', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'A clear target with a timeline is good, but without a control group, reaching 33 minutes could reflect an unusually favorable demand period rather than the model\'s effect.' },
              { option_label: 'D', option_text: 'Survey Dashers about whether they feel they are waiting less at restaurants after the change', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Dasher perception surveys are noisy and hard to aggregate. They cannot substitute for operational data on actual wait times.' },
            ],
          },
        ],
      },
    ],
  },

  {
    id: 'pm-coinbase-001',
    title: 'Crypto Wallet Adoption in Developing Markets',
    scenario_role: 'Product Manager, International Growth',
    scenario_context: 'Coinbase is considering an expansion push for crypto wallet adoption in developing markets, particularly in Southeast Asia and Sub-Saharan Africa. These markets have high mobile penetration, significant unbanked populations, and strong remittance demand. Current Coinbase wallet adoption in these regions is under 3% despite representing over 40% of global remittance volume.',
    scenario_trigger: 'The Head of International Growth asks for a go-to-market plan for increasing wallet adoption by 10x in one target market within 18 months.',
    scenario_question: 'How would you approach increasing crypto wallet adoption in developing markets?',
    engineer_standout: 'A strong engineer would identify that onboarding friction is not just a UX problem in these markets. It is a trust problem compounded by KYC requirements, data infrastructure limitations, and local currency conversion reliability. The solution requires system design across multiple layers, not a single product change.',
    paradigm: 'traditional',
    industry: 'Fintech',
    sub_vertical: 'Cryptocurrency',
    difficulty: 'advanced',
    estimated_minutes: 25,
    primary_competencies: ['strategic_thinking', 'domain_expertise'],
    secondary_competencies: ['cognitive_empathy'],
    frameworks: ['Go-To-Market Strategy', 'Jobs To Be Done'],
    relevant_roles: ['pm', 'swe', 'tech_lead'],
    company_tags: ['Coinbase', 'M-Pesa', 'Chipper Cash'],
    tags: ['fintech', 'crypto', 'developing-markets', 'go-to-market', 'coinbase'],
    is_published: true,
    is_calibration: false,
    is_premium: false,
    steps: [
      {
        step: 'frame',
        step_nudge: 'Before choosing a strategy, what is the primary barrier to crypto wallet adoption in developing markets: awareness, trust, friction, or economics?',
        grading_weight: 0.25,
        step_order: 1,
        questions: [
          {
            question_text: 'What is the most accurate framing of why crypto wallet adoption is low in developing markets despite high remittance demand?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'cognitive_empathy'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Crypto literacy is low; people do not understand how wallets work or why they are useful for remittances', quality: 'good_but_incomplete', points: 2, competencies: ['cognitive_empathy'], explanation: 'Awareness is a genuine barrier, but it is downstream of a more fundamental problem: even informed users face KYC friction, local currency conversion risk, and limited off-ramp options. Education alone does not resolve these.' },
              { option_label: 'B', option_text: 'The off-ramp problem: even if someone receives crypto, converting it to local currency reliably and cheaply enough to make it better than existing remittance services is unsolved for most of these markets', quality: 'best', points: 3, competencies: ['strategic_thinking', 'domain_expertise'], explanation: 'Off-ramp reliability is the root barrier. A crypto wallet that cannot convert to local currency at a competitive rate is not a usable financial tool for someone receiving remittances. All the other barriers exist downstream of this one.' },
              { option_label: 'C', option_text: 'KYC requirements prevent unbanked populations from completing Coinbase onboarding, blocking the addressable market', quality: 'surface', points: 1, competencies: ['domain_expertise'], explanation: 'KYC friction is a real onboarding barrier, but it is an implementation problem that other companies (M-Pesa, Chipper Cash) have partially solved with mobile-first identity verification. It is not the primary structural barrier.' },
              { option_label: 'D', option_text: 'Smartphone penetration is still too low in the target markets to support mobile crypto wallet adoption at scale', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Smartphone penetration in Southeast Asia and Sub-Saharan Africa has exceeded 60% in urban areas and is growing rapidly. This premise is outdated and does not match the stated context.' },
            ],
          },
        ],
      },
      {
        step: 'list',
        step_nudge: 'Map the distinct components of a developing market go-to-market strategy for a crypto wallet. What must be true in each layer for adoption to happen?',
        grading_weight: 0.25,
        step_order: 2,
        questions: [
          {
            question_text: 'Which go-to-market structure best addresses the layered barriers to crypto wallet adoption in developing markets?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'creative_execution'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Launch a consumer marketing campaign with simplified onboarding, partner with local influencers for awareness, and offer a $10 sign-up bonus for new wallets', quality: 'surface', points: 1, competencies: [], explanation: 'Consumer acquisition campaigns drive trial but cannot sustain retention if the off-ramp problem remains unsolved. Users who receive crypto and cannot convert it will churn and warn their network.' },
              { option_label: 'B', option_text: 'Solve the off-ramp first by partnering with two or three local mobile money operators (M-Pesa, MTN), then build a simplified remittance flow targeting diaspora senders, then run consumer acquisition', quality: 'best', points: 3, competencies: ['strategic_thinking', 'creative_execution'], explanation: 'This sequences correctly: off-ramp partnership creates the utility, remittance flow targets the highest-intent use case first, and consumer acquisition only runs once the product can actually deliver value. Each step unblocks the next.' },
              { option_label: 'C', option_text: 'Focus on merchant adoption first: getting local merchants to accept crypto payments creates demand from consumers and establishes the off-ramp simultaneously', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Merchant adoption is a viable strategy but a slower one. Remittance is a more urgent, higher-frequency use case that creates faster habit formation. Merchant adoption follows consumer adoption in most successful crypto rollouts.' },
              { option_label: 'D', option_text: 'License the Coinbase brand to a local fintech partner who manages operations, reducing Coinbase\'s execution risk', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Licensing reduces execution risk but also reduces Coinbase\'s ability to control the product experience, collect data, and build the network effects that make a developing market expansion strategically valuable.' },
            ],
          },
        ],
      },
      {
        step: 'optimize',
        step_nudge: 'Choose one target market to go deep on first. What makes a market the right beachhead, and what would you sacrifice by choosing it?',
        grading_weight: 0.30,
        step_order: 3,
        questions: [
          {
            question_text: 'Which market would you choose as the first beachhead for the crypto wallet expansion, and why?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'domain_expertise'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Nigeria: largest diaspora remittance market in Sub-Saharan Africa, high crypto adoption baseline (Chainalysis ranked it top 3 globally in 2023), and mobile payment infrastructure via Flutterwave and Paystack enables off-ramps', quality: 'best', points: 3, competencies: ['strategic_thinking', 'domain_expertise'], explanation: 'Nigeria scores highest on the criteria that matter: existing crypto adoption reduces education cost, remittance volume provides immediate use case, and local payment infrastructure enables off-ramps. The regulatory environment is complex but more defined than most peer markets.' },
              { option_label: 'B', option_text: 'Indonesia: large population, growing middle class, and government-backed blockchain initiatives that create regulatory tailwinds', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Indonesia is a reasonable choice but has lower remittance dependency and a more fragmented local payment infrastructure than Nigeria. Government blockchain initiatives are a tailwind but not yet an off-ramp solution.' },
              { option_label: 'C', option_text: 'Kenya: M-Pesa is the gold standard of mobile money, so the off-ramp infrastructure is best in the world and the Coinbase integration path is clearest', quality: 'surface', points: 1, competencies: ['domain_expertise'], explanation: 'Kenya\'s M-Pesa infrastructure is excellent, but Kenya\'s remittance market is smaller than Nigeria and the crypto adoption baseline is lower. Good infrastructure alone does not make the best beachhead without demand scale.' },
              { option_label: 'D', option_text: 'Philippines: largest per-capita remittance market globally, strong OFW diaspora, and high smartphone penetration in urban areas', quality: 'surface', points: 1, competencies: ['domain_expertise'], explanation: 'Philippines is a strong candidate but the regulatory environment for crypto has been volatile and the existing remittance services (GCash, Maya) are deeply entrenched with strong brand trust that is hard to displace.' },
            ],
          },
        ],
      },
      {
        step: 'win',
        step_nudge: 'What does 10x wallet adoption look like in concrete numbers, and what leading indicators would tell you within 90 days whether the strategy is working?',
        grading_weight: 0.20,
        step_order: 4,
        questions: [
          {
            question_text: 'What are the right leading indicators to track in the first 90 days of the developing market expansion?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Off-ramp conversion rate (% of inbound crypto transactions successfully converted to local currency), remittance activation rate (new wallets that complete at least one inbound transfer within 30 days), and 60-day wallet retention rate', quality: 'best', points: 3, competencies: ['strategic_thinking'], explanation: 'These three metrics test the three hypotheses in sequence: off-ramp works, remittance flow activates users, and users stay after first transaction. All three must be positive for 10x adoption to be reachable.' },
              { option_label: 'B', option_text: 'New wallet registrations per week, app store rating in the target market, and social media mentions', quality: 'surface', points: 1, competencies: [], explanation: 'Registrations are a vanity metric without activation data. App store ratings and social mentions correlate weakly with long-term adoption.' },
              { option_label: 'C', option_text: 'Total transaction volume in local currency and monthly active wallet count', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Lagging outcome metrics that take multiple months to accumulate. They confirm success but not in time to course-correct within 90 days.' },
              { option_label: 'D', option_text: 'KYC completion rate and time-to-first-transaction after wallet creation', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'KYC completion measures onboarding friction, not market-level adoption viability. Fixing onboarding while the off-ramp remains broken will not drive 10x adoption.' },
            ],
          },
        ],
      },
    ],
  },

  {
    id: 'pm-coinbase-002',
    title: 'Coinbase Onboarding: Setting Goals for a High-Stakes First Experience',
    scenario_role: 'Product Manager, Onboarding',
    scenario_context: 'The Coinbase onboarding experience is the first product surface a new user encounters after deciding to buy or hold crypto. It spans identity verification (KYC), bank or card linking, and first purchase or deposit. Drop-off is highest at the KYC step, where regulatory requirements mandate document verification that can take minutes or fail entirely.',
    scenario_trigger: 'The VP of Product asks the onboarding PM to define the goals and success metrics for the onboarding product at the upcoming planning cycle.',
    scenario_question: 'How would you set goals and define success for the Coinbase onboarding experience?',
    engineer_standout: 'A strong engineer would recognize that onboarding metrics must model the full funnel, not just activation. A 90% KYC completion rate that produces users who never make a purchase is not a healthy onboarding outcome. The right metric structure aligns short-term funnel steps with long-term retention and transaction behavior.',
    paradigm: 'traditional',
    industry: 'Fintech',
    sub_vertical: 'Cryptocurrency',
    difficulty: 'standard',
    estimated_minutes: 20,
    primary_competencies: ['strategic_thinking', 'cognitive_empathy'],
    secondary_competencies: ['domain_expertise'],
    frameworks: ['North Star Framework', 'Funnel Analysis'],
    relevant_roles: ['pm', 'swe', 'data_eng'],
    company_tags: ['Coinbase', 'Robinhood', 'Cash App'],
    tags: ['metrics', 'onboarding', 'fintech', 'coinbase', 'goal-setting'],
    is_published: true,
    is_calibration: false,
    is_premium: false,
    steps: [
      {
        step: 'frame',
        step_nudge: 'What does it mean for an onboarding experience to "succeed"? Is it getting users through the funnel, or something that happens after the funnel?',
        grading_weight: 0.25,
        step_order: 1,
        questions: [
          {
            question_text: 'What is the most accurate framing of the goal for the Coinbase onboarding experience?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'cognitive_empathy'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Maximize the percentage of new sign-ups who complete KYC verification', quality: 'surface', points: 1, competencies: [], explanation: 'KYC completion is a necessary step, not a success state. A user who completes KYC but never makes a purchase has not been successfully onboarded.' },
              { option_label: 'B', option_text: 'Get users to their first transaction as quickly and confidently as possible, in a way that predicts long-term retention on the platform', quality: 'best', points: 3, competencies: ['strategic_thinking', 'cognitive_empathy'], explanation: 'First transaction is the activation event, but anchoring to long-term retention prevents optimizing for cheap activations that churn quickly. This framing connects the onboarding metric to the business outcome it serves.' },
              { option_label: 'C', option_text: 'Reduce the time-to-complete for the KYC and bank-linking steps to minimize abandonment', quality: 'good_but_incomplete', points: 2, competencies: ['cognitive_empathy'], explanation: 'Reducing friction is important but is a means, not an end. Speeding up KYC without addressing the post-KYC experience or purchase confidence does not constitute onboarding success.' },
              { option_label: 'D', option_text: 'Ensure regulatory compliance through KYC while keeping the user experience competitive with Robinhood and Cash App', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Compliance is a constraint, not a goal. Benchmarking against competitors is relevant for product design but not a goal statement for a planning cycle.' },
            ],
          },
        ],
      },
      {
        step: 'list',
        step_nudge: 'Map the full onboarding funnel from sign-up to first purchase. Which steps are controllable by the product team, and which are constrained by regulation or external dependencies?',
        grading_weight: 0.25,
        step_order: 2,
        questions: [
          {
            question_text: 'Which funnel structure best captures the onboarding steps the PM team can directly influence?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'domain_expertise'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Sign-up, email verification, KYC start, KYC pass rate, payment method link, first purchase within 7 days', quality: 'best', points: 3, competencies: ['strategic_thinking', 'domain_expertise'], explanation: 'This funnel tracks the steps in sequence and separately measures KYC start (which PM controls via entry point design) from KYC pass rate (which depends on ID quality and vendor performance). The 7-day purchase window creates an activation time constraint that prevents late conversions from masking drop-off.' },
              { option_label: 'B', option_text: 'Sign-up to first purchase conversion rate as a single metric', quality: 'surface', points: 1, competencies: [], explanation: 'A single conversion rate hides where users drop off and which step to improve. The PM cannot prioritize without knowing the step-level funnel.' },
              { option_label: 'C', option_text: 'Sign-up, identity verification, first deposit, first purchase, 30-day active rate', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'This funnel is reasonable but does not distinguish KYC start from KYC pass rate, which matters because one is a product problem and the other is a vendor or document quality problem.' },
              { option_label: 'D', option_text: 'App store rating, support ticket volume related to onboarding, and onboarding NPS', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'These are diagnostic signals for problems that already exist, not a funnel that defines what onboarding success looks like going into a planning cycle.' },
            ],
          },
        ],
      },
      {
        step: 'optimize',
        step_nudge: 'Not all onboarding steps have the same impact on long-term retention. Where would you focus your team\'s investment first, and what would you deprioritize?',
        grading_weight: 0.30,
        step_order: 3,
        questions: [
          {
            question_text: 'Data shows that users who link a bank account (not just a debit card) within 24 hours of KYC have 3x higher 90-day retention than debit-card users. Where does this shift your investment?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'creative_execution'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Invest in making bank account linking faster and more prominent in the onboarding flow, even at the cost of slightly lower overall activation rates', quality: 'best', points: 3, competencies: ['strategic_thinking', 'creative_execution'], explanation: 'If bank-linked users retain at 3x the rate, the long-term value of a bank-linked activation far exceeds a debit-card activation even at somewhat lower conversion. Optimizing for quality of activation over quantity is the right tradeoff when the data is this clear.' },
              { option_label: 'B', option_text: 'Run an A/B test offering a $10 bonus for linking a bank account to see if the incentive improves link rates', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'An incentive test is a reasonable hypothesis, but it treats bank linking as an awareness or motivation problem. The primary opportunity is making bank linking easier in the flow, not more lucrative.' },
              { option_label: 'C', option_text: 'Focus on reducing KYC drop-off because it is the largest absolute funnel loss point regardless of payment method downstream', quality: 'surface', points: 1, competencies: ['strategic_thinking'], explanation: 'KYC drop-off is a volume problem, but the retention data suggests the quality of users who link a bank account matters more than the total number of KYC completers. Fixing KYC without addressing payment method quality misses the higher-value opportunity.' },
              { option_label: 'D', option_text: 'Segment reporting by payment method linked, then present the data to leadership and let them decide the investment priority', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Presenting data and deferring to leadership is not a product decision. The PM\'s job is to make the call, not to escalate analysis.' },
            ],
          },
        ],
      },
      {
        step: 'win',
        step_nudge: 'Write the goal structure you would present at the planning cycle. What is the north star, what are the supporting metrics, and what is not a goal?',
        grading_weight: 0.20,
        step_order: 4,
        questions: [
          {
            question_text: 'Which goal structure best captures the right success definition for Coinbase onboarding at a planning cycle?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'creative_execution'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'North star: % of sign-ups who make a first purchase within 7 days. Supporting: bank-link rate within 24h of KYC, KYC pass rate, median time from sign-up to first purchase. Not a goal: total sign-up volume (owned by acquisition, not onboarding).', quality: 'best', points: 3, competencies: ['strategic_thinking', 'creative_execution'], explanation: 'This structure is complete: a north star that reflects product success, supporting metrics that explain the north star, and an explicit out-of-scope statement that prevents the onboarding team from being held accountable for acquisition volume they do not control.' },
              { option_label: 'B', option_text: 'Goal: increase onboarding conversion rate from 42% to 55% by end of year. Metric: sign-up to first purchase within 30 days.', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'A clear target with a metric is a reasonable planning artifact, but the 30-day window is too loose and a single metric does not show where to invest. The north star plus supporting structure is more actionable.' },
              { option_label: 'C', option_text: 'Goal: best-in-class onboarding experience benchmarked against Robinhood\'s conversion rate and Cash App\'s time-to-first-transaction.', quality: 'surface', points: 1, competencies: [], explanation: 'Competitive benchmarks are useful context but not a goal structure. You cannot directly measure your position against a competitor\'s internal metric, and parity with a competitor does not guarantee an improvement in your own business outcome.' },
              { option_label: 'D', option_text: 'Goal: reduce onboarding support ticket volume by 40% while maintaining current conversion rates.', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Support ticket reduction is an operational efficiency goal, not a product success goal. It optimizes for reducing complaints without ensuring that users are actually succeeding with the product.' },
            ],
          },
        ],
      },
    ],
  },
] as const
