// PM Interview Challenges — Batch 2: Anthropic/Perplexity/Meta (q008-q015)

export const CHALLENGES = [
  {
    id: 'pm-anthropic-001',
    title: 'Communicating AI Uncertainty to End Users',
    scenario_role: 'Staff Engineer, AI Products',
    scenario_context: 'The team ships a consumer-facing Claude-powered writing assistant. Qualitative feedback shows users treating confident-sounding outputs as ground truth, even when the model is operating near the edge of its knowledge. Three support tickets this week involve users citing fabricated statistics the model produced.',
    scenario_trigger: 'A content team at an enterprise client publishes an article containing a made-up study the assistant cited. The client demands a fix before their next content cycle in 10 days.',
    scenario_question: 'What product feature design best communicates model uncertainty without making the product feel broken or untrustworthy?',
    engineer_standout: 'A strong engineer would frame this as a calibration communication problem, not a UI decoration problem — distinguishing between epistemic uncertainty (unknown facts) and aleatoric uncertainty (inherently ambiguous prompts), and proposing inline confidence signals tied to actual model logits or retrieval coverage rather than generic disclaimers.',
    paradigm: 'ai_assisted',
    industry: 'AI Tooling',
    sub_vertical: 'Writing Assistance',
    difficulty: 'advanced',
    estimated_minutes: 20,
    primary_competencies: ['cognitive_empathy', 'creative_execution'],
    secondary_competencies: ['domain_expertise', 'taste'],
    frameworks: ['Human-in-the-Loop Design', 'Trust Calibration'],
    relevant_roles: ['ml_eng', 'swe', 'pm', 'tech_lead'],
    company_tags: ['Anthropic', 'OpenAI', 'Notion AI', 'Perplexity'],
    tags: ['ai-safety', 'uncertainty', 'trust', 'ux', 'calibration', 'anthropic'],
    is_published: true,
    is_calibration: false,
    is_premium: false,
    steps: [
      {
        step: 'frame',
        step_nudge: 'What is the root cause here — is it the model producing wrong outputs, or users having no signal to know when to be skeptical?',
        grading_weight: 0.25,
        step_order: 1,
        questions: [
          {
            question_text: 'What is the most accurate framing of the uncertainty communication problem?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['cognitive_empathy', 'domain_expertise'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'The model produces factually wrong outputs too often and needs more RLHF before shipping to enterprise clients', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Model quality is a separate concern. Even accurate models produce uncertain outputs in low-coverage domains. Framing this as a model bug skips the product design problem.' },
              { option_label: 'B', option_text: 'Users lack a reliable signal for when the model is operating in low-confidence territory, so they cannot calibrate their own trust appropriately', quality: 'best', points: 3, competencies: ['cognitive_empathy', 'domain_expertise'], explanation: 'The root cause is a missing signal, not bad outputs. When users cannot distinguish high-confidence from low-confidence responses, they default to trusting everything — a predictable and fixable design gap.' },
              { option_label: 'C', option_text: 'The product onboarding does not warn users that AI can hallucinate, so they were never educated about the risk', quality: 'surface', points: 1, competencies: ['cognitive_empathy'], explanation: 'One-time onboarding warnings do not transfer to moment-of-use. A disclaimer users read once does not help them evaluate a specific output three weeks later.' },
              { option_label: 'D', option_text: 'Enterprise clients need a different product tier with stricter factual constraints and human review before output delivery', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Enterprise tiering is a reasonable commercial response but sidesteps the product design question and does nothing for the existing client in 10 days.' },
            ],
          },
        ],
      },
      {
        step: 'list',
        step_nudge: 'What are the structurally distinct design approaches for surfacing uncertainty inline — not variations on disclaimers?',
        grading_weight: 0.25,
        step_order: 2,
        questions: [
          {
            question_text: 'Which design approach most accurately communicates model uncertainty at the point of consumption?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['creative_execution', 'taste'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Add a footer disclaimer on every response: "AI outputs may contain errors. Always verify important claims."', quality: 'surface', points: 1, competencies: [], explanation: 'Blanket disclaimers apply equally to all outputs and train users to ignore them. They convey no information about which specific claims need verification.' },
              { option_label: 'B', option_text: 'Highlight specific spans of text with a confidence indicator derived from retrieval coverage or token probability — low-confidence spans get a hover tooltip suggesting verification', quality: 'best', points: 3, competencies: ['creative_execution', 'domain_expertise'], explanation: 'Span-level signals give users actionable, local information. Anchored to actual model uncertainty signals rather than generic risk framing, this is calibrated communication.' },
              { option_label: 'C', option_text: 'Show a single document-level confidence badge (e.g., "Medium Confidence") computed from average token probability', quality: 'good_but_incomplete', points: 2, competencies: ['creative_execution'], explanation: 'Document-level signals are better than no signal, but averaging masks high-risk spans within otherwise accurate responses — exactly the failure mode in this scenario.' },
              { option_label: 'D', option_text: 'Require users to click "Verify with sources" before copying any output, forcing them to confirm they checked the claims', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Friction gates create resentment and workarounds. Users will click through without checking, and the UX burden will reduce adoption without improving safety.' },
            ],
          },
        ],
      },
      {
        step: 'optimize',
        step_nudge: 'What is the key tradeoff between surface-level safety signals and the product feeling broken or overly cautious?',
        grading_weight: 0.30,
        step_order: 3,
        questions: [
          {
            question_text: 'You ship span-level uncertainty highlighting. Usage data shows users are clicking away on responses with many highlighted spans. What is the right optimization?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'cognitive_empathy'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Raise the threshold for highlighting so only very low-confidence spans appear, reducing visual noise at the cost of missing some uncertain claims', quality: 'best', points: 3, competencies: ['strategic_thinking', 'cognitive_empathy'], explanation: 'Threshold tuning names the criterion (user retention) and names the sacrifice (some missed uncertain claims). This is the correct tradeoff framing — not hiding uncertainty, but calibrating signal density to user behavior.' },
              { option_label: 'B', option_text: 'Remove span highlighting entirely and revert to a document-level badge to stop the drop-off', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Reverting to a weaker signal to preserve engagement trades safety for retention. The original enterprise incident came from insufficient user signals.' },
              { option_label: 'C', option_text: 'A/B test different highlight colors to find one that feels less alarming to users', quality: 'surface', points: 1, competencies: ['taste'], explanation: 'Color tuning addresses aesthetics, not the core issue of signal density. If many spans are highlighted, aesthetics do not reduce the cognitive load.' },
              { option_label: 'D', option_text: 'Add a user setting that lets people toggle uncertainty highlighting on or off based on their preference', quality: 'good_but_incomplete', points: 2, competencies: ['cognitive_empathy'], explanation: 'User control is good design, but most users will default to off, defeating the safety goal. A well-calibrated default matters more than the option.' },
            ],
          },
        ],
      },
      {
        step: 'win',
        step_nudge: 'What is the falsifiable hypothesis you would ship to the enterprise client in 10 days, and how would you measure whether it worked?',
        grading_weight: 0.20,
        step_order: 4,
        questions: [
          {
            question_text: 'What is the right success metric for the uncertainty communication feature?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'domain_expertise'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Reduction in user-reported factual errors in support tickets within 30 days of launch', quality: 'best', points: 3, competencies: ['strategic_thinking'], explanation: 'Directly measures the outcome that caused the enterprise incident. Falsifiable: if tickets do not drop, the feature is not working as intended. Specific enough to act on.' },
              { option_label: 'B', option_text: 'Click-through rate on uncertainty tooltip hover interactions', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Tooltip engagement is a proxy for user awareness, not for whether users are actually catching and avoiding fabricated claims.' },
              { option_label: 'C', option_text: 'User satisfaction (CSAT) on AI-generated content quality', quality: 'surface', points: 1, competencies: [], explanation: 'CSAT is too broad and slow to change. It conflates quality perception with dozens of other product factors.' },
              { option_label: 'D', option_text: 'Model accuracy measured on an internal benchmark dataset before and after the feature ships', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'The feature is a communication layer, not a model improvement. Benchmarking the model measures something orthogonal to whether users are better calibrated.' },
            ],
          },
        ],
      },
    ],
  },

  {
    id: 'pm-anthropic-002',
    title: 'Safety vs. Capability: When to Ship a New AI Feature',
    scenario_role: 'Tech Lead, AI Platform',
    scenario_context: 'The product team has a new code generation feature that dramatically improves developer productivity in internal evals. The safety team flags that in 2% of test cases the feature produces code with subtle security vulnerabilities that are not obvious to junior developers. The feature is scheduled to launch in 3 weeks.',
    scenario_trigger: 'The head of safety requests a 60-day delay for additional red-teaming. The head of product argues the feature is already safer than Stack Overflow answers most junior devs copy from.',
    scenario_question: 'How do you prioritize between shipping the capability and completing the safety review, given competing stakeholder pressures and a real user need?',
    engineer_standout: 'An engineer would recognize that the 2% failure rate on security is not a uniform risk — it depends heavily on deployment context. Code running in a sandbox is different from code deployed to production auth flows. The right move is contextual scoping, not a binary ship/hold.',
    paradigm: 'ai_assisted',
    industry: 'AI Tooling',
    sub_vertical: 'Developer Tools',
    difficulty: 'advanced',
    estimated_minutes: 22,
    primary_competencies: ['strategic_thinking', 'domain_expertise'],
    secondary_competencies: ['cognitive_empathy'],
    frameworks: ['Risk-Based Prioritization', 'Staged Rollout'],
    relevant_roles: ['tech_lead', 'ml_eng', 'pm', 'swe'],
    company_tags: ['Anthropic', 'GitHub Copilot', 'Cursor', 'Replit'],
    tags: ['ai-safety', 'prioritization', 'developer-tools', 'security', 'anthropic'],
    is_published: true,
    is_calibration: false,
    is_premium: false,
    steps: [
      {
        step: 'frame',
        step_nudge: 'Before choosing between delay and launch, what is the actual question being decided — and what information is missing from this framing?',
        grading_weight: 0.25,
        step_order: 1,
        questions: [
          {
            question_text: 'What is the most productive framing of the safety-versus-capability decision?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'domain_expertise'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'It is a values question — safety culture must always win over velocity to preserve Anthropic\'s brand differentiation', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Safety culture matters, but treating every safety flag as a blanket hold ignores the actual risk severity and leaves real user value on the table without a principled framework.' },
              { option_label: 'B', option_text: 'It is a risk-scoping question — the 2% failure rate is meaningless without knowing which use cases those failures occur in and what the blast radius is', quality: 'best', points: 3, competencies: ['strategic_thinking', 'domain_expertise'], explanation: 'Contextual risk assessment is the correct upstream move. A 2% security vulnerability rate in a prototype scaffold is different from 2% in production auth code. Scoping unlocks a partial-launch path.' },
              { option_label: 'C', option_text: 'It is a stakeholder alignment problem — the safety lead and product lead need a shared decision framework before any technical analysis', quality: 'surface', points: 1, competencies: ['cognitive_empathy'], explanation: 'Process alignment is necessary but downstream of understanding the actual risk. Meeting first and analyzing second wastes time and produces the wrong framing.' },
              { option_label: 'D', option_text: 'It is a benchmark problem — the comparison to Stack Overflow is the right frame and needs to be quantified for the safety team to accept it', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'The Stack Overflow comparison is a rhetorical move, not a safety argument. It does not answer what the blast radius is for the 2% case in this specific product context.' },
            ],
          },
        ],
      },
      {
        step: 'list',
        step_nudge: 'What are the structurally distinct options between a full launch and a full delay — and what does each sacrifice?',
        grading_weight: 0.25,
        step_order: 2,
        questions: [
          {
            question_text: 'Which set of options represents genuinely distinct paths, not variations on the same approach?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'creative_execution'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Option 1: Full launch as scheduled. Option 2: 60-day delay with full red-team. Option 3: Launch with a "beta" label to lower user expectations.', quality: 'surface', points: 1, competencies: [], explanation: 'Option 3 is not a safety measure — it is a liability hedge. The list fails the width test because all three options treat launch scope as binary.' },
              { option_label: 'B', option_text: 'Option 1: Full delay. Option 2: Launch to internal users only. Option 3: Launch with sandbox-only code execution and no production deployment path. Option 4: Launch with automated security scanning on all generated code before display.', quality: 'best', points: 3, competencies: ['strategic_thinking', 'creative_execution'], explanation: 'Four structurally distinct options: time delay, audience scope, execution context restriction, and automated guardrail. Each sacrifices something different and can be evaluated independently.' },
              { option_label: 'C', option_text: 'Option 1: Delay 30 days. Option 2: Delay 60 days. Option 3: Delay until 0% failure rate.', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'All three options are the same category (delay) with different durations. No structural diversity, and 0% failure rate is not a realistic target for probabilistic systems.' },
              { option_label: 'D', option_text: 'Option 1: Full launch. Option 2: Delay 60 days. Option 3: Launch with a user consent screen explaining the security risk.', quality: 'good_but_incomplete', points: 2, competencies: ['cognitive_empathy'], explanation: 'Consent screens are better than nothing but fail for the junior developer population — the people least likely to know what the security risk means are exactly who needs protection.' },
            ],
          },
        ],
      },
      {
        step: 'optimize',
        step_nudge: 'Name the criterion you are optimizing for and what you are explicitly giving up to achieve it.',
        grading_weight: 0.30,
        step_order: 3,
        questions: [
          {
            question_text: 'You learn that 80% of the 2% security-vulnerable cases occur only in generated code touching auth and secrets management. What is the right decision?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'domain_expertise'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Launch the full feature and add a warning banner specifically on auth-related suggestions — optimizing for velocity while sacrificing precision of the safety signal', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Warning banners are low-friction but low-efficacy for junior developers who cannot evaluate the warning. Better than nothing, but the sacrifice is that the riskiest users get the weakest protection.' },
              { option_label: 'B', option_text: 'Launch with auth and secrets management prompts filtered out entirely — optimizing for clean safety on the highest-risk cases while sacrificing 20% of feature value', quality: 'best', points: 3, competencies: ['strategic_thinking', 'domain_expertise'], explanation: 'Scoped feature launch names the criterion (eliminate the high-risk tail) and names the sacrifice (20% of capability). This is a principled tradeoff, not a hedge, and unblocks the launch in 3 weeks.' },
              { option_label: 'C', option_text: 'Full delay for 60 days to red-team all edge cases, including the 20% of non-auth cases — optimizing for complete safety coverage', quality: 'surface', points: 1, competencies: [], explanation: 'Given the new data, a full delay is no longer proportionate. The high-risk category is now identifiable and filterable. Treating all cases the same ignores the information just gathered.' },
              { option_label: 'D', option_text: 'Ship to enterprise customers only, since they have security teams who can review generated code before deployment', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Enterprise-first shipping assumes enterprise customers have review capacity, which is not guaranteed, and it delays the developer tool from reaching the exact audience (junior devs) where it has the highest leverage.' },
            ],
          },
        ],
      },
      {
        step: 'win',
        step_nudge: 'What is the falsifiable test that tells you whether the scoped launch was the right call — and by when?',
        grading_weight: 0.20,
        step_order: 4,
        questions: [
          {
            question_text: 'How do you define success for the scoped launch over the first 90 days?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'creative_execution'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Zero reported security incidents from generated code AND auth-related prompts re-enabled after passing 30-day red-team with no new vulnerability categories found', quality: 'best', points: 3, competencies: ['strategic_thinking', 'creative_execution'], explanation: 'Two conditions: safety outcome (no incidents) and a concrete gate for restoring the filtered capability. This makes the tradeoff reversible and sets a clear signal for when to expand.' },
              { option_label: 'B', option_text: 'Developer satisfaction scores above 4.2 on the code generation feature', quality: 'surface', points: 1, competencies: [], explanation: 'Satisfaction measures perceived value, not safety outcomes. A feature can score well and still produce security issues that users do not know to report.' },
              { option_label: 'C', option_text: 'No security-related support tickets or user complaints in the first 30 days', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Support tickets are a lagging and sparse signal — most security issues from generated code would never surface as support tickets, especially from junior devs who do not recognize the problem.' },
              { option_label: 'D', option_text: 'Reduction in the 2% failure rate on internal security evals to below 0.5%', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Internal eval improvement measures model progress, not launch success. The 2% figure was for unfiltered outputs; the filtered launch already removes that risk category.' },
            ],
          },
        ],
      },
    ],
  },

  {
    id: 'pm-anthropic-003',
    title: 'Diagnosing Slow Adoption of an AI Platform',
    scenario_role: 'Founding Engineer, Growth',
    scenario_context: 'Anthropic\'s API platform has seen visibility grow significantly through media coverage and conference talks. Despite this, month-over-month new paying customer growth has slowed from 18% to 6% over three months. Churn among existing customers is flat. The sales team says inbound lead quality is high.',
    scenario_trigger: 'The growth dashboard flags that trial-to-paid conversion dropped from 31% to 19% in the last two months, concentrated in teams of 5-15 engineers.',
    scenario_question: 'How would you diagnose the root cause of the adoption slowdown and determine which part of the funnel to fix first?',
    engineer_standout: 'An engineer would look at where in the trial period drop-off happens rather than treating conversion as a single event. The difference between "stuck at API key setup" versus "failed first meaningful integration" versus "couldn\'t get model outputs good enough to ship" points to completely different root causes and solutions.',
    paradigm: 'ai_native',
    industry: 'AI Tooling',
    sub_vertical: 'Developer Platform',
    difficulty: 'standard',
    estimated_minutes: 18,
    primary_competencies: ['strategic_thinking', 'domain_expertise'],
    secondary_competencies: ['cognitive_empathy'],
    frameworks: ['Funnel Analysis', 'Jobs To Be Done'],
    relevant_roles: ['swe', 'tech_lead', 'pm', 'ml_eng'],
    company_tags: ['Anthropic', 'OpenAI', 'Cohere', 'Together AI'],
    tags: ['growth', 'conversion', 'developer-platform', 'diagnosis', 'anthropic'],
    is_published: true,
    is_calibration: false,
    is_premium: false,
    steps: [
      {
        step: 'frame',
        step_nudge: 'The drop is in one specific customer segment. What does that tell you about where the friction is — and where it is not?',
        grading_weight: 0.25,
        step_order: 1,
        questions: [
          {
            question_text: 'What is the most precise framing of the conversion drop?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'domain_expertise'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'The overall API platform has a positioning problem — high visibility is attracting the wrong audience who were never going to pay', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Churn is flat and inbound lead quality is reported as high. Positioning might be a long-term concern but does not explain a segmented conversion drop concentrated in 5-15 person teams.' },
              { option_label: 'B', option_text: 'The 5-15 engineer team segment hits a specific onboarding friction point that solo developers and large enterprises do not — the segmentation is a diagnostic signal, not a coincidence', quality: 'best', points: 3, competencies: ['strategic_thinking', 'domain_expertise'], explanation: 'Segmented drops point upstream. Mid-size teams have distinct patterns: shared API key management, team-level approval for billing, and a need for integration examples at non-trivial scale. The segment is the clue.' },
              { option_label: 'C', option_text: 'The trial period is too short for teams to complete an integration and see value before the trial expires', quality: 'good_but_incomplete', points: 2, competencies: ['cognitive_empathy'], explanation: 'Time-to-value friction is real and worth investigating, but it does not explain why this specific team size is affected while others are not.' },
              { option_label: 'D', option_text: 'Competitor models (GPT-4o, Gemini) improved enough to win trials that Claude would have won 6 months ago', quality: 'surface', points: 1, competencies: [], explanation: 'Competitive loss is possible but speculative without data, and it does not explain the team-size concentration. Attribution to competition requires evidence from lost-deal surveys.' },
            ],
          },
        ],
      },
      {
        step: 'list',
        step_nudge: 'Map out all the distinct places where a 5-15 person engineering team could stall between signing up for a trial and becoming a paying customer.',
        grading_weight: 0.25,
        step_order: 2,
        questions: [
          {
            question_text: 'Which set of funnel drop-off hypotheses is most structurally comprehensive for the 5-15 engineer segment?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['domain_expertise', 'strategic_thinking'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Hypothesis 1: First API call never made (setup friction). Hypothesis 2: First integration completed but model output quality insufficient for use case. Hypothesis 3: Technical success but budget approval stalls at manager level.', quality: 'best', points: 3, competencies: ['domain_expertise', 'strategic_thinking'], explanation: 'Three structurally distinct categories: developer experience (setup), model quality (output fit), and organizational (budget). Each points to a different fix and can be isolated with funnel event data.' },
              { option_label: 'B', option_text: 'Hypothesis 1: Pricing too high. Hypothesis 2: Pricing unclear. Hypothesis 3: No annual contract option.', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'All three hypotheses are in the pricing category. This fails the width test and would concentrate diagnosis on one variable while missing technical and organizational causes.' },
              { option_label: 'C', option_text: 'Hypothesis 1: Documentation is poor. Hypothesis 2: No SDKs in the team\'s preferred language. Hypothesis 3: Onboarding email sequence is generic.', quality: 'surface', points: 1, competencies: [], explanation: 'All three are developer experience sub-variants — narrower than the scope of the problem and presupposes the cause before diagnosis.' },
              { option_label: 'D', option_text: 'Hypothesis 1: Developer setup friction. Hypothesis 2: Time-to-value too long during trial. Hypothesis 3: Enterprise features (SSO, audit logs) missing for this team size.', quality: 'good_but_incomplete', points: 2, competencies: ['domain_expertise'], explanation: 'Reasonable set, but hypothesis 2 and 3 partially overlap — enterprise features is one specific form of time-to-value friction for this segment. Slightly less distinct than the best option.' },
            ],
          },
        ],
      },
      {
        step: 'optimize',
        step_nudge: 'You have limited engineering bandwidth. Name the one hypothesis you would test first and what you give up by doing so.',
        grading_weight: 0.30,
        step_order: 3,
        questions: [
          {
            question_text: 'Data shows 60% of 5-15 person teams never make a second API call after the first. What is the right first intervention?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'creative_execution'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Ship a team onboarding flow with shared API key management and a guided first-integration walkthrough, accepting the sacrifice of 2 weeks of other roadmap work', quality: 'best', points: 3, competencies: ['strategic_thinking', 'creative_execution'], explanation: '60% of teams stopping after call one points to setup or first-output friction. A guided team onboarding directly addresses this, and naming the 2-week roadmap sacrifice is the honest tradeoff.' },
              { option_label: 'B', option_text: 'Extend the trial from 14 days to 30 days to give teams more time to complete their integration', quality: 'good_but_incomplete', points: 2, competencies: ['cognitive_empathy'], explanation: 'More time helps if time-to-value is the bottleneck, but if teams are stopping after call one due to friction, extra time alone does not remove that friction.' },
              { option_label: 'C', option_text: 'Email every trial user who made fewer than 3 API calls with a personal note from the developer relations team', quality: 'surface', points: 1, competencies: [], explanation: 'Manual outreach can surface qualitative signal, but it is not a scalable fix and does not address the product gap. It is a research method, not an intervention.' },
              { option_label: 'D', option_text: 'Reduce pricing for the 5-15 person tier to lower the financial risk of committing to a trial', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Pricing as the first lever is premature. The drop-off after call one suggests the team never gets to the point of evaluating value, so price is not the deciding factor yet.' },
            ],
          },
        ],
      },
      {
        step: 'win',
        step_nudge: 'What is the specific, testable prediction you would make before shipping the onboarding fix?',
        grading_weight: 0.20,
        step_order: 4,
        questions: [
          {
            question_text: 'What does success look like for the team onboarding fix at the 60-day mark?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: '5-15 person team conversion returns to 28%+ (near pre-drop baseline) AND second API call rate within trial increases to above 50%', quality: 'best', points: 3, competencies: ['strategic_thinking'], explanation: 'Two linked metrics: the north star (conversion rate recovery) and the leading indicator (second API call rate). If the leading indicator moves but conversion does not, there is a second bottleneck downstream.' },
              { option_label: 'B', option_text: 'Overall platform trial-to-paid conversion returns to 31%', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Overall conversion is the right long-term target but too broad to attribute to this specific fix. Segment-level measurement is needed to confirm causation.' },
              { option_label: 'C', option_text: 'User satisfaction scores on the onboarding experience above 4.0 out of 5', quality: 'surface', points: 1, competencies: [], explanation: 'Satisfaction is a perception metric. Teams can rate onboarding positively and still not convert — the question is whether they ship something with the API, not whether they enjoyed setup.' },
              { option_label: 'D', option_text: 'Zero teams report confusion about API key sharing in support tickets', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Support ticket reduction is a lagging and sparse signal. Most stuck teams do not file tickets — they just leave.' },
            ],
          },
        ],
      },
    ],
  },

  {
    id: 'pm-anthropic-004',
    title: 'Positioning Against a More Capable but Less Safe Competitor',
    scenario_role: 'Tech Lead, Product Strategy',
    scenario_context: 'A major AI lab releases a model that outperforms Claude on most standard benchmarks. The new model scores 12 points higher on HumanEval and 8 points higher on MMLU. Early developer feedback on X is enthusiastic. Anthropic\'s enterprise sales team reports three prospective deals where the competitor was cited as a reason for delay.',
    scenario_trigger: 'The safety team publishes a third-party audit showing the competitor\'s model produces harmful outputs at 3.8x the rate of Claude 3 Opus on a standardized red-team benchmark.',
    scenario_question: 'How would you position Anthropic\'s offerings in market messaging and sales conversations, given this competitive dynamic?',
    engineer_standout: 'An engineer would ask whether the benchmark advantage is relevant for the actual use cases being sold — code completion benchmarks do not predict performance on open-ended enterprise workflows. Competitive positioning should be grounded in use-case-specific performance, not general benchmark rankings.',
    paradigm: 'ai_native',
    industry: 'AI Tooling',
    sub_vertical: 'Enterprise AI Platform',
    difficulty: 'advanced',
    estimated_minutes: 20,
    primary_competencies: ['strategic_thinking', 'domain_expertise'],
    secondary_competencies: ['creative_execution'],
    frameworks: ['Competitive Positioning', 'Jobs To Be Done'],
    relevant_roles: ['pm', 'tech_lead', 'em', 'swe'],
    company_tags: ['Anthropic', 'OpenAI', 'Google DeepMind'],
    tags: ['strategy', 'competitive', 'positioning', 'safety', 'enterprise', 'anthropic'],
    is_published: true,
    is_calibration: false,
    is_premium: false,
    steps: [
      {
        step: 'frame',
        step_nudge: 'Before deciding what to say about the competitor, what is the actual purchase decision the three stalled enterprise deals are making?',
        grading_weight: 0.25,
        step_order: 1,
        questions: [
          {
            question_text: 'What is the most accurate framing of the competitive situation?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'domain_expertise'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Benchmark superiority will drive enterprise purchasing decisions and Anthropic needs to close the capability gap quickly or lose the market', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Enterprise buyers rarely purchase on benchmark rankings. Procurement is driven by risk tolerance, compliance requirements, integration support, and use-case fit — all of which are upstream of HumanEval scores.' },
              { option_label: 'B', option_text: 'The three stalled deals are likely evaluating a different dimension than raw capability — safety audit results and compliance posture may matter more than benchmark scores for their risk profile', quality: 'best', points: 3, competencies: ['strategic_thinking', 'domain_expertise'], explanation: 'Enterprise sales stalls are rarely about capability alone. The safety audit data (3.8x harmful output rate) is directly relevant to enterprise risk teams, legal, and compliance — the actual decision-makers in large organizations.' },
              { option_label: 'C', option_text: 'Anthropic should acknowledge the benchmark gap publicly and redirect the narrative to safety as a core differentiator', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Safety as differentiator is the right direction, but leading with public acknowledgment of benchmark gaps before understanding what the stalled deals actually care about is backwards.' },
              { option_label: 'D', option_text: 'Developer enthusiasm for the competitor on X will translate to enterprise adoption within 6 months, making this an urgent crisis requiring immediate product response', quality: 'surface', points: 1, competencies: [], explanation: 'Developer X sentiment and enterprise procurement are different markets on different timelines. Enterprise sales cycles are 3-12 months, during which the competitive landscape will continue to shift.' },
            ],
          },
        ],
      },
      {
        step: 'list',
        step_nudge: 'What are the structurally distinct positioning angles available, and what does each one require to be credible?',
        grading_weight: 0.25,
        step_order: 2,
        questions: [
          {
            question_text: 'Which set of positioning options is most distinct and credible given the available data?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'creative_execution'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Angle 1: Claude is safer (cite the 3.8x audit). Angle 2: Claude is better for specific enterprise use cases where reliability matters more than peak performance. Angle 3: Anthropic has a stronger Constitutional AI research track record that predicts long-term safety compliance.', quality: 'best', points: 3, competencies: ['strategic_thinking', 'creative_execution'], explanation: 'Three structurally distinct angles: current measured safety outcome, use-case-specific performance, and research credibility as a forward-looking predictor. Each is independently verifiable and speaks to a different buyer concern.' },
              { option_label: 'B', option_text: 'Angle 1: Claude is safer. Angle 2: Claude is more trustworthy. Angle 3: Claude is better for responsible AI use cases.', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'All three angles say the same thing in different words. This is not a set of distinct options — it is one talking point repeated three times.' },
              { option_label: 'C', option_text: 'Angle 1: Benchmark scores do not predict real-world performance. Angle 2: Benchmark scores favor narrow tasks. Angle 3: Benchmark scores are manipulable by competitors.', quality: 'surface', points: 1, competencies: ['strategic_thinking'], explanation: 'All three attack benchmark validity. While true, a purely defensive positioning (what Claude is not) is weaker than positive differentiation (what Claude is).' },
              { option_label: 'D', option_text: 'Angle 1: Safety for regulated industries (finance, healthcare). Angle 2: Better benchmark parity is coming with the next model release. Angle 3: Anthropic\'s enterprise support SLAs are stronger.', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Reasonable angles, but angle 2 (next model release) is a future promise that weakens the current position and may stall deals further while buyers wait.' },
            ],
          },
        ],
      },
      {
        step: 'optimize',
        step_nudge: 'Name the primary criterion for the positioning strategy and what you sacrifice by optimizing for it.',
        grading_weight: 0.30,
        step_order: 3,
        questions: [
          {
            question_text: 'For the three stalled enterprise deals, what is the highest-leverage positioning move in the next 30 days?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'domain_expertise'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Commission a use-case-specific comparison showing Claude performance on the exact workflows each stalled deal cares about, accepting that this takes 3-4 weeks and delays the response', quality: 'best', points: 3, competencies: ['strategic_thinking', 'domain_expertise'], explanation: 'Tailored evidence beats general positioning for late-stage deals. Optimizing for deal-specific credibility over speed is the right criterion at the enterprise sales stage. Naming the 3-4 week sacrifice is honest.' },
              { option_label: 'B', option_text: 'Lead every sales conversation with the 3.8x safety audit finding — use it as the primary objection handler for competitor mentions', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Safety audit data is genuinely useful, but leading every conversation with the same data regardless of what the deal cares about is not strategic — it is a playbook, not positioning.' },
              { option_label: 'C', option_text: 'Reduce price for the three deals to compensate for the perceived capability disadvantage', quality: 'surface', points: 1, competencies: [], explanation: 'Price concession signals that you agree the product is inferior and trains enterprise buyers to request discounts in every future deal. It does not address the capability perception.' },
              { option_label: 'D', option_text: 'Announce a Claude 4 preview to signal that the benchmark gap will be closed, giving deals a reason to wait for Anthropic', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Announcing unreleased products to stall competitors is risky. If the preview does not materialize on schedule, it damages credibility. It also does not address what the buyer needs today.' },
            ],
          },
        ],
      },
      {
        step: 'win',
        step_nudge: 'What is the specific outcome that tells you the positioning strategy worked — and how soon would you see it?',
        grading_weight: 0.20,
        step_order: 4,
        questions: [
          {
            question_text: 'What is the leading indicator that the repositioning around safety is landing with enterprise buyers?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Security and compliance teams are brought into evaluation conversations within the first two meetings — not just technical teams', quality: 'best', points: 3, competencies: ['strategic_thinking'], explanation: 'When safety positioning is working, it elevates the conversation to the buyers who own risk decisions. Compliance and legal involvement at the table is a leading behavioral indicator — visible before any contract closes.' },
              { option_label: 'B', option_text: 'Win rate against the competitor returns to pre-announcement levels within 90 days', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Win rate is the right ultimate metric but is a lagging indicator. It will not tell you if the positioning is working until after the 90-day window, too late to course-correct in flight.' },
              { option_label: 'C', option_text: 'Positive coverage of the 3.8x safety audit finding in AI industry media within two weeks', quality: 'surface', points: 1, competencies: [], explanation: 'Media coverage is a brand metric, not a sales metric. Enterprise deals do not correlate strongly with press coverage of audit findings.' },
              { option_label: 'D', option_text: 'All three stalled deals close within 60 days', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Deal closure is the goal, but enterprise sales have too many variables for a 60-day close to be a valid positioning test. Three deals is not a statistically meaningful sample.' },
            ],
          },
        ],
      },
    ],
  },

  {
    id: 'pm-anthropic-005',
    title: 'Measuring Whether a Safety Feature Actually Builds Trust',
    scenario_role: 'Staff Engineer, AI Products',
    scenario_context: 'The team ships a new "Sources" panel in a Claude-powered research assistant. The panel surfaces the documents and web pages the model drew on for each response. The hypothesis is that showing sources will increase user trust and long-session engagement. Three weeks post-launch, sources are visible on 100% of eligible responses.',
    scenario_trigger: 'The metrics dashboard shows no statistically significant change in session length, return rate, or the "Did this help?" thumbs rating since launch. The PM wants to know if the feature failed.',
    scenario_question: 'How would you measure whether the Sources panel is improving user trust, and what would you change if it is not?',
    engineer_standout: 'An engineer would immediately ask whether the metric is sensitive enough to detect trust changes. Trust is a latent variable — session length and thumbs ratings may not move even when trust improves if users lack another option or use the product for a different reason than the hypothesized one.',
    paradigm: 'ai_assisted',
    industry: 'AI Tooling',
    sub_vertical: 'Research Assistant',
    difficulty: 'standard',
    estimated_minutes: 18,
    primary_competencies: ['strategic_thinking', 'domain_expertise'],
    secondary_competencies: ['cognitive_empathy'],
    frameworks: ['North Star Framework', 'Trust Calibration'],
    relevant_roles: ['ml_eng', 'swe', 'pm', 'data_eng'],
    company_tags: ['Anthropic', 'Perplexity', 'You.com', 'Bing Chat'],
    tags: ['metrics', 'trust', 'measurement', 'research-assistant', 'anthropic'],
    is_published: true,
    is_calibration: false,
    is_premium: false,
    steps: [
      {
        step: 'frame',
        step_nudge: 'What is the problem with using session length and thumbs ratings to measure trust — and what would a better proxy look like?',
        grading_weight: 0.25,
        step_order: 1,
        questions: [
          {
            question_text: 'What is the most accurate framing of why the metrics are not moving?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'domain_expertise'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'The feature failed — users do not value sources and the design should be reconsidered', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Flat metrics do not mean failure. They may mean the metrics chosen are not sensitive to the outcome being measured. Concluding failure before examining metric validity is a diagnostic error.' },
              { option_label: 'B', option_text: 'Session length and thumbs ratings measure task completion and output quality, not trust — trust would show up in different behavioral signals like source click-through, content sharing, and task escalation patterns', quality: 'best', points: 3, competencies: ['strategic_thinking', 'domain_expertise'], explanation: 'This is the measurement validity problem. Trust is a latent variable that surfaces in specific behaviors — whether users act on information, share it, escalate it, or verify it — not in coarse engagement signals.' },
              { option_label: 'C', option_text: 'Three weeks is too short to measure trust change, which is a long-term shift in user belief that requires months of consistent exposure', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Time horizon is a valid concern, but the more fundamental issue is that even with more time, session length and thumbs may never be sensitive to trust. Both problems need addressing.' },
              { option_label: 'D', option_text: 'The sources panel is not visible enough in the UI — users may not know it exists, so there is no exposure effect to measure', quality: 'surface', points: 1, competencies: ['taste'], explanation: 'Discoverability is worth checking, but the question states sources are visible on 100% of eligible responses. The problem is metric sensitivity, not feature awareness.' },
            ],
          },
        ],
      },
      {
        step: 'list',
        step_nudge: 'What behavioral signals would indicate that users are trusting the output enough to act on it — and how do you distinguish trust from mere task completion?',
        grading_weight: 0.25,
        step_order: 2,
        questions: [
          {
            question_text: 'Which set of metrics best operationalizes "trust" as a measurable behavior in a research assistant?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['domain_expertise', 'creative_execution'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Source click-through rate (user verified the source), content copy rate (user acted on the output), external share rate (user trusted it enough to send to someone else)', quality: 'best', points: 3, competencies: ['domain_expertise', 'creative_execution'], explanation: 'Three behaviorally distinct trust signals: verification behavior (clicking sources), action behavior (copying), and endorsement behavior (sharing). Each is observable and maps to a real trust decision.' },
              { option_label: 'B', option_text: 'Net Promoter Score from monthly surveys and in-app trust rating after each response', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Self-reported trust is subject to social desirability bias and does not predict behavior. Users say they trust a product but still verify everything manually.' },
              { option_label: 'C', option_text: 'Session length, pages visited per session, and 7-day return rate', quality: 'surface', points: 1, competencies: [], explanation: 'These are the same engagement metrics already showing no movement. Adding more engagement metrics without a theory of how they connect to trust does not improve diagnostic power.' },
              { option_label: 'D', option_text: 'Sources panel open rate and time spent reading sources', quality: 'good_but_incomplete', points: 2, competencies: ['domain_expertise'], explanation: 'Sources engagement measures awareness and use of the feature, but not whether it changed trust outcomes. A user can read sources and still not trust the output, or trust the output without reading sources.' },
            ],
          },
        ],
      },
      {
        step: 'optimize',
        step_nudge: 'If you could only ship one change to the Sources panel in the next sprint, what is it and what are you explicitly giving up?',
        grading_weight: 0.30,
        step_order: 3,
        questions: [
          {
            question_text: 'Source click-through data shows users open 1 in 12 sources on average. You have one sprint. What is the highest-leverage change?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'taste'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Surface the single most credible source inline with the specific claim it supports, rather than listing all sources in a panel — optimizing for trust signal quality over source completeness', quality: 'best', points: 3, competencies: ['strategic_thinking', 'taste'], explanation: 'Inline citation at the claim level is a proven pattern (Perplexity, Bing Chat). It gives users a trust signal where they need it, not where sources were architecturally easy to surface. The sacrifice is showing fewer sources overall.' },
              { option_label: 'B', option_text: 'Add source quality indicators (publication reputation score) to help users evaluate whether to trust a source', quality: 'good_but_incomplete', points: 2, competencies: ['domain_expertise'], explanation: 'Quality signals help users who already open sources, but do not address why 11 out of 12 sources go unopened. Improving the panel does not solve the discoverability and motivation problem.' },
              { option_label: 'C', option_text: 'Increase the default visibility of the Sources panel by moving it above the response text', quality: 'surface', points: 1, competencies: ['taste'], explanation: 'Prominence increases exposure but may not increase trust if the fundamental interaction model (list of links) is not what users need in the moment.' },
              { option_label: 'D', option_text: 'A/B test sources on versus off across 50% of sessions to get a clean causal estimate of the feature\'s effect on engagement', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'The engagement metrics are already established as insensitive to trust. Running more experiments with the same metrics will not produce useful signal, and withholding sources from 50% of users is a product regression.' },
            ],
          },
        ],
      },
      {
        step: 'win',
        step_nudge: 'Write a crisp recommendation to the PM: did the Sources feature work, what specifically would you measure going forward, and what is the next test?',
        grading_weight: 0.20,
        step_order: 4,
        questions: [
          {
            question_text: 'What is the correct verdict on the Sources panel after three weeks, and what is the next concrete action?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'creative_execution'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'The panel cannot be evaluated on current metrics — instrument source click-through, content copy rate, and external share rate, then run a 30-day measurement window before drawing a conclusion. In parallel, ship inline citation to the 10% of power users with highest copy rates as a faster iteration loop.', quality: 'best', points: 3, competencies: ['strategic_thinking', 'creative_execution'], explanation: 'Correct sequence: admit the measurement is invalid, define better metrics, and run a parallel iteration on the design for the most engaged users. Does not over-conclude from bad data.' },
              { option_label: 'B', option_text: 'The feature failed to improve engagement and should be deprioritized in the next roadmap cycle while better ideas are explored', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Concluding failure from metrics that were never valid for measuring the outcome is a false negative. This writes off a potentially working feature based on wrong evidence.' },
              { option_label: 'C', option_text: 'The feature needs more time — run the same metrics for 90 days before deciding', quality: 'surface', points: 1, competencies: [], explanation: 'More time with the same insensitive metrics produces the same uninformative result. Time is not the variable that needs to change.' },
              { option_label: 'D', option_text: 'Run a user survey asking: "Did the Sources panel increase your trust in the response?" and use the results to decide whether to continue the feature', quality: 'good_but_incomplete', points: 2, competencies: ['cognitive_empathy'], explanation: 'Survey self-report is better than nothing and produces qualitative signal, but self-reported trust does not predict behavior, and survey response rates will be too low to be conclusive.' },
            ],
          },
        ],
      },
    ],
  },

  {
    id: 'pm-perplexity-001',
    title: 'Defining Success for an AI Feature at Perplexity',
    scenario_role: 'Tech Lead, Search Products',
    scenario_context: 'Perplexity ships a new "Deep Research" feature that generates multi-page research reports from a single query, citing dozens of sources. The feature takes 2-4 minutes to complete versus 5 seconds for a standard answer. The team needs to decide whether to invest in scaling it or roll it back.',
    scenario_trigger: 'Week-2 data shows Deep Research queries represent 4% of volume but 22% of Pro subscription upgrades in the same session. Average revenue per user on weeks with Deep Research use is 2.1x the control group.',
    scenario_question: 'How would you define success for the Deep Research feature, and what would you prioritize measuring to make the scaling decision?',
    engineer_standout: 'An engineer would immediately recognize that 4% query volume does not mean 4% of user value — the conversion and ARPU signals suggest Deep Research is a premium purchase trigger, not a mass-use feature. The engineering scaling question depends on whether to optimize for query volume or purchase event density.',
    paradigm: 'ai_native',
    industry: 'Search / Information Retrieval',
    sub_vertical: 'AI-Powered Search',
    difficulty: 'standard',
    estimated_minutes: 18,
    primary_competencies: ['strategic_thinking', 'domain_expertise'],
    secondary_competencies: ['motivation_theory'],
    frameworks: ['North Star Framework', 'Jobs To Be Done'],
    relevant_roles: ['swe', 'ml_eng', 'pm', 'data_eng'],
    company_tags: ['Perplexity', 'Bing Chat', 'You.com', 'Google SGE'],
    tags: ['metrics', 'ai-features', 'success-definition', 'perplexity', 'monetization'],
    is_published: true,
    is_calibration: false,
    is_premium: false,
    steps: [
      {
        step: 'frame',
        step_nudge: 'What is the actual job this feature is doing in the product system — is it a use case or something else entirely?',
        grading_weight: 0.25,
        step_order: 1,
        questions: [
          {
            question_text: 'What is the most accurate framing of Deep Research\'s role in the Perplexity product?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'motivation_theory'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Deep Research is a premium feature for power users and should be optimized for the 4% who use it most frequently', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'This is directionally correct but misses the more important insight: the conversion signal suggests Deep Research is functioning as a purchase trigger for users who were not going to convert otherwise.' },
              { option_label: 'B', option_text: 'Deep Research is functioning as a trial-to-paid conversion mechanism — the experience of generating a deep report is what convinces users that Perplexity Pro is worth paying for', quality: 'best', points: 3, competencies: ['strategic_thinking', 'motivation_theory'], explanation: '22% of Pro upgrades happening in the same session as a Deep Research query, despite only 4% query volume, is a conversion funnel signal. The feature\'s primary value may be what it demonstrates about Pro, not what it does at scale.' },
              { option_label: 'C', option_text: 'Deep Research is a costly feature with low adoption and the 2-4 minute latency is the reason it is not scaling — the problem to solve is speed', quality: 'surface', points: 1, competencies: ['domain_expertise'], explanation: 'Latency may be a constraint, but it is not the framing problem. The data shows the feature is working as a value signal at low frequency. Optimizing for speed does not address the strategic question.' },
              { option_label: 'D', option_text: 'The 4% volume means Deep Research is not differentiated enough and needs to be promoted more aggressively to drive mass adoption', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Forcing mass adoption of a 2-4 minute query on a fast-search product would degrade the core experience. Low volume + high conversion signal is often the right profile for a premium trigger, not a sign of marketing failure.' },
            ],
          },
        ],
      },
      {
        step: 'list',
        step_nudge: 'Map out all the distinct things "success" could mean for this feature — they are not all the same goal.',
        grading_weight: 0.25,
        step_order: 2,
        questions: [
          {
            question_text: 'Which set of success definitions is most structurally distinct for an AI feature like Deep Research?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'domain_expertise'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Success Type 1: Usage frequency (query volume grows to 15%+). Success Type 2: Conversion leverage (Pro upgrade rate in Deep Research sessions stays above 20%). Success Type 3: Retention signal (users who do Deep Research have 40%+ lower 30-day churn).', quality: 'best', points: 3, competencies: ['strategic_thinking', 'domain_expertise'], explanation: 'Three structurally distinct success types: volume (reach), conversion (revenue leverage), and retention (LTV contribution). Each points to different investment decisions and different scaling priorities.' },
              { option_label: 'B', option_text: 'Success Type 1: Users are happy with report quality. Success Type 2: Users find sources credible. Success Type 3: Users would recommend Deep Research to a friend.', quality: 'surface', points: 1, competencies: [], explanation: 'All three are perception-based satisfaction metrics. They do not distinguish between different business outcomes and cannot inform the scaling decision between infrastructure investment and rollback.' },
              { option_label: 'C', option_text: 'Success Type 1: Reduces cost per query. Success Type 2: Improves gross margin on Pro tier. Success Type 3: Infrastructure scales without engineering intervention.', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'All three success types are operational efficiency metrics, which answer the wrong question. The scaling decision is about user and business value, not operational self-sufficiency.' },
              { option_label: 'D', option_text: 'Success Type 1: High Pro conversion in Deep Research sessions. Success Type 2: High Pro upgrade rate overall.', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Two is better than one but both types are in the same category (conversion). This misses usage frequency and retention as independent success dimensions.' },
            ],
          },
        ],
      },
      {
        step: 'optimize',
        step_nudge: 'You have a budget to scale either infrastructure for faster queries or a better discovery flow for the feature. Name the criterion and sacrifice for each choice.',
        grading_weight: 0.30,
        step_order: 3,
        questions: [
          {
            question_text: 'Given the conversion data, what is the highest-leverage investment for Deep Research in the next quarter?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'creative_execution'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Invest in discovery: show Deep Research as a prominent upgrade prompt when users submit complex queries, accepting the sacrifice of some search-result-first UX purity', quality: 'best', points: 3, competencies: ['strategic_thinking', 'creative_execution'], explanation: 'If Deep Research is a conversion trigger, the constraint is discovery — only 4% of queries reach it. Improving how users encounter Deep Research before they would have converted otherwise is the highest-leverage move.' },
              { option_label: 'B', option_text: 'Invest in infrastructure to reduce query time from 2-4 minutes to under 60 seconds, accepting the engineering cost as justified by improved mass-market appeal', quality: 'good_but_incomplete', points: 2, competencies: ['domain_expertise'], explanation: 'Speed improvement is real product value, but it does not address the discovery bottleneck. Users who never try Deep Research are not held back by latency — they do not know it exists for their use case.' },
              { option_label: 'C', option_text: 'Invest in report quality — longer sources, better synthesis — to justify the 2-4 minute wait and increase satisfaction scores', quality: 'surface', points: 1, competencies: ['taste'], explanation: 'Quality improvement is correct for retention but misapplied here. Users who generate one report and then upgrade to Pro are already satisfied enough. The bottleneck is pre-trial exposure.' },
              { option_label: 'D', option_text: 'Restrict Deep Research to Pro subscribers only to create an exclusive feature that justifies Pro pricing', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'If Deep Research is the conversion trigger for free-to-Pro, gating it to Pro subscribers eliminates the mechanism. Users cannot upgrade to access a feature they have never experienced.' },
            ],
          },
        ],
      },
      {
        step: 'win',
        step_nudge: 'Write the falsifiable hypothesis you would test in the next 45 days and how you would know if it was right.',
        grading_weight: 0.20,
        step_order: 4,
        questions: [
          {
            question_text: 'What is the specific prediction that would confirm Deep Research is a conversion driver worth scaling?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'If we surface Deep Research as an upgrade prompt on complex queries for free users, Pro conversion in the treatment group will be at least 8 percentage points higher than the control group within 45 days', quality: 'best', points: 3, competencies: ['strategic_thinking'], explanation: 'Crisp, falsifiable, and directly tests the conversion driver hypothesis. 8 percentage points is specific enough to be meaningful and small enough to be achievable. Falsifies cleanly in either direction.' },
              { option_label: 'B', option_text: 'Deep Research will become the most-used Pro feature by query volume within 90 days if we invest in it', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'This prediction targets query volume, which contradicts the insight that Deep Research value comes from low-frequency, high-conversion use. Maximum volume is the wrong goal.' },
              { option_label: 'C', option_text: 'Users who try Deep Research will rate it higher than standard search on quality surveys', quality: 'surface', points: 1, competencies: [], explanation: 'Quality perception is not the scaling decision variable. Users can prefer Deep Research and still not convert to Pro.' },
              { option_label: 'D', option_text: 'Pro churn will decrease by 5% among users who use Deep Research at least once per week', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Retention prediction is valid and worth testing, but it measures retention after subscription, not conversion from free. The most urgent question is whether Deep Research drives more upgrades.' },
            ],
          },
        ],
      },
    ],
  },

  {
    id: 'pm-meta-001',
    title: 'Diagnosing Declining Comments per Post on Facebook',
    scenario_role: 'Tech Lead, Feed Ranking',
    scenario_context: 'Facebook\'s engagement metrics show average comments per post has declined 14% over the past two quarters across all post types. Likes, reactions, and shares have remained stable. The ranking team suspects Feed algorithm changes from six months ago may be involved, but no single change was large enough to explain the drop on its own.',
    scenario_trigger: 'The integrity team flags that comment spam detection was tuned in the same window, which removed 18% more comments as spam — some of which may have been legitimate.',
    scenario_question: 'How would you diagnose the root cause of declining average comments per post before committing to any product changes?',
    engineer_standout: 'An engineer would immediately ask whether the 14% average decline is masking different signals in different segments. A drop in average can come from fewer comments on most posts, fewer posts getting any comments, or a segment of high-comment posts disappearing. Each implies a different root cause.',
    paradigm: 'traditional',
    industry: 'Social Media',
    sub_vertical: 'Feed and Engagement',
    difficulty: 'standard',
    estimated_minutes: 18,
    primary_competencies: ['strategic_thinking', 'domain_expertise'],
    secondary_competencies: ['cognitive_empathy'],
    frameworks: ['Funnel Analysis', 'Root Cause Analysis'],
    relevant_roles: ['swe', 'ml_eng', 'pm', 'data_eng', 'tech_lead'],
    company_tags: ['Meta', 'Facebook', 'Instagram', 'Twitter/X'],
    tags: ['metrics', 'engagement', 'comments', 'diagnosis', 'meta', 'feed'],
    is_published: true,
    is_calibration: false,
    is_premium: false,
    steps: [
      {
        step: 'frame',
        step_nudge: 'What does "average comments per post" actually hide — and what would you need to decompose it into before you can locate the root cause?',
        grading_weight: 0.25,
        step_order: 1,
        questions: [
          {
            question_text: 'What is the most useful decomposition of the "average comments per post" metric?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'domain_expertise'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Segment by post type (photo, video, text, link) to see which format drove the decline', quality: 'good_but_incomplete', points: 2, competencies: ['domain_expertise'], explanation: 'Post type segmentation is useful but still operates on the average. It does not reveal whether the distribution of comments is shifting (fewer posts getting many comments) versus a flat decline across all posts.' },
              { option_label: 'B', option_text: 'Decompose into: (1) % of posts receiving zero comments, (2) median comments per commented post, (3) comments removed by spam filter — to separate distribution shift from volume decline from algorithmic removal', quality: 'best', points: 3, competencies: ['strategic_thinking', 'domain_expertise'], explanation: 'This decomposition separates three mechanistically distinct causes. If (1) is rising, fewer posts are comment-worthy. If (2) is flat but (1) rises, the commenting behavior is unchanged but reach is. If (3) is large, the spam filter is a primary suspect.' },
              { option_label: 'C', option_text: 'Look at whether the decline correlates with the Feed algorithm change timeline', quality: 'surface', points: 1, competencies: ['strategic_thinking'], explanation: 'Timeline correlation is a useful starting heuristic but does not distinguish cause from coincidence. The spam filter also changed in the same window.' },
              { option_label: 'D', option_text: 'Compare average comments per post for active users versus all users to see if the decline is driven by inactive user base growth', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'User activity segmentation is relevant for retention analysis but unlikely to explain a 14% comments-per-post decline if likes and reactions are stable. The metric mismatch makes this the wrong primary decomposition.' },
            ],
          },
        ],
      },
      {
        step: 'list',
        step_nudge: 'List the structurally distinct hypotheses for what is causing the decline — they should each point to a different part of the system.',
        grading_weight: 0.25,
        step_order: 2,
        questions: [
          {
            question_text: 'Which set of hypotheses best covers the distinct root causes for declining comments per post?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['domain_expertise', 'strategic_thinking'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'H1: Spam filter over-removal (system artifact). H2: Feed ranking deprioritizes comment-heavy posts, reducing comment-amplification loop. H3: Content mix shifting toward video and Stories, which attract fewer comments than text/photo. H4: User behavior shift toward private reactions (DMs, reactions) over public comments.', quality: 'best', points: 3, competencies: ['domain_expertise', 'strategic_thinking'], explanation: 'Four hypotheses from four distinct system layers: algorithmic moderation (spam filter), algorithmic distribution (ranking), content mix, and user behavior. Each requires different evidence and a different fix.' },
              { option_label: 'B', option_text: 'H1: Spam filter removed too many comments. H2: Algorithm suppressed comments. H3: Spam filter made users comment less.', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'All three hypotheses are variations on the spam filter. This list fails the width test and would concentrate investigation on one variable while missing content mix and behavioral shifts.' },
              { option_label: 'C', option_text: 'H1: Users are spending less time on Facebook overall. H2: Users prefer Instagram or TikTok for social interaction. H3: Feed is less engaging than it was.', quality: 'surface', points: 1, competencies: [], explanation: 'These are high-level competitor or engagement narratives that are not specific enough to test or act on. They do not point to a specific system component that can be changed.' },
              { option_label: 'D', option_text: 'H1: Spam filter over-removal. H2: Feed algorithm change. H3: Content mix shift toward video.', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Three distinct system layers, but missing the user behavior dimension (shift to private reactions/DMs) which is a plausible and independently testable cause.' },
            ],
          },
        ],
      },
      {
        step: 'optimize',
        step_nudge: 'You can only investigate one hypothesis first. Name the criterion for choosing it and what you give up.',
        grading_weight: 0.30,
        step_order: 3,
        questions: [
          {
            question_text: 'Data confirms: 18% of removed comments from the spam filter window were false positives. What is the correct next step?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'domain_expertise'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Roll back the spam filter change entirely and measure how much of the 14% decline recovers, accepting the sacrifice of more spam appearing while the investigation continues', quality: 'best', points: 3, competencies: ['strategic_thinking', 'domain_expertise'], explanation: 'Rollback is the cleanest experimental test for the spam filter hypothesis. The recovery magnitude tells you exactly how much of the 14% is attributable to false positives, which informs whether other hypotheses need investigation.' },
              { option_label: 'B', option_text: 'Restore the specific false-positive comments that were removed and measure engagement lift', quality: 'good_but_incomplete', points: 2, competencies: ['domain_expertise'], explanation: 'Surgical restoration avoids reintroducing real spam, but restoring historical content into live feeds has unpredictable notification and ranking effects. Rollback of the filter logic is cleaner.' },
              { option_label: 'C', option_text: 'Start investigating the Feed ranking hypothesis in parallel before acting on spam, since the ranking change is more likely to be the primary cause', quality: 'surface', points: 1, competencies: [], explanation: 'Intuition-based prioritization without data support. The spam filter is the identified variable with a quantified false positive rate — it should be tested first before expanding the investigation.' },
              { option_label: 'D', option_text: 'Tune the spam filter to a lower sensitivity threshold and measure the comments per post change over 30 days', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Tuning forward does not recover the already-removed comments that caused the baseline to drop. The decline happened in the past window, not going forward.' },
            ],
          },
        ],
      },
      {
        step: 'win',
        step_nudge: 'After the spam filter rollback, what does the data need to show for you to close this investigation — and what would keep it open?',
        grading_weight: 0.20,
        step_order: 4,
        questions: [
          {
            question_text: 'Spam filter rollback recovers 6 percentage points of the 14% decline. What is the right conclusion and next action?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'The spam filter accounts for roughly half the decline. Fix the filter precision (keep the rollback in place, retrain on false positives), then investigate the ranking and content mix hypotheses for the remaining 8 points', quality: 'best', points: 3, competencies: ['strategic_thinking'], explanation: 'Correct attribution: 6 of 14 points explained, 8 still unexplained. The action sequence follows: fix the confirmed cause, then continue investigating the residual. This is rigorous incremental diagnosis.' },
              { option_label: 'B', option_text: 'The spam filter was the primary cause. Ship a retrained filter and close the investigation', quality: 'plausible_wrong', points: 0, competencies: [], explanation: '6 of 14 percentage points recovered means 57% of the decline is still unexplained. Closing the investigation prematurely leaves a significant metric gap undiagnosed.' },
              { option_label: 'C', option_text: 'The spam filter was a contributing factor but the bigger issue is elsewhere. Escalate to the Feed ranking team to investigate their changes', quality: 'surface', points: 1, competencies: ['cognitive_empathy'], explanation: 'Escalating without data makes the ranking team the owner of an unquantified problem. The right move is to continue the investigation with the remaining 8-point gap quantified.' },
              { option_label: 'D', option_text: 'Wait 60 days for the rollback effect to fully stabilize before concluding and moving to the next hypothesis', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Waiting for full stabilization is prudent, but 60 days is too long given a 14% metric gap that was already two quarters in the making. The residual investigation should run in parallel.' },
            ],
          },
        ],
      },
    ],
  },

  {
    id: 'pm-meta-002',
    title: 'Prioritizing Competing Requests from News Feed and Reels Teams',
    scenario_role: 'Tech Lead, Core Platform',
    scenario_context: 'Two major product teams at Facebook are requesting the same shared infrastructure resource: the relevance ranking pipeline. News Feed wants a 40% increase in model inference capacity to ship a real-time context feature. Reels wants the same capacity to reduce recommendation latency from 800ms to 200ms. Both requests have compelling engagement data. The infrastructure budget for Q3 covers one, not both.',
    scenario_trigger: 'The VP of Product asks for a recommendation by end of week, and both teams have escalated to their respective VPs, creating direct peer pressure on both sides.',
    scenario_question: 'How would you prioritize between the two teams\' competing requests given the organizational and technical constraints?',
    engineer_standout: 'An engineer would recognize that "capacity" is not one resource — inference throughput, latency, and model freshness have different cost structures. Before recommending split versus winner-take-all, they would ask whether the requests can be partially satisfied with different resource types, or whether the latency and throughput problems have different solutions.',
    paradigm: 'traditional',
    industry: 'Social Media',
    sub_vertical: 'Feed and Recommendation Systems',
    difficulty: 'advanced',
    estimated_minutes: 22,
    primary_competencies: ['strategic_thinking', 'cognitive_empathy'],
    secondary_competencies: ['domain_expertise', 'creative_execution'],
    frameworks: ['Stakeholder Alignment', 'Risk-Based Prioritization'],
    relevant_roles: ['tech_lead', 'em', 'pm', 'swe', 'ml_eng'],
    company_tags: ['Meta', 'Facebook', 'Instagram', 'TikTok'],
    tags: ['prioritization', 'strategy', 'stakeholders', 'meta', 'infrastructure', 'tradeoffs'],
    is_published: true,
    is_calibration: false,
    is_premium: false,
    steps: [
      {
        step: 'frame',
        step_nudge: 'Before choosing between the two teams, what information is missing that would make this a better decision — and whose job is it to get it?',
        grading_weight: 0.25,
        step_order: 1,
        questions: [
          {
            question_text: 'What is the most productive framing of the prioritization decision?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'domain_expertise'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'It is a political decision — whoever has the stronger VP relationship will win and the technical analysis is cover for a social outcome', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Organizational politics are real, but treating the decision as purely political skips the technical decomposition that might reveal a non-zero-sum solution. Political framing produces escalation, not resolution.' },
              { option_label: 'B', option_text: 'It is a resource decomposition problem first — "inference capacity" may not be one resource, and both requests may have different underlying bottlenecks that can be satisfied without a winner-take-all split', quality: 'best', points: 3, competencies: ['strategic_thinking', 'domain_expertise'], explanation: 'The most upstream question is whether the resource is actually fungible. If Reels latency is solved by caching or batching rather than raw throughput, the capacity conflict may be partially resolvable before prioritization.' },
              { option_label: 'C', option_text: 'It is a business impact question — run an incremental lift calculation for each team\'s feature and fund the one with higher expected ARPU impact', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Business impact analysis is correct and necessary, but doing it before understanding whether the resource conflict is real could produce the right answer for the wrong reason if the technical assumption is wrong.' },
              { option_label: 'D', option_text: 'It is a process failure — the organization should have a clearer infrastructure allocation framework so individual VP pressure does not drive these decisions', quality: 'surface', points: 1, competencies: ['cognitive_empathy'], explanation: 'Process critique is valid as a longer-term recommendation, but it does not resolve the immediate decision and deflects the responsibility to make a recommendation by end of week.' },
            ],
          },
        ],
      },
      {
        step: 'list',
        step_nudge: 'What are the structurally distinct paths to resolving this conflict — not all of them require choosing one team over the other?',
        grading_weight: 0.25,
        step_order: 2,
        questions: [
          {
            question_text: 'Which set of resolution paths is most structurally complete?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'creative_execution'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Path 1: Fund News Feed now, Reels in Q4. Path 2: Fund Reels now, News Feed in Q4. Path 3: 50/50 split with both teams building reduced-scope versions. Path 4: Investigate whether Reels latency can be solved with a different technical approach (caching, model distillation) that does not require the same capacity type.', quality: 'best', points: 3, competencies: ['strategic_thinking', 'creative_execution'], explanation: 'Four structurally distinct paths: sequential funding (two variants), split, and technical alternative. Path 4 is the non-obvious one that could dissolve the conflict rather than resolve it.' },
              { option_label: 'B', option_text: 'Path 1: Fund News Feed. Path 2: Fund Reels. Path 3: Delay both and re-evaluate in Q4.', quality: 'surface', points: 1, competencies: [], explanation: 'Three paths, all within the binary decision space (who gets the resource). Delay is a non-answer that pushes the conflict forward without new information.' },
              { option_label: 'C', option_text: 'Path 1: Let VPs negotiate directly. Path 2: Escalate to the CPO. Path 3: Use ROI analysis to decide.', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'All three paths are governance mechanisms, not resource resolution paths. They decide who decides, not what the right decision is. This avoids the technical and product analysis.' },
              { option_label: 'D', option_text: 'Path 1: Fund News Feed because Feed is the core product. Path 2: Fund Reels because latency is measurably hurting engagement. Path 3: Fund both by deferring another infrastructure investment.', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Three reasonable paths, but Path 3 (deferred investment) needs to name what is deferred and its cost. Missing the technical alternative path (distillation/caching for Reels) is the key gap.' },
            ],
          },
        ],
      },
      {
        step: 'optimize',
        step_nudge: 'Name the criterion you would use to choose and what you are explicitly sacrificing by using it.',
        grading_weight: 0.30,
        step_order: 3,
        questions: [
          {
            question_text: 'A 2-day technical investigation reveals Reels latency can be reduced from 800ms to 400ms with model distillation using existing capacity — not to 200ms. News Feed\'s real-time context feature has no technical alternative. What is the right recommendation?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'domain_expertise'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Fund News Feed\'s full request and ship the distillation fix for Reels — optimizing for total engagement impact delivered this quarter while sacrificing the 200ms Reels latency target until Q4 capacity arrives', quality: 'best', points: 3, competencies: ['strategic_thinking', 'domain_expertise'], explanation: 'This recommendation names the criterion (total impact this quarter) and the explicit sacrifice (Reels 200ms target delayed). It uses the technical investigation to dissolve part of the conflict rather than making a political choice.' },
              { option_label: 'B', option_text: 'Fund Reels at full capacity because latency reduction has a more direct causal path to engagement than News Feed\'s context feature', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Reasonable reasoning, but ignores that the technical investigation just showed Reels can get meaningful latency improvement without the capacity. Funding Reels fully when a partial alternative exists is over-allocation.' },
              { option_label: 'C', option_text: '50/50 split — give each team half the capacity, let them each ship reduced versions and measure results before Q4', quality: 'surface', points: 1, competencies: ['cognitive_empathy'], explanation: 'Equal split avoids the prioritization judgment but likely means neither team ships a meaningful improvement. News Feed real-time context requires the full capacity to function.' },
              { option_label: 'D', option_text: 'Escalate to the CPO with the technical findings and let the executive team make the final call', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'The VP asked for a recommendation by end of week, not an escalation. Presenting findings without a recommendation is not what was asked, and it shifts accountability upward without adding value.' },
            ],
          },
        ],
      },
      {
        step: 'win',
        step_nudge: 'How do you communicate this recommendation to both teams in a way that preserves the relationship and prevents the same conflict next quarter?',
        grading_weight: 0.20,
        step_order: 4,
        questions: [
          {
            question_text: 'What is the right way to communicate the prioritization decision to the Reels team, which did not get the full allocation?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['cognitive_empathy', 'creative_execution'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Share the technical investigation findings directly, explain that the distillation path delivers 400ms now (meaningful improvement from 800ms), commit to the remaining 200ms in Q4 with a specific capacity plan, and propose a shared infrastructure roadmap session to prevent future conflicts', quality: 'best', points: 3, competencies: ['cognitive_empathy', 'creative_execution'], explanation: 'Transparent reasoning, a concrete near-term win for Reels (400ms), a Q4 commitment, and a structural fix for the repeat scenario. All four elements are needed for the relationship to hold.' },
              { option_label: 'B', option_text: 'Send the VP a written summary of the decision rationale and let them communicate to the Reels team however they see fit', quality: 'surface', points: 1, competencies: [], explanation: 'Delegating communication to the VP avoids the direct conversation but loses the opportunity to explain the technical finding that partially helps Reels. The team lead is the right person to deliver technical context.' },
              { option_label: 'C', option_text: 'Tell the Reels team that this quarter\'s capacity was allocated to a higher-priority project based on business impact, and invite them to resubmit in Q4 planning', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Vague "higher priority" language without specifics reads as political dismissal and does not share the distillation option that partially resolves the Reels problem now.' },
              { option_label: 'D', option_text: 'Present the decision in the weekly leadership meeting so all stakeholders hear the reasoning at the same time and there is no information asymmetry', quality: 'good_but_incomplete', points: 2, competencies: ['cognitive_empathy'], explanation: 'Group transparency is good practice, but delivering a rejection in a group setting without a prior private conversation with the losing team is likely to create defensiveness rather than alignment.' },
            ],
          },
        ],
      },
    ],
  },
] as const
