/**
 * Seed data: 7 FLOW challenges from Meta PM interview questions (batch 3)
 *
 * Run:
 *   npx tsx scripts/seed-challenges-batch-3.ts
 *
 * Requires SUPABASE_SERVICE_ROLE_KEY + NEXT_PUBLIC_SUPABASE_URL in .env.local
 */

export const CHALLENGES = [
  {
    id: 'pm-meta-003',
    title: 'Teen Engagement When Parents Join Facebook',
    scenario_role: 'Data PM, Growth',
    scenario_context: 'Facebook growth data shows a correlation between parent sign-ups and a decline in the same-household teen\'s weekly sessions. The question is whether parents joining is causing the drop, or whether both events share a confounding cause like age or life stage.',
    scenario_trigger: 'A quarterly business review flags a 12% drop in 18-24 weekly active rate in markets where parental adoption grew fastest over the same period.',
    scenario_question: 'How do you design a measurement framework that separates correlation from causation, and determine whether parent presence on Facebook reduces teen engagement?',
    engineer_standout: 'A strong engineer would identify the need for a natural experiment or instrumental variable, distinguish between true causal effect and selection bias, and question whether the right metric is session frequency or content consumption depth.',
    paradigm: 'traditional',
    industry: 'Social Media',
    sub_vertical: 'Consumer Social',
    difficulty: 'advanced',
    estimated_minutes: 20,
    primary_competencies: ['strategic_thinking', 'domain_expertise'],
    secondary_competencies: ['cognitive_empathy'],
    frameworks: ['North Star Framework', 'Causal Inference'],
    relevant_roles: ['pm', 'data_eng', 'ml_eng'],
    company_tags: ['Meta', 'Instagram', 'TikTok'],
    tags: ['metrics', 'teen-engagement', 'causation', 'facebook', 'measurement'],
    is_published: true,
    is_calibration: false,
    is_premium: false,
    steps: [
      {
        step: 'frame',
        step_nudge: 'Before measuring impact, what structural problem makes this measurement genuinely hard?',
        grading_weight: 0.25,
        step_order: 1,
        questions: [
          {
            question_text: 'What is the core measurement challenge in isolating teen engagement impact from parent sign-ups?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'domain_expertise'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Privacy restrictions make it impossible to link parent and teen accounts at all', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Meta has household and family graph data. Privacy is a constraint on how data is used, not an absolute barrier to building household cohorts.' },
              { option_label: 'B', option_text: 'Parents and teens join Facebook at different life stages, so any observed engagement drop may reflect organic teen attrition rather than a causal parent effect', quality: 'best', points: 3, competencies: ['strategic_thinking', 'domain_expertise'], explanation: 'Selection bias is the core problem. Teens who still use Facebook when parents join are already a different cohort from those who had already churned, making the correlation misleading.' },
              { option_label: 'C', option_text: 'Teen engagement has too many variables (TikTok, school, seasons) to isolate any single cause', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'True but generic. Every product metric has confounders. The specific structural problem here is household-level selection bias, not general noise.' },
              { option_label: 'D', option_text: 'The 18-24 cohort definition is too broad because it includes college students and young workers with different usage patterns', quality: 'surface', points: 1, competencies: ['domain_expertise'], explanation: 'Segment refinement is good practice but does not address the fundamental causation problem. You can refine the cohort and still draw a spurious conclusion.' },
            ],
          },
        ],
      },
      {
        step: 'list',
        step_nudge: 'What data approaches could distinguish a genuine causal effect from selection bias?',
        grading_weight: 0.25,
        step_order: 2,
        questions: [
          {
            question_text: 'Which research design best isolates the causal effect of parent sign-up on teen engagement?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'domain_expertise'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Survey teens asking whether they use Facebook less after a parent joined', quality: 'surface', points: 1, competencies: ['cognitive_empathy'], explanation: 'Self-report introduces recall bias and social desirability effects. Behavioral data is the right instrument for this kind of question.' },
              { option_label: 'B', option_text: 'Compare engagement trends for teens whose parent joined last month against a matched cohort of teens with no parent account, using pre-period behavior as the baseline', quality: 'best', points: 3, competencies: ['strategic_thinking', 'domain_expertise'], explanation: 'Difference-in-differences with a matched control is the correct causal design here. Pre-period baseline controls for pre-existing trends; matching controls for household characteristics.' },
              { option_label: 'C', option_text: 'Track teens in markets where Facebook ran parent-targeted ad campaigns versus those where it did not', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Using a campaign as a natural experiment is valid but requires that the campaign only affected parent sign-up rates and nothing else, which is hard to verify.' },
              { option_label: 'D', option_text: 'Segment DAU by age and compare year-over-year trends in the 18-24 band globally', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Global trends conflate parent-adoption effects with market saturation, platform competition, and cohort effects. This is the kind of analysis that generated the misleading correlation in the first place.' },
            ],
          },
        ],
      },
      {
        step: 'optimize',
        step_nudge: 'If causation is confirmed, what metrics distinguish healthy teen separation from damaging teen churn?',
        grading_weight: 0.30,
        step_order: 3,
        questions: [
          {
            question_text: 'Analysis confirms a small but real causal effect: parent presence reduces teen Facebook sessions by 8% but does not change Instagram sessions. What is the right strategic interpretation?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'cognitive_empathy'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'The 8% session drop is a problem to fix by building features that increase teen privacy on Facebook', quality: 'good_but_incomplete', points: 2, competencies: ['cognitive_empathy'], explanation: 'Privacy features may help but the finding that Instagram is unaffected is the key signal. The issue is platform-specific, not Meta-wide.' },
              { option_label: 'B', option_text: 'Teens are migrating within Meta\'s portfolio, not churning from it; Facebook sessions drop but Instagram holds, so net Meta time-on-platform is largely flat', quality: 'best', points: 3, competencies: ['strategic_thinking', 'cognitive_empathy'], explanation: 'Within-portfolio migration is a strategic win, not a loss. The correct framing is cross-app engagement, not single-app retention. Meta\'s portfolio strategy exists precisely for this scenario.' },
              { option_label: 'C', option_text: 'An 8% session drop is within noise and should be deprioritized in favor of higher-ROI growth levers', quality: 'surface', points: 1, competencies: ['strategic_thinking'], explanation: 'The analysis confirmed causation. Dismissing a confirmed causal effect as noise is a different error from recognizing it is small.' },
              { option_label: 'D', option_text: 'Launch a product intervention to reduce parent content visibility to teen feeds to restore pre-parent engagement levels', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Intervening to keep teens on Facebook while parents are present creates a deceptive experience and contradicts the safety narrative Meta has built around teen products.' },
            ],
          },
        ],
      },
      {
        step: 'win',
        step_nudge: 'What specific metric threshold signals that parent adoption is tipping into a net negative for the teen cohort?',
        grading_weight: 0.20,
        step_order: 4,
        questions: [
          {
            question_text: 'What is the right success metric and threshold to monitor going forward?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'domain_expertise'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Monitor teen Facebook DAU and alert if it drops more than 5% in a 30-day window after parent sign-up cohorts exceed 40% penetration in a market', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Single-app DAU is the wrong unit of analysis given the Instagram migration finding. This measure would falsely alarm on healthy within-portfolio shifts.' },
              { option_label: 'B', option_text: 'Track combined Meta teen time-on-platform (Facebook + Instagram) for households where a parent joined, with a threshold alert if cross-app combined minutes drop more than 10% vs. the matched control cohort', quality: 'best', points: 3, competencies: ['strategic_thinking', 'domain_expertise'], explanation: 'Portfolio-level metric is the correct unit. The threshold is testable and tied directly to the causal analysis methodology, making it actionable rather than arbitrary.' },
              { option_label: 'C', option_text: 'Use NPS from the 18-24 segment as the leading indicator of teen satisfaction and monitor quarterly', quality: 'surface', points: 1, competencies: ['cognitive_empathy'], explanation: 'NPS is too slow to capture month-to-month migration effects and too noisy to isolate the parent-adoption signal from general sentiment.' },
              { option_label: 'D', option_text: 'No ongoing monitoring needed once the causal analysis is complete; revisit annually in the growth review', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'One-time analysis does not produce ongoing signal. Platform dynamics change and annual reviews cannot catch emerging effects in time to respond.' },
            ],
          },
        ],
      },
    ],
  },

  {
    id: 'pm-meta-004',
    title: 'Promoting Instagram Inside the Facebook App',
    scenario_role: 'Growth PM, Facebook',
    scenario_context: 'The Facebook Growth team has a mandate to accelerate Instagram sign-ups among existing Facebook users who do not yet have an Instagram account. The Facebook app has 3 billion monthly active users; Instagram sign-up rates from Facebook-originated flows have historically been below benchmark.',
    scenario_trigger: 'A leadership review shows that Facebook-to-Instagram cross-promotion has driven fewer conversions than organic search and app-store discovery for two consecutive quarters. The team is asked to redesign the promotion strategy.',
    scenario_question: 'Where and how should cross-promotion from Facebook to Instagram be run to maximize net new Instagram users without degrading Facebook engagement or trust?',
    engineer_standout: 'A strong engineer would identify that placement and timing are a personalization problem, that naive interstitials hurt session depth, and that the optimal trigger is an intent signal rather than a frequency schedule.',
    paradigm: 'traditional',
    industry: 'Social Media',
    sub_vertical: 'Cross-Platform Growth',
    difficulty: 'standard',
    estimated_minutes: 18,
    primary_competencies: ['strategic_thinking', 'creative_execution'],
    secondary_competencies: ['cognitive_empathy'],
    frameworks: ['Jobs To Be Done', 'Growth Loops'],
    relevant_roles: ['pm', 'swe', 'ml_eng'],
    company_tags: ['Meta', 'Instagram', 'Facebook'],
    tags: ['cross-promotion', 'growth', 'instagram', 'facebook', 'acquisition'],
    is_published: true,
    is_calibration: false,
    is_premium: false,
    steps: [
      {
        step: 'frame',
        step_nudge: 'Why has Facebook cross-promotion underperformed organic discovery, and what does that imply about user mindset during Facebook sessions?',
        grading_weight: 0.25,
        step_order: 1,
        questions: [
          {
            question_text: 'What best explains why Facebook-to-Instagram promotions have underperformed organic discovery?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'cognitive_empathy'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'The promotions are shown too infrequently and need higher display volume', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Increasing frequency on a low-intent surface amplifies the mismatch between ad message and user mindset. More impressions of the wrong context do not improve conversion.' },
              { option_label: 'B', option_text: 'Users already in a Facebook session have a consumption mindset, not an exploration mindset, so Instagram discovery pitches create friction rather than opportunity', quality: 'best', points: 3, competencies: ['strategic_thinking', 'cognitive_empathy'], explanation: 'Mindset mismatch is the root cause. Organic search and App Store discovery work because users arrive with intent. Promotions inside an active Facebook session interrupt rather than meet a job.' },
              { option_label: 'C', option_text: 'Facebook users who do not have Instagram yet are older and less likely to adopt any new social app', quality: 'good_but_incomplete', points: 2, competencies: ['cognitive_empathy'], explanation: 'Demographics matter but do not explain the gap relative to organic. Some of those same users did convert via organic channels, so the channel is the variable to explain.' },
              { option_label: 'D', option_text: 'The creative assets in Facebook promotions are lower quality than Instagram\'s own onboarding', quality: 'surface', points: 1, competencies: ['creative_execution'], explanation: 'Creative quality is a real lever but a secondary one. Even best-in-class creative on the wrong surface at the wrong moment will underperform.' },
            ],
          },
        ],
      },
      {
        step: 'list',
        step_nudge: 'What are structurally distinct placement or trigger strategies, each with a different underlying intent signal?',
        grading_weight: 0.25,
        step_order: 2,
        questions: [
          {
            question_text: 'Which of the following represents the most distinct set of cross-promotion placement strategies?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['creative_execution', 'strategic_thinking'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'News Feed ads, Stories ads, and Reels interstitials', quality: 'surface', points: 1, competencies: ['creative_execution'], explanation: 'All three are mid-session interruptions on the same consumption surface. They are variations on one approach, not structurally distinct strategies.' },
              { option_label: 'B', option_text: 'Intent-triggered prompt when user searches for a creator who is more active on Instagram; session-end card after organic share; onboarding re-engagement for dormant accounts', quality: 'best', points: 3, competencies: ['creative_execution', 'strategic_thinking'], explanation: 'Each of the three is anchored to a different intent signal: content gap, sharing momentum, and reactivation context. Structurally distinct means each could succeed or fail independently.' },
              { option_label: 'C', option_text: 'Push notifications, email re-engagement, and SMS for non-app users', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Out-of-app channels are a real strategy but describe where to reach users, not when. The strongest placements combine channel and intent signal.' },
              { option_label: 'D', option_text: 'A dedicated Instagram tab in the Facebook navigation bar', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Permanent navigation real estate for a competing app within Facebook creates UX confusion and is unlikely to pass a product review. It conflates placement with the underlying conversion mechanism.' },
            ],
          },
        ],
      },
      {
        step: 'optimize',
        step_nudge: 'Which placement do you bet on first, and what specifically are you sacrificing by choosing it over the others?',
        grading_weight: 0.30,
        step_order: 3,
        questions: [
          {
            question_text: 'You can launch one placement in Q1. Which do you choose and what is the explicit sacrifice?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'creative_execution'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Search-triggered prompt when a user searches for a creator with more Instagram followers than Facebook followers; sacrifice: requires real-time cross-platform follower data pipeline', quality: 'best', points: 3, competencies: ['strategic_thinking', 'creative_execution'], explanation: 'Highest intent signal (user already demonstrated desire for specific content) with a named, concrete sacrifice. The data pipeline cost is real and specific, not vague.' },
              { option_label: 'B', option_text: 'Reels interstitial after 3 consecutive Reels views; sacrifice: some session depth', quality: 'good_but_incomplete', points: 2, competencies: ['creative_execution'], explanation: 'Reasonable signal (visual content consumption predicts Instagram interest) but the sacrifice is under-specified. How much session depth, and is that acceptable?' },
              { option_label: 'C', option_text: 'Session-end card after user closes the app; sacrifice: low visibility since most users miss end-of-session cards', quality: 'surface', points: 1, competencies: ['strategic_thinking'], explanation: 'Session-end reduces interruption but the candidate names it as a sacrifice rather than recognizing it reduces conversion probability, which is the real tradeoff.' },
              { option_label: 'D', option_text: 'Run all three in parallel as an A/B/C test to get data faster; sacrifice: engineering resources split three ways', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Parallelizing avoids the prioritization question. The task was to choose one and name the sacrifice, which is the strategic judgment being tested.' },
            ],
          },
        ],
      },
      {
        step: 'win',
        step_nudge: 'What is the success criterion that tells you the promotion worked without being confounded by organic Instagram growth in the same period?',
        grading_weight: 0.20,
        step_order: 4,
        questions: [
          {
            question_text: 'How do you measure whether the Q1 placement drove incremental Instagram sign-ups?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'domain_expertise'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Count Instagram account creations that originated from the Facebook placement URL', quality: 'good_but_incomplete', points: 2, competencies: ['domain_expertise'], explanation: 'Attribution is necessary but not sufficient. URL attribution does not tell you whether those users would have signed up anyway through a different channel.' },
              { option_label: 'B', option_text: 'Run a holdback experiment: suppress the placement for 10% of eligible users and compare Instagram sign-up rates between holdback and exposed cohorts at 30 days', quality: 'best', points: 3, competencies: ['strategic_thinking', 'domain_expertise'], explanation: 'Holdback is the gold standard for incrementality measurement. It directly answers the counterfactual by comparing identical users with and without the promotion.' },
              { option_label: 'C', option_text: 'Compare Instagram sign-up rates month-over-month before and after the placement launches', quality: 'surface', points: 1, competencies: ['strategic_thinking'], explanation: 'Before-after comparison conflates the placement effect with seasonal trends, product changes, and external events that happened in the same window.' },
              { option_label: 'D', option_text: 'Track impressions-to-sign-up conversion rate and benchmark it against industry norms for app promotion campaigns', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Industry benchmarks do not tell you whether this specific promotion drove net new users or cannibalized organic discovery. Incrementality, not efficiency, is the question.' },
            ],
          },
        ],
      },
    ],
  },

  {
    id: 'pm-meta-005',
    title: 'Design a Product for Borrowing and Lending Money',
    scenario_role: 'Product Lead, Social Commerce',
    scenario_context: 'Peer-to-peer money lending between people who already trust each other is a real financial behavior, but it is mostly informal and often ends in broken relationships. The question is whether a product can reduce friction and conflict without introducing the regulatory complexity of a licensed lender.',
    scenario_trigger: 'A research report shows that 60% of adults have lent money to friends or family in the past year; 40% of those reported the loan created relationship tension. An executive asks you to design a product to address this.',
    scenario_question: 'Design a product that helps people borrow and lend money within trusted social networks while reducing friction, awkwardness, and repayment conflict.',
    engineer_standout: 'A strong engineer would identify the reminder and enforcement system as a graph traversal problem, consider the API surface for bank integrations, and flag the legal boundary between a social tool and a regulated lending product.',
    paradigm: 'traditional',
    industry: 'FinTech',
    sub_vertical: 'Social Finance',
    difficulty: 'standard',
    estimated_minutes: 20,
    primary_competencies: ['cognitive_empathy', 'creative_execution'],
    secondary_competencies: ['strategic_thinking'],
    frameworks: ['Jobs To Be Done', 'Behavior Change Design'],
    relevant_roles: ['pm', 'swe', 'em'],
    company_tags: ['Meta', 'Venmo', 'Cash App'],
    tags: ['product-design', 'social-finance', 'lending', 'peer-to-peer', 'meta'],
    is_published: true,
    is_calibration: false,
    is_premium: false,
    steps: [
      {
        step: 'frame',
        step_nudge: 'What is the core job a borrower and a lender each need done that is not being served by existing tools?',
        grading_weight: 0.25,
        step_order: 1,
        questions: [
          {
            question_text: 'What is the primary unsolved problem in peer lending that a product should address?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['cognitive_empathy', 'strategic_thinking'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'There is no easy way to transfer money between friends', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Venmo and Cash App already solve the transfer problem. Building another payments tool misreads the problem space entirely.' },
              { option_label: 'B', option_text: 'Lending is emotionally loaded because repayment expectations are implicit, not explicit, and reminders feel aggressive coming from a friend', quality: 'best', points: 3, competencies: ['cognitive_empathy', 'strategic_thinking'], explanation: 'The implicit expectation gap is the root cause of both relationship tension and non-repayment. A product that externalizes the terms and automates reminders removes the social cost from the human relationship.' },
              { option_label: 'C', option_text: 'People do not track informal loans accurately so they forget what is owed', quality: 'good_but_incomplete', points: 2, competencies: ['cognitive_empathy'], explanation: 'Tracking is a symptom of the implicit-terms problem but not the whole story. Even people who track informal loans face awkwardness in following up.' },
              { option_label: 'D', option_text: 'Small-dollar lending is under-served by banks and requires a new financial product category', quality: 'surface', points: 1, competencies: ['domain_expertise'], explanation: 'This frames the problem as a market gap rather than a social behavior gap. The target user already has access to credit; they choose peer lending to preserve relationships.' },
            ],
          },
        ],
      },
      {
        step: 'list',
        step_nudge: 'What are the distinct product paradigms for handling repayment expectations, reminders, and disputes?',
        grading_weight: 0.25,
        step_order: 2,
        questions: [
          {
            question_text: 'Which set of product concepts represents the most structurally distinct approaches to the lending product?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['creative_execution', 'strategic_thinking'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Loan tracking app, shared IOU ledger, and a loan contract generator', quality: 'surface', points: 1, competencies: ['creative_execution'], explanation: 'All three are record-keeping tools. They differ in format but share the same underlying model: passive documentation without a repayment mechanism.' },
              { option_label: 'B', option_text: 'Escrow-funded loans with scheduled auto-repayment; social nudge system where a mutual friend mediates overdue loans; and an interest-earning lender pool for trusted circles', quality: 'best', points: 3, competencies: ['creative_execution', 'strategic_thinking'], explanation: 'Each approach uses a different mechanism for the hardest part (repayment enforcement): automated financial rails, social graph pressure, and aligned incentive structures. Genuinely non-overlapping.' },
              { option_label: 'C', option_text: 'Mobile app with push reminders, email digest of outstanding loans, and a web dashboard', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'These are notification channels, not product concepts. The question is what mechanism enforces repayment, not how you remind people.' },
              { option_label: 'D', option_text: 'Informal loan tracking with optional interest, plus a "forgive loan" button for lenders', quality: 'good_but_incomplete', points: 2, competencies: ['cognitive_empathy'], explanation: 'This is one coherent product but a single option, not a list of distinct concepts. The forgive button is a useful insight about lender psychology but does not constitute a full product paradigm.' },
            ],
          },
        ],
      },
      {
        step: 'optimize',
        step_nudge: 'Which concept do you build first, and what specific feature do you cut to stay within a 3-month timeline?',
        grading_weight: 0.30,
        step_order: 3,
        questions: [
          {
            question_text: 'You choose to build the scheduled auto-repayment concept. What is the highest-risk dependency to cut in v1?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['creative_execution', 'strategic_thinking'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Cut the bank-linking integration; require manual repayment confirmation instead of automated pull', quality: 'best', points: 3, competencies: ['creative_execution', 'strategic_thinking'], explanation: 'Bank linking (ACH or Plaid integration) is the highest regulatory and technical risk in v1. Manual confirmation preserves the loan tracking value while deferring the complex financial infrastructure to v2 once compliance posture is clear.' },
              { option_label: 'B', option_text: 'Cut the social graph component; make the product private and not tied to any social network', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Decoupling from social graph reduces virality but is a legitimate scope choice. However, the social graph is less technically risky than bank linking, so it is not the highest-risk cut.' },
              { option_label: 'C', option_text: 'Cut dispute resolution; tell users to handle disputes outside the app', quality: 'surface', points: 1, competencies: ['cognitive_empathy'], explanation: 'Dispute resolution is important but not the v1 critical path. Cutting it is reasonable but does not address the highest dependency risk.' },
              { option_label: 'D', option_text: 'Cut the repayment schedule feature and ship a basic loan tracker first', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'The repayment schedule is the core differentiator from existing tools like Splitwise. Cutting it leaves a product indistinguishable from the IOU apps that already exist.' },
            ],
          },
        ],
      },
      {
        step: 'win',
        step_nudge: 'What is the single metric that tells you whether this product is actually reducing relationship tension, not just tracking loans?',
        grading_weight: 0.20,
        step_order: 4,
        questions: [
          {
            question_text: 'Which metric best measures whether the product is solving the real problem rather than just processing transactions?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'cognitive_empathy'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: '% of loans fully repaid within the agreed timeframe', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Repayment rate measures financial completion but not relationship quality. A high repayment rate could be achieved by scaring users with aggressive reminders, which is exactly the experience the product should eliminate.' },
              { option_label: 'B', option_text: 'Re-use rate: % of users who complete one loan and initiate a second within 90 days', quality: 'best', points: 3, competencies: ['strategic_thinking', 'cognitive_empathy'], explanation: 'Re-use is the behavioral signal that the experience did not damage the relationship. If lenders and borrowers use the product again, the trust loop held. It is a direct measure of the product\'s core promise.' },
              { option_label: 'C', option_text: 'Total loan volume processed in the first 6 months', quality: 'surface', points: 1, competencies: ['strategic_thinking'], explanation: 'Volume is a vanity metric that measures adoption, not whether the product solved the tension problem. A high-volume product can still be creating conflict.' },
              { option_label: 'D', option_text: 'NPS from both borrowers and lenders after each completed loan', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'NPS at loan completion is a lagging sentiment metric. Users may rate positively immediately after repayment but the relationship impact reveals itself over months, not at the moment of payoff.' },
            ],
          },
        ],
      },
    ],
  },

  {
    id: 'pm-meta-006',
    title: "Instagram's Biggest Threat Right Now",
    scenario_role: 'Strategy Lead, Instagram',
    scenario_context: 'Instagram sits at roughly 2 billion monthly users but faces intensifying competition, creator monetization pressure, and regulatory scrutiny in multiple markets. Internal data suggests time-spent per session is flat while rival platforms show growth. The senior leadership team is running an annual threat review.',
    scenario_trigger: 'The VP of Strategy asks each product area lead to submit a one-slide view of the single biggest external threat to Instagram in the next 18 months.',
    scenario_question: "What is the most significant threat to Instagram's core business right now, and why does it outrank the other candidates?",
    engineer_standout: 'A strong engineer would frame threat as a systems problem: what dependency or leverage point does a competitor or regulator have that Instagram cannot neutralize without a fundamental platform change?',
    paradigm: 'traditional',
    industry: 'Social Media',
    sub_vertical: 'Photo and Video Sharing',
    difficulty: 'advanced',
    estimated_minutes: 20,
    primary_competencies: ['strategic_thinking', 'domain_expertise'],
    secondary_competencies: ['motivation_theory'],
    frameworks: ['Competitive Analysis', 'Systems Thinking'],
    relevant_roles: ['pm', 'em', 'tech_lead'],
    company_tags: ['Meta', 'Instagram', 'TikTok', 'YouTube'],
    tags: ['strategy', 'instagram', 'competitive-threat', 'meta', 'platform'],
    is_published: true,
    is_calibration: false,
    is_premium: false,
    steps: [
      {
        step: 'frame',
        step_nudge: 'What does "biggest threat" actually mean here: the most likely, the most severe, or the hardest to defend against?',
        grading_weight: 0.25,
        step_order: 1,
        questions: [
          {
            question_text: 'What is the right framing for evaluating which threat to Instagram is most significant?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'domain_expertise'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'The threat that is growing fastest in terms of user acquisition among 18-24 year olds', quality: 'good_but_incomplete', points: 2, competencies: ['domain_expertise'], explanation: 'User growth among young adults is a relevant signal but does not distinguish between a temporary trend and a structural platform shift. Many fast-growing products plateau.' },
              { option_label: 'B', option_text: 'The threat that is hardest for Instagram to neutralize without changing its core product identity', quality: 'best', points: 3, competencies: ['strategic_thinking', 'domain_expertise'], explanation: 'Defensive difficulty is the right lens. A threat Instagram can copy (format, feature) is manageable. A threat that requires Instagram to contradict its brand, algorithm, or business model is existential.' },
              { option_label: 'C', option_text: 'The threat with the largest potential TAM impact on Instagram\'s ad revenue over 5 years', quality: 'surface', points: 1, competencies: ['strategic_thinking'], explanation: 'Revenue impact is important but a 5-year financial model obscures near-term inflection points. The leadership team asked about the next 18 months specifically.' },
              { option_label: 'D', option_text: 'Any threat that has triggered regulatory action in at least two markets', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Regulatory trigger is an interesting filter but conflates external legal risk with competitive and product risk. The three categories require different responses.' },
            ],
          },
        ],
      },
      {
        step: 'list',
        step_nudge: 'Name the top three threat candidates with the mechanism by which each could damage Instagram, then rank them.',
        grading_weight: 0.25,
        step_order: 2,
        questions: [
          {
            question_text: 'Which list of threats, with mechanisms, is most analytically complete?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'domain_expertise'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'TikTok (algorithm-driven discovery), YouTube Shorts (creator monetization), and BeReal (authentic content trend)', quality: 'good_but_incomplete', points: 2, competencies: ['domain_expertise'], explanation: 'Three real threats, but BeReal has not demonstrated durable retention and conflates a product trend with a structural platform competitor. The list is incomplete without regulatory risk.' },
              { option_label: 'B', option_text: "TikTok's recommendation engine eroding creator-follower graph value; potential US TikTok ban eliminating the biggest engagement competitor; EU DMA forcing interoperability that commoditizes Instagram's closed social graph", quality: 'best', points: 3, competencies: ['strategic_thinking', 'domain_expertise'], explanation: 'This list spans competitive, geopolitical, and regulatory threat categories with a specific mechanism for each. The DMA interoperability risk is a genuinely hard-to-neutralize structural threat.' },
              { option_label: 'C', option_text: 'Creator burnout, declining organic reach, and rising ad load frustration', quality: 'surface', points: 1, competencies: ['cognitive_empathy'], explanation: 'These are internal platform health issues, not external threats. The question asks about what is coming from outside Instagram, not what Instagram is doing to itself.' },
              { option_label: 'D', option_text: 'AI-generated content flooding the feed, reducing authentic human content and trust', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'AI content is a real tension but affects all platforms equally and is not an external threat that a specific competitor or regulator is weaponizing against Instagram specifically.' },
            ],
          },
        ],
      },
      {
        step: 'optimize',
        step_nudge: "Given the threats you named, which one should Instagram actually be most afraid of, and what resource trade-off does prioritizing it require?",
        grading_weight: 0.30,
        step_order: 3,
        questions: [
          {
            question_text: "You argue that TikTok's recommendation algorithm is the #1 threat. What is the hardest internal sacrifice Instagram must make to defend against it?",
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'domain_expertise'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Instagram must sacrifice the social graph feed (posts from people you follow) by moving to full interest-based ranking, which means reducing the value of follower count as a creator metric', quality: 'best', points: 3, competencies: ['strategic_thinking', 'domain_expertise'], explanation: "This is the named, specific sacrifice. Moving to interest-graph ranking directly contradicts Instagram's founding model and alienates established creators with large followings who built their business on the follower mechanic." },
              { option_label: 'B', option_text: "Instagram must copy TikTok's 60-second video format as the default content type", quality: 'surface', points: 1, competencies: ['creative_execution'], explanation: 'Format copying is already underway with Reels. This does not name the underlying sacrifice in the recommendation model and understates the identity conflict.' },
              { option_label: 'C', option_text: 'Instagram must reduce ad frequency to improve content quality signals', quality: 'plausible_wrong', points: 0, competencies: [], explanation: "Reducing ad load trades revenue for engagement but does not address TikTok's core advantage, which is content discovery quality, not ad quantity." },
              { option_label: 'D', option_text: 'Instagram must invest in creator monetization tools so creators stay on the platform rather than moving to TikTok', quality: 'good_but_incomplete', points: 2, competencies: ['motivation_theory'], explanation: 'Creator retention is a real lever but it treats a symptom (creators leaving) rather than the root cause (discovery algorithm quality making TikTok a better content-audience match engine).' },
            ],
          },
        ],
      },
      {
        step: 'win',
        step_nudge: "What is the one recommendation you put on the VP's slide, and what measurable signal would confirm you were right within 12 months?",
        grading_weight: 0.20,
        step_order: 4,
        questions: [
          {
            question_text: "What is the crisp, testable recommendation for the VP's one-slide threat view?",
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'creative_execution'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: "Biggest threat: TikTok's interest-graph algorithm eroding Instagram's social-graph moat. Recommendation: shift Reels ranking to 70% interest-graph by Q3; success signal: time-in-Reels for non-follower content grows 15% YoY in the 18-24 cohort", quality: 'best', points: 3, competencies: ['strategic_thinking', 'creative_execution'], explanation: 'Specific threat mechanism, named intervention with a percentage target, and a testable metric with a threshold and timeline. Exactly what a VP slide needs.' },
              { option_label: 'B', option_text: 'Instagram must watch TikTok closely and respond quickly to product changes with Reels iterations', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Reactive monitoring is not a strategy. This is the kind of non-answer that should not survive a leadership review.' },
              { option_label: 'C', option_text: 'Biggest threat: regulatory fragmentation. Recommendation: dedicate a policy team to DMA compliance to avoid forced interoperability', quality: 'good_but_incomplete', points: 2, competencies: ['domain_expertise'], explanation: 'Regulatory framing is defensible but compliance is a maintenance activity, not a competitive strategy. It addresses a floor, not a ceiling.' },
              { option_label: 'D', option_text: 'Biggest threat: creator migration to TikTok. Recommendation: increase creator payouts by 30% to anchor top accounts', quality: 'surface', points: 1, competencies: ['motivation_theory'], explanation: 'Creator payouts address retention but not the algorithmic discovery advantage. Paying more for content that reaches fewer interested users does not close the competitive gap.' },
            ],
          },
        ],
      },
    ],
  },

  {
    id: 'pm-meta-007',
    title: 'CEO of Meta: Top 3 Priorities for the Next 5 Years',
    scenario_role: 'Strategy Executive',
    scenario_context: 'Meta has built a portfolio spanning social media, virtual reality, AI infrastructure, and messaging. The company generates roughly $130B in annual revenue, almost entirely from advertising. Hardware (Quest) and AI investments are growing fast but remain pre-profit. The board is asking for a 5-year strategic vision.',
    scenario_trigger: 'In an all-hands, the CEO is asked directly: "Given everything the company is betting on, what are your three biggest priorities for the next five years and why those three?"',
    scenario_question: "If you were Meta's CEO, what would your top three priorities be for the next five years, and how do they hold together as a coherent strategy?",
    engineer_standout: 'A strong engineer would think about infrastructure leverage points: where does a technical investment (AI compute, spatial computing OS, messaging protocol) create compounding returns across the portfolio rather than siloed product bets?',
    paradigm: 'traditional',
    industry: 'Technology Conglomerate',
    sub_vertical: 'Social and AR/VR',
    difficulty: 'advanced',
    estimated_minutes: 22,
    primary_competencies: ['strategic_thinking', 'domain_expertise'],
    secondary_competencies: ['motivation_theory'],
    frameworks: ['Platform Strategy', 'Portfolio Theory'],
    relevant_roles: ['pm', 'em', 'tech_lead'],
    company_tags: ['Meta', 'Apple', 'Google', 'Microsoft'],
    tags: ['strategy', 'meta', 'ceo-priorities', 'vision', 'portfolio'],
    is_published: true,
    is_calibration: false,
    is_premium: false,
    steps: [
      {
        step: 'frame',
        step_nudge: "Before naming priorities, what makes this question hard for a company with Meta's specific portfolio and constraints?",
        grading_weight: 0.25,
        step_order: 1,
        questions: [
          {
            question_text: "What is the central strategic tension that a 5-year priority list for Meta must resolve?",
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'domain_expertise'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Meta is too diversified; it needs to focus on its core social media business and exit hardware', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Focus on core is a legitimate argument but not the tension a CEO must resolve in a 5-year view. It ignores the strategic reasons Meta entered hardware and AI in the first place.' },
              { option_label: 'B', option_text: "Meta's short-term cash engine (ads) and long-term platform bets (AR/VR, AI) require different organizational cultures, time horizons, and success metrics that are hard to run in parallel", quality: 'best', points: 3, competencies: ['strategic_thinking', 'domain_expertise'], explanation: 'The core tension is time horizon mismatch: the ad business demands quarterly optimization while the next-platform bets require 5-10 year patient capital. A CEO priority list that does not address this tension is incomplete.' },
              { option_label: 'C', option_text: 'Meta faces increasing regulatory scrutiny and must prioritize compliance over growth', quality: 'surface', points: 1, competencies: ['domain_expertise'], explanation: "Regulatory risk is real but it is a constraint, not the central strategic tension. Framing priorities as compliance responses gives up the CEO's agency to shape the company's trajectory." },
              { option_label: 'D', option_text: 'The AI investment is too expensive and risks the ad business margins needed to fund everything else', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Capital allocation is part of the tension but understates it. The harder problem is cultural and organizational, not just financial.' },
            ],
          },
        ],
      },
      {
        step: 'list',
        step_nudge: 'Name at least four candidate priorities before choosing three. What principle distinguishes a genuine priority from a tactic?',
        grading_weight: 0.25,
        step_order: 2,
        questions: [
          {
            question_text: 'Which set of priorities represents a coherent 5-year strategy, not just a list of initiatives?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'domain_expertise'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: '(1) Grow ad revenue 15% YoY; (2) ship next Quest hardware cycle; (3) launch AI assistant in all apps', quality: 'surface', points: 1, competencies: ['strategic_thinking'], explanation: 'These are targets, not strategies. A priority needs to explain what Meta is choosing to do instead of alternatives, and why that choice compounds over time.' },
              { option_label: 'B', option_text: '(1) Own the AI-native social graph that makes ads more valuable than any competitor can match; (2) establish Meta AI as the default assistant layer before Apple and Google lock users in; (3) make the Quest the enterprise productivity platform before Apple Vision Pro wins that market', quality: 'best', points: 3, competencies: ['strategic_thinking', 'domain_expertise'], explanation: 'Each priority names a specific market position to own, a named competitor to beat, and a consequence if the bet is lost. They form a coherent narrative about Meta\'s long-term leverage.' },
              { option_label: 'C', option_text: '(1) Teen safety and regulatory trust; (2) creator monetization; (3) reducing ad load to improve content quality', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'These are defensive operational priorities, not strategic bets. A CEO setting a 5-year direction should be naming where the company will win, not just what risks it will mitigate.' },
              { option_label: 'D', option_text: '(1) Diversify revenue beyond ads via commerce and subscription; (2) international market penetration; (3) AI research investment to stay at the frontier', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Revenue diversification and international expansion are legitimate bets, but the list does not explain how the three connect or what makes Meta uniquely positioned to win each of them.' },
            ],
          },
        ],
      },
      {
        step: 'optimize',
        step_nudge: 'Given the three priorities you named, what is the hardest resource trade-off the CEO must be willing to make explicit?',
        grading_weight: 0.30,
        step_order: 3,
        questions: [
          {
            question_text: 'Between the AI assistant bet and the AR/VR hardware bet, which gets more capital in a constrained budget scenario, and what is the named sacrifice?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'domain_expertise'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'AI assistant gets more capital; sacrifice is slowing Quest hardware iteration to annual cadence instead of every 18 months, accepting that Apple Vision Pro may set the enterprise form factor standard', quality: 'best', points: 3, competencies: ['strategic_thinking', 'domain_expertise'], explanation: 'Specific capital choice, specific named sacrifice (hardware cadence), and specific consequence (Apple sets enterprise standard). This is a real strategic trade-off with an identifiable cost.' },
              { option_label: 'B', option_text: 'Both get equal capital because they serve different markets and timelines', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Equal allocation avoids the trade-off instead of naming it. In a constrained budget, equal splits are usually a sign of political compromise, not strategic clarity.' },
              { option_label: 'C', option_text: 'AR/VR gets more capital because it is a 10-year bet that requires sustained investment before returns', quality: 'good_but_incomplete', points: 2, competencies: ['domain_expertise'], explanation: 'The long-horizon argument is defensible but does not name the sacrifice. What does Meta give up on the AI side by making this choice?' },
              { option_label: 'D', option_text: 'Cut AR/VR entirely and redeploy all capital to AI; the spatial computing bet has not proven product-market fit', quality: 'surface', points: 1, competencies: ['strategic_thinking'], explanation: 'Exiting AR/VR is a coherent option but the phrase "cut entirely" avoids acknowledging that the platform bet has already generated real developer ecosystem investment that would be lost.' },
            ],
          },
        ],
      },
      {
        step: 'win',
        step_nudge: 'How does the CEO communicate these three priorities so that 70,000 employees know what to do differently on Monday?',
        grading_weight: 0.20,
        step_order: 4,
        questions: [
          {
            question_text: 'Which communication approach best translates a 5-year strategic vision into organizational action?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['creative_execution', 'motivation_theory'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Publish the three priorities in a company memo with historical context and Q&A, then cascade them through each VP\'s OKR cycle with explicit priority weighting', quality: 'best', points: 3, competencies: ['creative_execution', 'motivation_theory'], explanation: 'Memo plus OKR cascade connects vision to action. Publishing creates alignment and accountability; OKR weighting forces VPs to make the same trade-offs the CEO named at their level.' },
              { option_label: 'B', option_text: 'Present the priorities at all-hands and invite employees to submit questions', quality: 'surface', points: 1, competencies: ['motivation_theory'], explanation: 'All-hands creates awareness but not alignment. Questions surface concerns without changing how teams make daily decisions.' },
              { option_label: 'C', option_text: 'Embed the priorities in the annual performance review rubric so that all employee goals must map to one of the three', quality: 'good_but_incomplete', points: 2, competencies: ['motivation_theory'], explanation: 'Performance system alignment is powerful but takes 12 months to fully propagate and does not help teams make decisions in the near term.' },
              { option_label: 'D', option_text: 'Let each VP interpret the priorities for their own teams without top-down constraint to preserve execution speed', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Delegating interpretation produces divergent strategies across the organization. The whole point of named priorities is to create consistent decision-making criteria, not just inspiration.' },
            ],
          },
        ],
      },
    ],
  },

  {
    id: 'pm-meta-008',
    title: 'Design a Product for Gardening',
    scenario_role: 'Consumer PM',
    scenario_context: 'Gardening is a $100B hobby market in the US alone, with 55% of households participating and a disproportionate share of hobbyist time and spending going to people who are deeply engaged rather than casual growers. Most existing apps focus on plant identification rather than the ongoing practice of growing.',
    scenario_trigger: 'A product design review asks: "We have strong engagement data from plant identification features. What is the next product that serves the actual practice of gardening, not just plant curiosity?"',
    scenario_question: 'Design a product for gardening that serves the ongoing practice of growing rather than one-off plant identification, and that creates durable engagement.',
    engineer_standout: 'A strong engineer would identify the opportunity in local growing data (soil conditions, microclimate, frost dates) and ask whether the real value is personalization through sensors, hyperlocal weather APIs, or community-contributed observations.',
    paradigm: 'traditional',
    industry: 'Consumer Apps',
    sub_vertical: 'Hobbies and Lifestyle',
    difficulty: 'standard',
    estimated_minutes: 18,
    primary_competencies: ['cognitive_empathy', 'creative_execution'],
    secondary_competencies: ['strategic_thinking'],
    frameworks: ['Jobs To Be Done', 'Habit Loop'],
    relevant_roles: ['pm', 'swe', 'em'],
    company_tags: ['Meta', 'Google', 'Apple'],
    tags: ['product-design', 'gardening', 'consumer', 'engagement', 'meta'],
    is_published: true,
    is_calibration: false,
    is_premium: false,
    steps: [
      {
        step: 'frame',
        step_nudge: 'What is the job a dedicated gardener needs done that plant ID apps are not doing at all?',
        grading_weight: 0.25,
        step_order: 1,
        questions: [
          {
            question_text: 'What is the primary unmet need that a gardening practice product should address?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['cognitive_empathy', 'strategic_thinking'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Gardeners need a faster way to identify plants they encounter in stores or the wild', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Plant ID is already well served by PictureThis and iNaturalist. This replicates an existing solution rather than finding an unmet need in the practice of growing.' },
              { option_label: 'B', option_text: 'Gardeners lose track of what they planted, when tasks are due, and what worked last season, so decisions are made from memory rather than data', quality: 'best', points: 3, competencies: ['cognitive_empathy', 'strategic_thinking'], explanation: 'The memory and continuity gap is the structural unmet need. Gardening is a multi-season practice with long feedback loops. A product that builds a personalized growing record creates compounding value that one-off plant ID cannot.' },
              { option_label: 'C', option_text: 'Gardeners want a social community to share photos and get feedback', quality: 'surface', points: 1, competencies: ['cognitive_empathy'], explanation: 'Community is a growth mechanism, not a primary job. Reddit and Facebook Groups already partially serve this need. It is a secondary layer, not the core product value.' },
              { option_label: 'D', option_text: 'Gardeners need curated content like articles and videos to learn techniques', quality: 'good_but_incomplete', points: 2, competencies: ['cognitive_empathy'], explanation: 'Content is valuable but YouTube and gardening blogs already serve this reasonably well. The unmet need is personalization to the user\'s specific garden, not generic knowledge.' },
            ],
          },
        ],
      },
      {
        step: 'list',
        step_nudge: 'What are the structurally distinct product concepts that could serve the ongoing gardening practice?',
        grading_weight: 0.25,
        step_order: 2,
        questions: [
          {
            question_text: 'Which set of product concepts for gardening is most structurally distinct?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['creative_execution', 'strategic_thinking'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Garden journal app, plant care reminders app, and a pest identification app', quality: 'surface', points: 1, competencies: ['creative_execution'], explanation: 'The journal and reminder apps are both passive record-keeping tools. Pest ID repeats the plant ID model. These are three variations on two approaches.' },
              { option_label: 'B', option_text: 'A grow record tied to a plot map with hyperlocal frost and harvest timing; a community seed library that tracks what grows well in specific zip codes; and a sensor-connected plant monitoring system', quality: 'best', points: 3, competencies: ['creative_execution', 'strategic_thinking'], explanation: 'Each concept has a different data model and value proposition: personal longitudinal data, crowdsourced local data, and real-time sensor data. They are genuinely non-overlapping and serve different gardening contexts.' },
              { option_label: 'C', option_text: 'An AI chat assistant for gardening questions, plus a planting calendar with push reminders', quality: 'good_but_incomplete', points: 2, competencies: ['creative_execution'], explanation: 'Both are useful but represent a single paradigm (AI advice and scheduling). They do not include a local data or community angle, which is where the strongest differentiation lies.' },
              { option_label: 'D', option_text: 'A marketplace for buying seeds, plants, and tools with gardening content to drive discovery', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'E-commerce attached to content is a monetization strategy, not a product concept. It does not directly address the practice need and conflates the product with the business model.' },
            ],
          },
        ],
      },
      {
        step: 'optimize',
        step_nudge: 'Of the concepts you identified, which do you build first, and what is the specific feature you cut to ship in 3 months?',
        grading_weight: 0.30,
        step_order: 3,
        questions: [
          {
            question_text: 'You choose the grow record with hyperlocal timing as v1. What is the minimum viable version and the explicit cut?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['creative_execution', 'strategic_thinking'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Build manual log entries for each plant with expected harvest dates pulled from USDA hardiness zone data; cut the plot map visualization until v2', quality: 'best', points: 3, competencies: ['creative_execution', 'strategic_thinking'], explanation: 'Named feature to build (log plus USDA harvest timing), named cut (plot map visualization), and clear reasoning. USDA hardiness zone API is free and public, reducing scope. The map is valuable but not required for the core longitudinal record value.' },
              { option_label: 'B', option_text: 'Build everything but use a no-code tool to reduce development time', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'No-code tools do not eliminate scope; they change the implementation method. This avoids the prioritization question entirely.' },
              { option_label: 'C', option_text: 'Build a push notification reminder system for watering schedules as the first feature', quality: 'surface', points: 1, competencies: ['creative_execution'], explanation: 'Reminders are a feature, not a product. Without the grow record to personalize them, watering reminders are generic and compete with every calendar app.' },
              { option_label: 'D', option_text: 'Build the community seed library first because it generates network effects faster than a personal journal', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'Network effects argument is valid but the community product requires a critical mass of users with location data before it is useful. The personal grow record has single-user value from day one.' },
            ],
          },
        ],
      },
      {
        step: 'win',
        step_nudge: 'What metric tells you by end of first growing season whether the product is creating durable habit, not just novelty usage?',
        grading_weight: 0.20,
        step_order: 4,
        questions: [
          {
            question_text: 'Which metric best measures whether the gardening product is building a durable practice habit?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'cognitive_empathy'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: '% of users who open the app in year 2 growing season after using it in year 1', quality: 'best', points: 3, competencies: ['strategic_thinking', 'cognitive_empathy'], explanation: 'Year-over-year growing season retention is the definitive durability signal. Gardening is seasonal; a user who returns to the app when their garden is active again has formed a genuine practice association.' },
              { option_label: 'B', option_text: 'DAU/MAU ratio during the growing season', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'DAU/MAU measures engagement intensity but is artificially inflated during peak season. It does not tell you whether the habit persists or whether users return the following year.' },
              { option_label: 'C', option_text: 'Number of plants logged per active user in the first 90 days', quality: 'surface', points: 1, competencies: ['domain_expertise'], explanation: 'Log depth is a leading indicator of engagement but not durability. A user can log 20 plants and never return in year 2.' },
              { option_label: 'D', option_text: 'App store rating after the first growing season', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Ratings reflect satisfaction at the time of review, not whether the product is embedded in a recurring practice. Rating bias also skews toward outlier experiences.' },
            ],
          },
        ],
      },
    ],
  },

  {
    id: 'pm-meta-009',
    title: 'Instagram Stories Engagement Dropped 5% Overnight',
    scenario_role: 'Data PM, Instagram',
    scenario_context: 'Instagram Stories has 500 million daily users. A 5% engagement drop overnight on a surface at this scale has both user experience and revenue implications, since Stories is a primary ad placement. The on-call engineer notices the drop at 9am and pings the PM.',
    scenario_trigger: 'The Stories engagement metric (defined as story views divided by story impressions) dropped from an average of 68% to 63% between last night and this morning. No product changes were shipped to Stories in the past 72 hours.',
    scenario_question: 'Walk through your diagnostic approach: how do you determine whether this is a measurement error, a real user behavior change, or a technical degradation?',
    engineer_standout: 'A strong engineer would immediately segment by platform (iOS vs Android, app version), check the logging pipeline for event-drop issues, and distinguish between a change in numerator (story views) vs denominator (impressions) before assuming a user behavior change.',
    paradigm: 'traditional',
    industry: 'Social Media',
    sub_vertical: 'Stories and Short Video',
    difficulty: 'standard',
    estimated_minutes: 18,
    primary_competencies: ['strategic_thinking', 'domain_expertise'],
    secondary_competencies: ['cognitive_empathy'],
    frameworks: ['Issue Tree', 'Root Cause Analysis'],
    relevant_roles: ['pm', 'data_eng', 'swe'],
    company_tags: ['Meta', 'Instagram', 'Snapchat'],
    tags: ['metrics', 'diagnostic', 'instagram-stories', 'drop-analysis', 'debugging'],
    is_published: true,
    is_calibration: false,
    is_premium: false,
    steps: [
      {
        step: 'frame',
        step_nudge: 'Before diagnosing the drop, what structural question about the metric itself must you resolve first?',
        grading_weight: 0.25,
        step_order: 1,
        questions: [
          {
            question_text: 'What is the first question to answer before investigating the cause of the 5% drop?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'domain_expertise'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Is this a real user behavior change or a logging / measurement pipeline failure?', quality: 'best', points: 3, competencies: ['strategic_thinking', 'domain_expertise'], explanation: 'Measurement integrity is always the first question for any overnight drop. A logging bug or pipeline delay would show as a metric drop without any change in actual user behavior. Investigating behavior before confirming the data is valid wastes time.' },
              { option_label: 'B', option_text: 'Which engineering team owns Stories and should I loop them in?', quality: 'surface', points: 1, competencies: ['cognitive_empathy'], explanation: 'Escalation is a process response, not a diagnostic frame. Escalating before knowing what you are escalating about reduces credibility and wastes engineers time.' },
              { option_label: 'C', option_text: 'Did a competitor (Snapchat, TikTok) launch a feature yesterday that might explain the user shift?', quality: 'good_but_incomplete', points: 2, competencies: ['domain_expertise'], explanation: 'External competitive events are worth checking but not the first question. An overnight drop of this magnitude almost always has an internal cause, and external explanations rarely produce 24-hour inflections.' },
              { option_label: 'D', option_text: 'Which creator segments drove the drop and should we notify them?', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Notifying creators before confirming the drop is real and understanding its cause is premature and potentially damaging to trust.' },
            ],
          },
        ],
      },
      {
        step: 'list',
        step_nudge: 'Build an issue tree: what are the structurally distinct categories of root cause to check in sequence?',
        grading_weight: 0.25,
        step_order: 2,
        questions: [
          {
            question_text: 'Which diagnostic issue tree is most structurally complete for an overnight Stories engagement drop?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'domain_expertise'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Check if story posts dropped; check if view rates dropped; check if ad load increased', quality: 'good_but_incomplete', points: 2, competencies: ['domain_expertise'], explanation: 'These are three hypotheses within user behavior. The tree is missing the measurement validity branch, which should be checked first before assuming the behavior change is real.' },
              { option_label: 'B', option_text: 'Branch 1: measurement artifact (logging event drop, pipeline delay, definition change); Branch 2: supply change (fewer stories posted, lower quality content); Branch 3: demand change (users viewing fewer stories per session); Branch 4: technical degradation (load time regression, app crash rate)', quality: 'best', points: 3, competencies: ['strategic_thinking', 'domain_expertise'], explanation: 'The four branches are mutually exclusive and collectively exhaustive for an engagement rate metric. Each requires a different investigation and would produce a different fix.' },
              { option_label: 'C', option_text: 'Segment by demographics, device, and geography to find where the drop is concentrated', quality: 'surface', points: 1, competencies: ['domain_expertise'], explanation: 'Segmentation is a useful second step once you know the drop is real, but it does not constitute an issue tree. It tells you where the drop is, not what caused it.' },
              { option_label: 'D', option_text: 'Check if there was a code deploy in the past 5 days and roll it back if found', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Rolling back without a diagnosis is dangerous. The question states no changes shipped in 72 hours; jumping to rollback before confirming a code cause ignores the measurement validity question entirely.' },
            ],
          },
        ],
      },
      {
        step: 'optimize',
        step_nudge: 'You confirm the drop is real. Engagement rate fell because impressions grew 7% while views stayed flat. What does that mean and what do you do?',
        grading_weight: 0.30,
        step_order: 3,
        questions: [
          {
            question_text: 'Impressions grew 7%, views held flat, so the engagement rate fell. What is the most accurate interpretation?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'domain_expertise'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Stories feed is surfacing more stories per session but users are not watching the additional ones; the algorithm is producing quantity without quality', quality: 'best', points: 3, competencies: ['strategic_thinking', 'domain_expertise'], explanation: 'This is the correct mechanical interpretation: the denominator grew (more stories shown) while the numerator held flat (views unchanged). The algorithm inflated impressions without matching user intent. The fix is in the ranking model, not in content supply.' },
              { option_label: 'B', option_text: 'Users are posting more stories but watching fewer, indicating a supply-demand imbalance', quality: 'good_but_incomplete', points: 2, competencies: ['domain_expertise'], explanation: 'Supply-demand framing is partially correct but imprecise. Impressions are what the algorithm chose to show, not just what was posted. The algorithm decision is the proximate cause.' },
              { option_label: 'C', option_text: 'Story view rate is declining because content quality dropped among the creator base', quality: 'surface', points: 1, competencies: ['cognitive_empathy'], explanation: 'Content quality could contribute but does not explain why impressions grew simultaneously. The timing and direction of both metrics together points to an algorithm change, not a content shift.' },
              { option_label: 'D', option_text: 'The 7% impression growth is organic and the engagement rate drop is an acceptable consequence of reach expansion', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Accepting an engagement drop as a trade-off requires evidence that reach expansion creates compensating value (like new creator discovery). Without that analysis, this is rationalization, not strategy.' },
            ],
          },
        ],
      },
      {
        step: 'win',
        step_nudge: 'What specific action do you take in the next 24 hours, and what is the threshold that would make you escalate to a Sev-1?',
        grading_weight: 0.20,
        step_order: 4,
        questions: [
          {
            question_text: 'What is the right immediate action and escalation threshold given the diagnosis?',
            question_nudge: null,
            sequence: 1,
            grading_weight_within_step: 1.0,
            target_competencies: ['strategic_thinking', 'creative_execution'],
            response_type: 'mcq_plus_elaboration',
            options: [
              { option_label: 'A', option_text: 'Flag to the ranking team that the impressions/views ratio shifted by 12%; request a ranking model audit; escalate to Sev-1 if engagement rate drops another 2% in the next 24 hours or if ad revenue shows a correlated decline', quality: 'best', points: 3, competencies: ['strategic_thinking', 'creative_execution'], explanation: 'Specific action (ranking audit with precise data), specific escalation threshold (additional 2% drop or revenue signal), and named owner (ranking team). This is a complete incident response template.' },
              { option_label: 'B', option_text: 'Send a summary to the VP of Product and let them decide the escalation level', quality: 'plausible_wrong', points: 0, competencies: [], explanation: 'Escalating without a recommendation forces the VP to do the analysis you should have done. PM ownership means coming with a diagnosis and proposed action, not just an alert.' },
              { option_label: 'C', option_text: 'Monitor for 48 hours before taking action to see if it self-corrects', quality: 'surface', points: 1, competencies: ['strategic_thinking'], explanation: 'Waiting 48 hours with a confirmed real drop on a 500M-user surface with ad revenue implications is too slow. The diagnosis is already complete; the response window is hours, not days.' },
              { option_label: 'D', option_text: 'A/B test a reduced impressions-per-session cap to see if view rate recovers', quality: 'good_but_incomplete', points: 2, competencies: ['strategic_thinking'], explanation: 'An impressions cap experiment is a reasonable hypothesis but should be initiated by the ranking team with proper guardrails, not as an immediate PM-driven response to an ongoing drop.' },
            ],
          },
        ],
      },
    ],
  },
] as const
