-- Personalised study plans generated by Luma
CREATE TABLE IF NOT EXISTS user_study_plans (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  luma_rationale TEXT NOT NULL,
  move_sequence JSONB NOT NULL DEFAULT '[]',
  status TEXT NOT NULL DEFAULT 'active'
    CHECK (status IN ('active','completed','archived')),
  generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  context_snapshot JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- One active plan per user at a time
CREATE UNIQUE INDEX IF NOT EXISTS user_study_plans_user_active_idx
  ON user_study_plans (user_id)
  WHERE status = 'active';

-- RLS
ALTER TABLE user_study_plans ENABLE ROW LEVEL SECURITY;

CREATE POLICY "users can read their own plans"
  ON user_study_plans FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "service role full access to user_study_plans"
  ON user_study_plans FOR ALL
  USING (auth.role() = 'service_role');
