-- ============================================================================
-- Migration B: Trigger Hardening (R3.B + R3.C)
-- ============================================================================
-- 1. trg_recompute_topic_counts — add unchanged-skip guard + recompute
--    applies_to_types alongside challenge_count.
-- 2. trg_warn_missing_tags → enforce_tags_for_published_challenge — CASE block
--    generated from CHALLENGE_TYPE_POLICY (scripts/build-trigger-sql.ts) with
--    proper XOR handling for flow/freeform. Still RAISE NOTICE (R3.E.2 flips
--    to EXCEPTION in a future migration once admin tag review is complete).
--
-- DO NOT apply this migration until Codex has reviewed the SQL.
-- ============================================================================

BEGIN;

-- ----------------------------------------------------------------------------
-- 1. Replace trg_recompute_topic_counts
--    Changes vs. previous version:
--    a) Skip guard: if none of the tracked columns changed, return immediately.
--    b) Also recompute applies_to_types (array of distinct challenge_types) on
--       affected topics and techniques.
--    c) COALESCE(array_agg(DISTINCT ...), '{}') so empty sets produce '{}' not NULL.
-- ----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION trg_recompute_topic_counts() RETURNS TRIGGER AS $$
DECLARE
  affected_topics TEXT[];
  affected_techs  TEXT[];
BEGIN
  -- Skip guard: on UPDATE, if none of the columns we care about changed, no-op.
  IF TG_OP = 'UPDATE'
     AND NEW.is_published     IS NOT DISTINCT FROM OLD.is_published
     AND NEW.challenge_type   IS NOT DISTINCT FROM OLD.challenge_type
     AND NEW.topic_tags       IS NOT DISTINCT FROM OLD.topic_tags
     AND NEW.technique_tags   IS NOT DISTINCT FROM OLD.technique_tags THEN
    RETURN NEW;
  END IF;

  IF TG_OP = 'INSERT' THEN
    affected_topics := COALESCE(NEW.topic_tags,     '{}'::TEXT[]);
    affected_techs  := COALESCE(NEW.technique_tags, '{}'::TEXT[]);
  ELSIF TG_OP = 'DELETE' THEN
    affected_topics := COALESCE(OLD.topic_tags,     '{}'::TEXT[]);
    affected_techs  := COALESCE(OLD.technique_tags, '{}'::TEXT[]);
  ELSE -- UPDATE
    affected_topics := COALESCE(NEW.topic_tags,     '{}'::TEXT[])
                    || COALESCE(OLD.topic_tags,     '{}'::TEXT[]);
    affected_techs  := COALESCE(NEW.technique_tags, '{}'::TEXT[])
                    || COALESCE(OLD.technique_tags, '{}'::TEXT[]);
  END IF;

  IF cardinality(affected_topics) > 0 THEN
    UPDATE topics t
    SET
      challenge_count  = (
        SELECT COUNT(*)::INT
        FROM challenges c
        WHERE c.is_published = true
          AND c.topic_tags @> ARRAY[t.slug]
      ),
      applies_to_types = COALESCE((
        SELECT array_agg(DISTINCT c.challenge_type)
        FROM challenges c
        WHERE c.is_published = true
          AND c.topic_tags @> ARRAY[t.slug]
          AND c.challenge_type IS NOT NULL
      ), '{}'::TEXT[])
    WHERE t.slug = ANY(affected_topics);
  END IF;

  IF cardinality(affected_techs) > 0 THEN
    UPDATE techniques tq
    SET
      challenge_count  = (
        SELECT COUNT(*)::INT
        FROM challenges c
        WHERE c.is_published = true
          AND c.technique_tags @> ARRAY[tq.slug]
      ),
      applies_to_types = COALESCE((
        SELECT array_agg(DISTINCT c.challenge_type)
        FROM challenges c
        WHERE c.is_published = true
          AND c.technique_tags @> ARRAY[tq.slug]
          AND c.challenge_type IS NOT NULL
      ), '{}'::TEXT[])
    WHERE tq.slug = ANY(affected_techs);
  END IF;

  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

-- Re-attach trigger (function name unchanged, trigger name unchanged).
DROP TRIGGER IF EXISTS challenges_topic_counts ON challenges;
CREATE TRIGGER challenges_topic_counts
  AFTER INSERT OR UPDATE OR DELETE ON challenges
  FOR EACH ROW EXECUTE FUNCTION trg_recompute_topic_counts();

-- ----------------------------------------------------------------------------
-- 2. Replace trg_warn_missing_tags → enforce_tags_for_published_challenge
--    Per-type CASE block generated by `tsx scripts/build-trigger-sql.ts`.
--    Still RAISE NOTICE (warning level) — R3.E.2 will promote to EXCEPTION
--    once the admin tag-coverage review confirms existing challenges are clean.
-- ----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION enforce_tags_for_published_challenge() RETURNS TRIGGER AS $$
BEGIN
  -- Skip guard: if none of the relevant columns changed, no-op.
  IF TG_OP = 'UPDATE'
     AND NEW.is_published   IS NOT DISTINCT FROM OLD.is_published
     AND NEW.topic_tags     IS NOT DISTINCT FROM OLD.topic_tags
     AND NEW.technique_tags IS NOT DISTINCT FROM OLD.technique_tags
     AND NEW.move_tags      IS NOT DISTINCT FROM OLD.move_tags
     AND NEW.challenge_type IS NOT DISTINCT FROM OLD.challenge_type THEN
    RETURN NEW;
  END IF;

  IF NEW.is_published = true THEN
    -- CASE block auto-generated by scripts/build-trigger-sql.ts
    -- from CHALLENGE_TYPE_POLICY in src/lib/practice/policy.ts
    CASE NEW.challenge_type
      WHEN 'algorithm' THEN
        IF (NEW.topic_tags IS NULL OR cardinality(NEW.topic_tags) = 0) THEN
          RAISE NOTICE 'challenge %: type=algorithm requires topic_tags', NEW.id;
        END IF;
        IF (NEW.technique_tags IS NULL OR cardinality(NEW.technique_tags) = 0) THEN
          RAISE NOTICE 'challenge %: type=algorithm requires technique_tags', NEW.id;
        END IF;
      WHEN 'sql' THEN
        IF (NEW.topic_tags IS NULL OR cardinality(NEW.topic_tags) = 0) THEN
          RAISE NOTICE 'challenge %: type=sql requires topic_tags', NEW.id;
        END IF;
        IF (NEW.technique_tags IS NULL OR cardinality(NEW.technique_tags) = 0) THEN
          RAISE NOTICE 'challenge %: type=sql requires technique_tags', NEW.id;
        END IF;
      WHEN 'data_modeling' THEN
        IF (NEW.topic_tags IS NULL OR cardinality(NEW.topic_tags) = 0) THEN
          RAISE NOTICE 'challenge %: type=data_modeling requires topic_tags', NEW.id;
        END IF;
        IF (NEW.technique_tags IS NULL OR cardinality(NEW.technique_tags) = 0) THEN
          RAISE NOTICE 'challenge %: type=data_modeling requires technique_tags', NEW.id;
        END IF;
      WHEN 'system_design' THEN
        IF (NEW.topic_tags IS NULL OR cardinality(NEW.topic_tags) = 0) THEN
          RAISE NOTICE 'challenge %: type=system_design requires topic_tags', NEW.id;
        END IF;
        IF (NEW.technique_tags IS NULL OR cardinality(NEW.technique_tags) = 0) THEN
          RAISE NOTICE 'challenge %: type=system_design requires technique_tags', NEW.id;
        END IF;
      WHEN 'flow' THEN
        IF (NEW.topic_tags IS NULL OR cardinality(NEW.topic_tags) = 0) THEN
          RAISE NOTICE 'challenge %: type=flow requires topic_tags', NEW.id;
        END IF;
        IF (NEW.technique_tags IS NULL OR cardinality(NEW.technique_tags) = 0)
           AND (NEW.move_tags IS NULL OR cardinality(NEW.move_tags) = 0) THEN
          RAISE NOTICE 'challenge %: type=flow requires exactly one of [technique, move] but none are set', NEW.id;
        END IF;
        IF (NEW.technique_tags IS NOT NULL AND cardinality(NEW.technique_tags) > 0)
           AND (NEW.move_tags IS NOT NULL AND cardinality(NEW.move_tags) > 0) THEN
          RAISE NOTICE 'challenge %: type=flow requires exactly one of [technique, move] but multiple are set (technique and move)', NEW.id;
        END IF;
      WHEN 'freeform' THEN
        IF (NEW.topic_tags IS NULL OR cardinality(NEW.topic_tags) = 0) THEN
          RAISE NOTICE 'challenge %: type=freeform requires topic_tags', NEW.id;
        END IF;
        IF (NEW.technique_tags IS NULL OR cardinality(NEW.technique_tags) = 0)
           AND (NEW.move_tags IS NULL OR cardinality(NEW.move_tags) = 0) THEN
          RAISE NOTICE 'challenge %: type=freeform requires exactly one of [technique, move] but none are set', NEW.id;
        END IF;
        IF (NEW.technique_tags IS NOT NULL AND cardinality(NEW.technique_tags) > 0)
           AND (NEW.move_tags IS NOT NULL AND cardinality(NEW.move_tags) > 0) THEN
          RAISE NOTICE 'challenge %: type=freeform requires exactly one of [technique, move] but multiple are set (technique and move)', NEW.id;
        END IF;
      WHEN 'quick_take' THEN
        NULL; -- no tag requirements for type=quick_take
      WHEN 'claude_code_analytics' THEN
        NULL; -- no tag requirements for type=claude_code_analytics
      ELSE
        RAISE NOTICE 'challenge %: unknown challenge_type=%', NEW.id, NEW.challenge_type;
    END CASE;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Drop the old trigger + function and attach the new one.
DROP TRIGGER IF EXISTS challenges_warn_missing_tags ON challenges;
DROP FUNCTION IF EXISTS trg_warn_missing_tags();

DROP TRIGGER IF EXISTS challenges_enforce_tags ON challenges;
CREATE TRIGGER challenges_enforce_tags
  BEFORE INSERT OR UPDATE ON challenges
  FOR EACH ROW EXECUTE FUNCTION enforce_tags_for_published_challenge();

COMMIT;

-- ============================================================================
-- Post-migration verification (run manually after applying):
--   -- Verify new trigger is attached
--   SELECT tgname, tgtype FROM pg_trigger WHERE tgrelid = 'challenges'::regclass
--     AND tgname IN ('challenges_topic_counts','challenges_enforce_tags');
--
--   -- Verify old trigger is gone
--   SELECT COUNT(*) FROM pg_trigger WHERE tgrelid = 'challenges'::regclass
--     AND tgname = 'challenges_warn_missing_tags';
--   -- Expect: 0
--
--   -- Spot check: update a published challenge and look for RAISE NOTICE output
--   UPDATE challenges SET topic_tags = topic_tags WHERE id = (
--     SELECT id FROM challenges WHERE is_published = true LIMIT 1
--   );
-- ============================================================================
